### ISSUE TITLE
Provide config when starting the coordinator

### ISSUE THREAD

**Issue by andreogle** [api3dao/airnode#103]
This was briefly discussed internally today. The node having a hard build dependency on `config.json` (and `security.json` for now) existing is not ideal. The idea for now is to move this to the coordinator.

So, instead of starting the coordinator as:

```js
import { config } from '../core/src/config';

await coordinator.start(config.nodeSettings);
```

it would be called as something like:

```js
await coordinator.start({ config });
```
where `config` is being passed in by the deployer or the cloud provider (Lambda) itself on each invocation. This will probably need some experimentation to get right.

**Comment by bbenligiray** [comment]
I'll wait for you to implement the local version and I'll match that at the deployer. I don't want to break the tests.
