### ISSUE TITLE
Silence the deployer ethers provider

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#105]
Deployer sometimes outputs this to the terminal
```
========= NOTICE =========
Request-Rate Exceeded  (this message will not be repeated)

The default API keys for each service are provided as a highly-throttled,
community resource for low-traffic projects and early prototyping.

While your application will continue to function, we highly recommended
signing up for your own API keys to improve performance, increase your
request rate/limit and enable other perks, such as metrics and advanced APIs.

For more details: https://docs.ethers.io/api-keys/
==========================
```
The default provider needs to be overriden to silence this message:
https://github.com/ethers-io/ethers.js/issues/1036

**Comment by bbenligiray** [comment]
Turning off all logs doesn't work
https://github.com/ethers-io/ethers.js/issues/379

**Comment by ricmoo** [comment]
There is probably no need to override anything. Simply make sure you pass in your own keys. Or if you do sub-class it, return your own default keys to the static `getApiKey` method. :)

**Comment by bbenligiray** [comment]
@ricmoo Thanks for dropping by :)

This is a sort of a special case where the user doesn't know what an Ethereum provider is, doesn't have an API key to insert and will be running this only once (in a while).

We want to be more chain-agnostic anyway so I think we will move away from using the default ethers provider.

**Comment by bbenligiray** [comment]
We're now using the provider URL from `config.json`
https://github.com/api3dao/airnode/commit/27f22f30c66708d51ae9409bf3ed28ed06487faf#diff-5663c2c90283b2e61f87d95800ccea766b06ceb858857e46acdb5e48840b6ea8R21
