### ISSUE TITLE
Request: Deployment of Airnode contract in Hedera

### ISSUE THREAD

**Issue by walter-hernandez** [api3dao/airnode#1082]
## Description

Hedera launched its [Smart Contracts 2.0 in February of this year.](https://hedera.com/blog/how-to-get-event-information-from-hedera-smart-contracts) Hedera's governing council of several companies, universities and startup from different industries make an ideal candidate to for API3 to join the ecosystem.

The request is to deploy the Airnode contract in Hedera to facilitate others to create oracles that can be used with the Smart Contracts deployed in Hedera. Also, deploying in Hedera means expanding API3 reach to DLT network's different than Blockchain

**Comment by jgcogsystematictrading** [comment]
From the hethers docs it seems there are a few things that might make airnode not compatible: 
"Account creation happens on-chain. You cannot create a random hedera account by generating a pub key. Accounts must be explicitly created or implicitly using [HIP-32](https://hips.hedera.com/hip/hip-32)." 
"Gas Price is not specified by clients. The Hedera network computes the necessary gasPrice during transaction execution. More info [here](https://docs.hedera.com/guides/core-concepts/smart-contracts/gas-and-fees)."
"There is no concept of blocks, thus block related queries for filters/events or provider polling is replaced with timestamp based."

**Comment by bbenligiray** [comment]
A protocol-level integration seems infeasible but we may want to integrate Beacons at some point

**Comment by walter-hernandez** [comment]
@jgcogsystematictrading some possible solutions to what you mentioned could be:

- For the account creation, it would be to use [HIP-32](https://hips.hedera.com/hip/hip-32) for automatic account creation. 
- Since Hedera has a fixed USD prices for different transactions, it would be more straightforward to find out the gas price
- For the blocks and events, it is possible to use topics https://docs.hedera.com/guides/docs/sdks/consensus/create-a-topic

All of the above of course requires changes to the current deployment approach of Airnode. So:

@jgcogsystematictrading @bbenligiray I think an approach that can work for Hedera is to have the Airnode contract subscribed to a topic: https://docs.hedera.com/guides/docs/sdks/consensus/create-a-topic which is updated by the Airnode with new information. The Airnode contract gets updated from the topic. For I have read from Hedera's developers in Discord, this topics and smart contracts integration would be ready late this year.

The main advantage of offering API3 as an oracle in Hedera is for API3 to be the first oracle service available in Hedera, considering that Hedera has around [6.5 million transactions per day](https://decrypt.co/resources/hedera-hashgraph) and so far has more than [2 billion transactions since its beginning in 2017](https://app.dragonglass.me/hedera/home), which is more impressing considering that Ethereum has around 1[.5 million transactions since its origin in 2014](https://etherscan.io/txs)
