### ISSUE TITLE
Terraform fails at getting the region as a variable

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#110]
See:
https://github.com/terraform-providers/terraform-provider-aws/issues/8040

As a temporary fix, region is being hardcoded to the respective `.tf` file:
https://github.com/api3dao/airnode/blob/09cfa0f5f3ac890fa44bcb5d35560a60d38729e8/Dockerfile#L29

The region should be passed like the rest of variables after Terraform delivers a fix.

**Comment by bbenligiray** [comment]
Note that `remove-mnemonic:local` always attempts to remove from `us-east-1` for this reason.

**Comment by bbenligiray** [comment]
Moved the workaround from the Dockerfile to the scripts in e7e398d. This means that `remove-mnemonic:local` etc. also respect the `nodeSettings.region` value in `config.json` now.

**Comment by bbenligiray** [comment]
Note that this only applies for pre-alpha, as Terraform is not being used in v0.1.0 at the moment. We may need to revisit this if we migrate to bare Terraform instead of bare Serverless.

**Comment by andreogle** [comment]
@amarthadan I think this can be closed now, right?

**Comment by bbenligiray** [comment]
@amarthadan Can you confirm that this is fixed with the new Terraform version?

**Comment by amarthadan** [comment]
Yes, the region is read from `config.json`. Closing.

**Comment by bbenligiray** [comment]
But are you sure that Terraform respects the region you provide? Because that's the bug.

**Comment by amarthadan** [comment]
Yes, I'm sure, I've just tested it :slightly_smiling_face:
