### ISSUE TITLE
Research viability of combining multiple Dependabot PRs

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1180]
[Slack discussion](https://api3workspace.slack.com/archives/C02AYRX8D89/p1652097292961299)
https://www.hrvey.com/blog/combine-dependabot-prs

**Comment by Siegrift** [comment]
I've come accross renovate bot, which does the similar things as dependabot, but supports grouping PR.

I've played with it on my Airnode fork: https://github.com/Siegrift/airnode/pull/61 (WIP) and I like the results so far.

**Comment by amarthadan** [comment]
You forgot to close the issue. Closing.

**Comment by Siegrift** [comment]
Just to note, the renovate bot PRs (https://github.com/api3dao/airnode/pull/1290, https://github.com/api3dao/airnode/pull/1289, https://github.com/api3dao/airnode/pull/1288) were successfully created.
