### ISSUE TITLE
Make Airnode logger utility more usable for other projects

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1181]
The current [logging utility](https://github.com/api3dao/airnode/tree/master/packages/airnode-utilities/src/logging) in Airnode was built only with Airnode in mind. We’re starting using it in other tools (Airkeeper, Airseeker) and we’re running into some limitations.

I propose merging the [LogOptions](https://github.com/api3dao/airnode/blob/master/packages/airnode-utilities/src/logging/types.ts#L13) fields meta and additional into one field allowing to add any key/value pair instead of the prepared few in meta. That way it’s not bound to one project but reusable everywhere.

**Comment by Siegrift** [comment]
It would be better if we moved the logging utilities into a separate repo.

**Comment by amarthadan** [comment]
> It would be better if we moved the logging utilities into a separate repo.

What would be the difference?

Why is this blocked?

**Comment by Siegrift** [comment]
> What would be the difference?

The logging utilities should be a generic library. It's awkward to depend on a generic purpose library of a specific service (Airnode) in other services we use. I am fine with first implementing this in the Airnode, but we should still discuss this and create a new task for it if necessary.

> Why is this blocked?

Until the discussion is over and we've decided where to implement this.

**Comment by amarthadan** [comment]
> I am fine with first implementing this in the Airnode, but we should still discuss this and create a new task for it if necessary.

I agree, let's do that. Implement first under Airnode and potentially move it after.

**Comment by Siegrift** [comment]
Created https://github.com/api3dao/airnode/issues/1312.

**Comment by Siegrift** [comment]
I've started working on this and will resume after vacation. If this issue becomes a blocker and I am not back feel free to take over.

**Comment by Siegrift** [comment]
@kolenic-martin I tested this on AWS, seeing the logs metadata (coordinator ID, chainId and provider name being set correctly). Can you test on GCP and locally please?

**Comment by kolenic-martin** [comment]
Sure, no prob. I'll be off till Monday, is it okay to do it then? Or should
I squeeze this in sometime today?

**Comment by Siegrift** [comment]
Monday is fine.

**Comment by kolenic-martin** [comment]
Hi @Siegrift, sorry for the late reply but I actually tested this earlier in the week but I pushed back writing the report as I juggled other issues. The log metadata seems to be valid both in GCP and the local output. Sorry I didn't give an OK earlier.
