### ISSUE TITLE
Make Airnode use internal chain references instead of log chainIds

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1182]
Airnode trusts the `chainId` reported by the chain provider in retrieved log events. These `chainId`s are used to match up API requests with provider config. This breaks the security rule of "Don't trust the client".

Ideally, Airnode should use the config index of the chain when retrieving logs and carry that absolute index through so that API calls are matched up using a trusted reference.

This is an example of where a configured chain is retrieved based on a provider-sourced `chainId` (from AirnodeRrp’s event log): https://github.com/api3dao/airnode/commit/44de4f1045b7fb126e1effab48fdc54e17e50e5e#diff-fe629d3de1ed4c9f10a71f38e083d007938620d9f5c81fd6c9fda5bbfac62a97R45

**Comment by kolenic-martin** [comment]
Tagging @vponline for some more instructions (sorry, Michal). Thanks in advance for any instructions.

**Comment by vponline** [comment]
Sorry for not getting back to this earlier, but I am afraid that I also don't quite know how to try to test that this works (besides running the airnode-examples and confirming that they still work).

This change is supposed to protect against the blockchain provider reporting a different chainId when the transaction logs are fetched, compared to what the chainId is in the `config.json`. But I'm not quite sure how we could 'fake' the provider giving us a wrong chainId to compare that the code is actually using the chainId from the config 🤔

**Comment by amarthadan** [comment]
Hmm, I don't see how to easily test this from the user perspective either. Any ideas @Siegrift? If not, I suggest moving it to `Done`.
