### ISSUE TITLE
Support HTTP gateways with airnode-client

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1184]
We need the containerized version to include an HTTP server that supports API test calls

Related to https://github.com/api3dao/airnode/issues/480

**Comment by kolenic-martin** [comment]
The new functionality works as described in the docs; I've run the quick deploy tutorial and tried this out with various port numbers (3000 i.e. the default, 8000, 8080, 54321) as I did not come up with other variables that could potentially make this malfunction. Malformed requests are seen as such and thus are not fulfilled but that is expected.
