### ISSUE TITLE
Optimize signer wallet derivation by pre-computing the private key

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1186]
Currently, the node derives the Airnode wallet from the mnemonic to be able to sign fulfillment data. This is a computationally heavy operation that gets repeated with each request/gateway API call, which bloats our compute time. Instead, we should pre-compute the private key from the mnemonic at deployment and use that to sign data. Derivation from mnemonic is only required for deriving sponsor wallets.

See the [thread](https://api3workspace.slack.com/archives/C02AYRX8D89/p1654773375778079) for more information.

**Comment by amarthadan** [comment]
Not exactly. As mentioned in the [Slack post](https://api3workspace.slack.com/archives/C02AYRX8D89/p1654773375778079) we don't want to modify the config file but instead, add an environment variable with the derived private key. Similar to how we're currently adding the gateway URL and passing it to the heartbeat.

> We'd need to keep the existing functionality for local use however, right?
I don't think we need to though. I think we can do the same for the non-cloud version.

**Comment by vponline** [comment]
@kolenic-martin To test this all you need to do is try that an **airnode-example** deployment/removal works so this can be tested alongside something else.

**Comment by amarthadan** [comment]
@kolenic-martin Just to clarify, please, test both local and cloud versions (both AWS and GCP actually) because there are changes all over the place.

**Comment by kolenic-martin** [comment]
Hi @amarthadan, I've tested this as a part of another test, running Airnode (the coingecko example) both locally and on the two cloud providers. I did not note any issues and both the deployment and the request have been performed correctly.
