### ISSUE TITLE
Refactor `callApi` handler so it can be called without the whole configuration

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1187]
Based on the research done in https://api3dao.atlassian.net/browse/AN-749

**Comment by acenolaza** [comment]
PR: https://github.com/api3dao/airnode/pull/1308

**Comment by amarthadan** [comment]
Should this be in `In review`? The PR is still a draft and you're still working on it AFAIK.

**Comment by acenolaza** [comment]
> Should this be in `In review`? The PR is still a draft and you're still working on it AFAIK.

Back to "In Progress"

**Comment by acenolaza** [comment]
> Hi @acenolaza, this looks like an internals-related thing so there are no user-facing changes in terms of making requests. Is it enough if I run any of the examples to check whether that still works?

Yes, running the examples should be enough. I did run the `/operations` repo scripts to make sure requests are still being fullfilled.

**Comment by kolenic-martin** [comment]
Hi, @acenolaza, I've run a test deployment earlier today (AWS + coingecko) and this worked, so I can confirm this did not break anything and we can move this to Done.

**Comment by amarthadan** [comment]
I would definitely test also both gateways as the changes touch them as well.

**Comment by kolenic-martin** [comment]
@amarthadan thanks for noting, I'm moving this back to testing and will do that right away.

**Comment by kolenic-martin** [comment]
Hi, I've tested the coingecko-testable and coingecko-signed-data deployments locally and both on GCP and AWS. All of them perform requests and return values as they should, so I assume they are working normally. I'm moving this to Done.
