### ISSUE TITLE
Automatically remove unsuccessful Airnode deployments

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1188]
[Slack discussion](https://api3workspace.slack.com/archives/C02AYRX8D89/p1652783089926649)

**Comment by kolenic-martin** [comment]
Hi, I've tried several testing scenarios on both AWS and GCP, including:

- shutting down my network connection mid-deployment
- re-deploying to AWS after previous deployment was interrupting by Ctrl+C kill signal on the command line
- deploying with incorrect credentials
- deploying to GCP without the App Engine Admin API enabled

This either resulted in an attempt to autoremove or in a notice that the removal needs to be performed by the user, depending on the circumstances (e.g. I expect the autoremoval to fail if the connection is shut down). It seems this behaves as intended but it's pretty difficult to come up with other real-life testing scenarios as this is oftentimes tied to unexpected errors on the cloud provider's side or other "vis maior" factors, so I think if any errors appear, they will arise as I keep testing and deploying Airnode routinely. For now,I think it's safe to move this to Done.

**Comment by kolenic-martin** [comment]
Hi, I've tried several testing scenarios on both AWS and GCP, including:

- shutting down my network connection mid-deployment
- re-deploying to AWS after previous deployment was interrupting by Ctrl+C kill signal on the command line
- deploying with incorrect credentials
- deploying to GCP without the App Engine Admin API enabled

This either resulted in an attempt to autoremove or in a notice that the removal needs to be performed by the user, depending on the circumstances (e.g. I expect the autoremoval to fail if the connection is shut down). It seems this behaves as intended but it's pretty difficult to come up with other real-life testing scenarios as this is oftentimes tied to unexpected errors on the cloud provider's side or other "vis maior" factors, so I think if any errors appear, they will arise as I keep testing and deploying Airnode routinely. For now,I think it's safe to move this to Done.
