### ISSUE TITLE
requestId-keyed per-endpoint caching

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1190]
This leverages airnode-utilities caching to enable response caching. This is useful for RNG and non-idempotent API operations.

An example implementation for ANU QRNG can be found here: https://github.com/api3dao/airnode-qrng/commit/75c54a0f5dddbd2a29b7f303310356750d2fd1fc#diff-0586244b9496f86cf4c0bdd8ff5bcab4714ed16033fa4f6137e8dacdf732d124R93 

Ask @aquarat for more info if needed.

**Comment by amarthadan** [comment]
@aquarat I would have a hard time figuring out what is the issue about from the description. Can you elaborate a bit more on what needs to be done?

**Comment by aquarat** [comment]
Sure

We expect API operations to be idempotent, where calling an API multiple times will only cause one underlying action to be performed and/or the same value will always be returned.

Some APIs do not behave like this, a great example of this is the ANU QRNG API, which returns random numbers.

In the RNG example, a malicious node could manipulate random numbers being committed to the blockchain by inhibiting/holding back Airnode responses that contain random numbers that are not in their favour (they bet in a smart contract based game on '3' and then inhibit Airnode responses until the Airnode responds with a '3'.

Another example might be where a smart contract uses Airnode and a remote API to send an email. If the call succeeds but the Airnode transaction fails to be committed to the chain, we don't want an additional email being sent on every retry. 

In these scenarios it's useful to cache API responses and return the cached response. This should be enabled with an explicit OIS flag.

**Comment by dcroote** [comment]
@kolenic-martin - neither @Siegrift nor I could think of a way to test this using a cloud provider. Unless @aquarat has any ideas, perhaps you could replicate [what I did here](https://github.com/api3dao/airnode/pull/1372#issuecomment-1228063411) using hardhat & the airnode client locally?

**Comment by kolenic-martin** [comment]
Hi @dcroote, I've run the local node and client image and I had the `cacheResponses` parameter set to `true` in the config, performing several requests one after another and the cached responses did return as expected.

**Comment by dcroote** [comment]
Thanks @kolenic-martin !
