### ISSUE TITLE
Improve the visibility of mnemonic in `generate-mnemonic` command

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1192]
[Slack discussion](https://api3workspace.slack.com/archives/C01N6001YCE/p1649877336726019)

Burak: I think the nicest way would be to print the mnemonic in red

**Comment by bbenligiray** [comment]
I don't know what I was thinking, red on dark is pretty difficult to read. Maybe we can utilize some emojis somehow.

**Comment by amarthadan** [comment]
I'm not sure about emojis. Also not sure about any text styling (boldness, color, etc.). Users would most likely want to copy that mnemonic out and we want to avoid it being copied with color codes or something similar.

I would suggest going with something like:

```
This mnemonic is created locally on your machine using "ethers.Wallet.createRandom" under the hood.
Make sure to back it up securely, e.g., by writing it down on a piece of paper:

####################################### MNEMONIC #######################################
##                                                                                    ##
##    jealous anxiety dust play custom vintage member place shove cereal style wing   ##
##                                                                                    ##
####################################### MNEMONIC #######################################

The Airnode address for this mnemonic is: 0x2346D6F5019232a92e56F25e4DBB5B585e9250D1
The Airnode xpub for this mnemonic is: xpub6CfpG6iVDNEtTdjMKM135bky5ycrXG347kShBUVLoJUxjLCsSjkh3c6R7a4v15Y6arEDQTR8acL9bsQGQsWk3UM2VJr7XJWMRZrDcEGNFk3
```

**Comment by bbenligiray** [comment]
I too am a fan of ASCII art. This works very well imo.

**Comment by Siegrift** [comment]
> I pulled the mnemonic-visibility branch

Why pull that branch, when you can just test this from `master` ?

> That said, as there was a discussion regarding the ease of copying, I'd much rather see it like this:

That is a good point 👍, but I don't think it's that big of a deal, but leaving @amarthadan to decide.

**Comment by kolenic-martin** [comment]
> You couldn't have pulled mnemonic-visibility branch as it was deleted.
Was it, though?
![Image](https://user-images.githubusercontent.com/884979/174809929-27d79938-e338-4914-9fdf-72cc0313eeed.png)
>I don't see any advantage in your suggestion.
Again, copying from the console: you won't accidentally copy and hash/whitespace character.

**Comment by amarthadan** [comment]
> That said, master produces the same result, i.e. no change. Please tell me what I am supposed to do now.

@kolenic-martin What exactly did you do? It works on `master` for me. Have you rebuild the project?
I see you're running `yarn airnode-admin generate-mnemonic`. To be honest I didn't know that works :smile: But yeah, that looks for `node_modules/.bin/airnode-admin` binary and that is only "refreshed" when you do the build. Or, you can run `yarn cli generate-mnemonic` from the `packages/airnode-admin` directory (that one will work without rebuilding).

**Comment by Siegrift** [comment]
just a side note: 

It's better if @kolenic-martin keeps testing using `yarn airnode-admin` instead of the `yarn cli` because the first pattern can catch issues with wrong package.json binary path (a.k.a the validator issue in 0.7.1)

**Comment by kolenic-martin** [comment]
> But yeah, that looks for node_modules/.bin/airnode-admin binary and that is only "refreshed" when you do the build. Or, you can run yarn cli generate-mnemonic from the packages/airnode-admin directory (that one will work without rebuilding).

Yup, rebuilding the project actually helped. But tbh on standard console screen size (80x24 IIRC) it looks bad, you might want to be under that limit. Look for yourself:

![Image](https://user-images.githubusercontent.com/884979/174831160-ec805e52-ba24-4242-9eb7-1a5c68c59c59.png)

**Comment by Siegrift** [comment]
I don't think we need to honor the length character. User can just increase the size of the terminal and the general readability of the thing is more important.

**Comment by amarthadan** [comment]
Ok, I'm reopening this to change the format to be without a border for easier copying.

**Comment by kolenic-martin** [comment]
@amarthadan let me know when this is testable

**Comment by amarthadan** [comment]
@kolenic-martin Already merged 🙂

**Comment by kolenic-martin** [comment]
Sorry for the delay; I tested this in the morning, it's all good now. The whitespace/# removal makes it definitely a bit more practical.
