### ISSUE TITLE
Automatically recognize integrated chains

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1194]
Currently, one needs to update [this](https://github.com/api3dao/airnode/blob/master/packages/airnode-node/src/evm/networks.ts) when there is a new chain integration. However, airnode-protocol already knows everything about these chains, so it can export these to be used here.

* Update the [generate-references script](https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/package.json#L20) to also generate the required information about the chains and store in [references.json](https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/deployments/references.json) to be [exported](https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/src/index.ts)
* Import this information in airnode-node instead of hardcoding it

This needs to refer to https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/deployments/references.json

**Comment by kolenic-martin** [comment]
Hi @amarthadan, is there any way to test this for me? I have not generated a chain integration like ever so I might need some guidance on this. I'll be happy to learn, though.

**Comment by vponline** [comment]
@kolenic-martin  You can test this one by going to `packages/airnode-protocol`.

In there you can delete the `deployments/references.json` file and then run `yarn deploy:generate-references`.

This script should re-generate the `references.json` file and it should contain the `networks` field:
```ts
"networks": {
    "1": {
      "chainId": 1,
      "name": "homestead"
    },
...
```

**Comment by kolenic-martin** [comment]
Hi @vponline, I have proceeded as you instructed, i.e.:
- cd packages/airnode-protocol
- rm deployments/references.json
- yarn deploy:generate-references
- cat deployments/references.json
- [press PrtSc]
![image](https://user-images.githubusercontent.com/884979/174792944-af83a176-ff6f-4054-a7c5-ea7fe7a666e0.png)

This works just fine then :)
