### ISSUE TITLE
Require authorizer types to be specified

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1196]
[Slack discussion](https://api3workspace.slack.com/archives/C02AYRX8D89/p1646981665975509)
```
{
  "chains": [
    {
      "authorizers": {
        "requesterAuthorizers": [
          "$REQUESTER_AUTHORIZER_1",
          "$REQUESTER_AUTHORIZER_2"
        ]
      },
      ...
    },
    ...
  ]
}
```

**Comment by bbenligiray** [comment]
According to [this](https://github.com/api3dao/airnode/issues/1197#issuecomment-1153665996), the field name should be `requesterEndpointAuthorizers` rather than `requesterAuthorizers`

**Comment by kolenic-martin** [comment]
Hi @vponline and @amarthadan, can this be tested from the end-user perspective somehow?

**Comment by vponline** [comment]
@kolenic-martin  Sorry I forgot to update here, there is an ongoing [slack discussion](https://api3workspace.slack.com/archives/C02AYRX8D89/p1656417246277959?thread_ts=1656334347.924069&cid=C02AYRX8D89) whether this will be left for later so I don't think you need to test this for now.
