### ISSUE TITLE
Improve coingecko-signed-data integration

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1199]
From https://api3dao.atlassian.net/browse/AN-557 :
* We should prevent users from choosing the local airnode client flow as the docker client image does not have http gateway functionality
* We should print the decoded value as well as the raw JSON string

Also, from the perspective of the user, I would have the following questions:
* What is the API key and where does it come from?
* Where does the templateId value come from?

These could potentially be answered with link(s) to the docs from the integration README

**Comment by dcroote** [comment]
@kolenic-martin - for testing this `coingecko-signed-data` integration , can you confirm that:
1. You cannot choose the local Airnode client during the `choose-integration` step 
2. The README instructions (including decoding at the end) work as expected with the AWS or GCP flow

**Comment by martinkolenic** [comment]
Hi @dcroote and @amarthadan, I have run the coingecko-signed-data example and can confirm that the local option is not present in the choose-integration step:
![Image](https://user-images.githubusercontent.com/884979/173829933-9339e640-d826-4f0b-be60-5c8518534587.png)

I subsequently ran both remaining flows and they both work correctly.
