### ISSUE TITLE
Configure the Airnode logger once instead of passing options with every log call

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1201]
Currently the Airnode logger expects an `options` argument for every call. The details in `options` mostly come from the config file, which is expensive to parse. Ideally the logger should be configured once at the start of the handler runtime/first invocation. 

https://github.com/api3dao/airnode/pull/867#discussion_r814794043

**Comment by kolenic-martin** [comment]
Hi @vponline, this isn't really a user-facing issue but I did this to test it:

1. I ran the example and deployed it on AWS,
2. I made a request, which got fulfilled
3. I checked the logs on CloudWatch

It seems that there are normal log entries as usual so I assume this works correctly. Moving to Done.
