### ISSUE TITLE
Support airnode examples GCP deployments with gcp.json

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1203]
The examples README still suggest the old way of globally logging in.

**Comment by dcroote** [comment]
I believe this might be irrelevant now? [AN-573](https://api3dao.atlassian.net/browse/AN-573) was created by @Siegrift  2022-02-24 and the README now contains information on `gcp.json` including a link to the `latest/` docs:

https://github.com/api3dao/airnode/blob/982803f74af8a4de78390bc9a2881ba889257d8e/packages/airnode-examples/README.md?plain=1#L137-L148

**Comment by amarthadan** [comment]
I believe you're right. I'll wait for @Siegrift to confirm that that's what he meant by the issue and we can then move this to `Done`.

**Comment by Siegrift** [comment]
I think the issue was created before the README was updated. This can be closed now.
