### ISSUE TITLE
Use `promise-utils` library for all retries, timeouts and as an alternative for try/catch

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1204]
We've built the `promise-utils` library so it can replace all usages of the `attempt` library and custom `go` function implementation within Airnode (`airnode-utilities`)

**Comment by vponline** [comment]
> as an alternative for try/catch

Does this mean that we want to replace all uses of try/catch with the go-function? (Otherwise, I'm not sure I understand the intention of how to apply the go function in the try/catch)

**Comment by Siegrift** [comment]
> Does this mean that we want to replace all uses of try/catch with the go-function? (Otherwise, I'm not sure I understand the intention of how to apply the go function in the try/catch)

I prefer `go` for readability and there doesn't seem to be too many usages of try-catch so it shouldn't be that hard to do. Is there something I am missing?

**Comment by vponline** [comment]
> I prefer go for readability and there doesn't seem to be too many usages of try-catch so it shouldn't be that hard to do. Is there something I am missing?

No problem, I can include that as well. I just hadn't realized it was one of the intended use cases (to replace try/catch).

**Comment by amarthadan** [comment]
Yeah, I agree with @Siegrift, getting rid of the try/catch blocks in favor of `go` function would be nice.

**Comment by vponline** [comment]
@kolenic-martin 

Since this PR was simply a refactor, the functionality of Airnode should not have changed so I think you can consider this tested if you run the Airnode-Example(s) through while testing something else (as long as you have the master branch including this PR) and you don't notice any issues 😄

**Comment by kolenic-martin** [comment]
Hi @vponline, I've been attempting to test this since yesterday but my AWS deployments seem to get stuck for some reason. I've been investigating this since I started working and I hope to get some more clarity by lunchtime (UTC+2).

**Comment by kolenic-martin** [comment]
Hi, @vponline, so after lots of troubleshooting it turned out to be an AWS-related issue and the examples still run without errors.
