### ISSUE TITLE
Fix aws.env containing quotation marks causing problems

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1205]
[JIRA issue discussion](https://api3dao.atlassian.net/browse/AN-463)

**Comment by kolenic-martin** [comment]
Hi @amarthadan, what is the expected behaviour when I do have quotation marks in aws.env? Thanks.

**Comment by kolenic-martin** [comment]
Hi @vponline, thanks. I've just finished testing the deployment and removal with the quotation marks in aws.env and I can now confirm it works.
