### ISSUE TITLE
Add get-sponsor-status to the admin SDK

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1206]
`get-sponsor-status` implementation is embedded in the CLI command (https://github.com/api3dao/airnode/blob/master/packages/airnode-admin/src/cli.ts#L237-L256 ) and is not exposed by the SDK. Implement this as an SDK function and use that in the CLI command implementation instead so that people can import the respective function and use it. (I realized this was the case because I actually wanted to import and use `getSponsorStatus()` but couldn’t.)

**Comment by dcroote** [comment]
Let me know if I'm misinterpreting, but isn't the function you're looking for `sponsorToRequesterToSponsorshipStatus`? The CLI command `get-sponsor-status` calls it [here](https://github.com/api3dao/airnode/blob/69f04de9257436f5f8c1f8241b92d4461e79387c/packages/airnode-admin/src/cli.ts#L247-L248) and it's exposed in the SDK both as a [standalone function](https://github.com/api3dao/airnode/blob/260faa1104ee5170c8a884ddde02702b83cb6a85/packages/airnode-admin/src/implementation.ts#L287-L294) and [within the AdminSdk class](https://github.com/api3dao/airnode/blob/69f04de9257436f5f8c1f8241b92d4461e79387c/packages/airnode-admin/src/sdk.ts#L51-L53). 

Here is a working example per [this tx](https://goerli.etherscan.io/tx/0x3b518d4488f8257d45a0bbf129929b58afa5ca48cfc5ba724edae03bb3e47108) (it prints `true`):

```ts
import { sponsorToRequesterToSponsorshipStatus, getAirnodeRrp } from '@api3/airnode-admin';

async function run() {
  const airnodeRrp = await getAirnodeRrp('https://rpc.ankr.com/eth_goerli', {
    airnodeRrpAddress: '0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd',
  });

  const isSponsored = await sponsorToRequesterToSponsorshipStatus(
    airnodeRrp,
    '0xecf74c19215c8dd2baf16ad3a6ec1a25386d813c',
    '0xE2BC3959464a22115A7a1079e26C2fd820EB08F5'
  );
  console.log(isSponsored);
}

run();
```

**Comment by amarthadan** [comment]
Why is this in `In review`? There's no PR for it.

**Comment by amarthadan** [comment]
Ping @bbenligiray 
https://github.com/api3dao/airnode/issues/1206#issuecomment-1159596972
