### ISSUE TITLE
Report better logs when `callStatic` Reverts

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1207]
`testFulfill()` in [api-calls.ts](https://github.com/api3dao/airnode/blob/2685f63673b36556315604fdc82246a6c7f369c0/packages/airnode-node/src/evm/fulfillments/api-calls.ts#L115) does not report logs when it fails. 

Airnode just reports:

`Submitting API call fail for Request:${request.id}...`

This does not indicate if it failed in the static call or somewhere else. At AirnodeRrp we get the `no revert` string emitted in the event, which at least gives us some information to help debug, Airnode should also log where exactly it failed eg `static call fullfilment failed with : $err`

**Comment by kolenic-martin** [comment]
Hi @dcroote, any idea how to test this in an end-user role? I am not completely sure how to perform a static call :/

**Comment by Siegrift** [comment]
I don't think this can be tested from the user perspective. Let's move this to DONE.
