### ISSUE TITLE
Remove HTTP gateway endpoint URL from receipt.json

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1225]
We add the HTTP gateway endpoint URL in `receipt.json` even though this is practically a secret. Now that we’re receiving the URL through the heartbeat, we can remove it from the receipt, which makes the receipt pushable to public repos.

Note that we will need to display the URL to the deploying user in case they aren’t using the heartbeat. Printing it to the console should be fine.

**Comment by kolenic-martin** [comment]
Hi @amarthadan, I ran the coingecko example to check whether receipt.json still contains the URL with the latest pull from the master and, indeed, it's not there anymore, so your changes work as intended. This is now tested, moving.

**Comment by amarthadan** [comment]
@kolenic-martin And did it display on a terminal at the end of the deployment? That's a quite important part of this as well.

**Comment by Siegrift** [comment]
> Note that we will need to display the URL to the deploying user in case they aren’t using the heartbeat. Printing it to the console should be fine.

I fear this is going to be problematic. When I close the terminal window, the gateway URL is lost and the user is not warned about this very much... (Maybe we should add "make sure to save this URL somewhere" note)

**Comment by bbenligiray** [comment]
In a lot of use-cases they don't need to save it though. It's a fairly advanced use-case anyway so I suspect they will know about what to do with it.
