### ISSUE TITLE
Require contracts in nodeSettings.chains of config.json

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#123]
`contracts` will be a required key in `nodeSettings.chains` of `config.json`. Its value will be in the form:
```js
{
  Airnode: "0x123...456",
  Convenience: "0xabc...def"
}
```

**Comment by andreogle** [comment]
Do we want any validation to protect the user here? i.e. for chain ID 1, should it check the address against a hardcoded address? Or do we just take whatever is configured?

**Comment by bbenligiray** [comment]
I think the node should take whatever is configured, but we can have the `validator` display a warning
