### ISSUE TITLE
Automate assigning of Martin when issues is moved to `Testing`

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1234]

**Comment by amarthadan** [comment]
Waiting for @aquarat to set up a webhook so I can test it.

**Comment by aquarat** [comment]
(done)

**Comment by Siegrift** [comment]
Is this really in progress? I just merged a PR for https://github.com/api3dao/airnode/issues/1191 and it moved to testing column and assigned @kolenic-martin .

It seems to me it's done and tested.

**Comment by amarthadan** [comment]
It's deployed and apparently working :smile: I just need to commit the changes.

**Comment by amarthadan** [comment]
The same approach as for #1232
You can check the code [here](https://github.com/amarthadan/github-board-slack-notifications/commit/d32f7100e7a2d0bf3d57292c7a455373ff4f59af) but again, more polishing and proper integration to our infra will be done in a separate issue once I see it's working.

Closing.

**Comment by Siegrift** [comment]
> Closing.
You haven't closed this. But I think you should link the PR which commits it to the api3 infra and the PR should autoclose this issue when merged.

**Comment by amarthadan** [comment]
No, I'll close this, the integration to API3 infra will be a different task.
