### ISSUE TITLE
Heartbeat Payload URL is a bare domain for GCP

### ISSUE THREAD

**Issue by aquarat** [api3dao/airnode#1241]
## Description

The URL delivered in a heartbeat payload from a GCP installation is a bare domain name, as opposed to a full URL (containing `https://`). AWS installations deliver full URLs.

## Version

v0.6.5 release

## Present Behaviour

GCP Installations deliver bare domain names as a heartbeat URL in the heartbeat payload.

## Expected Behaviour

URLs should be consistent across GCP and AWS.

## Steps to reproduce

Turn on heartbeat functionality.

**Comment by amarthadan** [comment]
Yes, I fixed that for `receipt.json` but not for the heartbeat :man_facepalming:
Do we want to make a fix and release `0.6.6`?

**Comment by aquarat** [comment]
I don't think we need a new patch release for that change, it's very minor. Just something small for the future.
We're the only ones using heartbeats anyway.

**Comment by amarthadan** [comment]
Ok, I'll add it to 0.8.0, it's quite small anyway.

**Comment by kolenic-martin** [comment]
Hi, this has been tested and the GCP installation now has a `https://` in front o the URL. Moving to Done.
