### ISSUE TITLE
[0.7.x] Broken `airnode-validator` package version `0.7.0`

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1247]
Backport of https://github.com/api3dao/airnode/issues/1246 to `0.7.x`

**Comment by Siegrift** [comment]
@aquarat I'm assigning this to you, since you will re-publish `v0.7.1`

**Comment by kolenic-martin** [comment]
I'm dropping the screenshot here as well so that we know the issue might have persisted (at least on my machine):
![Image](https://user-images.githubusercontent.com/884979/174622274-61a6777f-3081-4a70-9343-9017991f53f7.png)

**Comment by aquarat** [comment]
I'll do so shortly.

**Comment by aquarat** [comment]
Apologies, I only just saw this. v0.7.2 has been published.
The airnode-validator library works as expected in my testing.

I think for our next minor version we can publish the packages to a different package repository for testing prior to publishing to npmjs.

**Comment by amarthadan** [comment]
Renaming the task and assigning @kolenic-martin (@aquarat you should have done that 😛 )

**Comment by kolenic-martin** [comment]
Hi, I'm dropping the confirmation screenshot here too, this works just fine and we can consider the issue fixed :)

![Image](https://user-images.githubusercontent.com/884979/174791446-f33fc453-12a8-4b7c-8875-29acb7ab7083.png)
