### ISSUE TITLE
Use OIS package from separate repository in Airnode

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#1274]
Blocked by https://github.com/api3dao/ois/issues/2

**Comment by amarthadan** [comment]
Can you assign priority, size, and iteration?

**Comment by Siegrift** [comment]
Blocked by https://github.com/api3dao/ois/issues/6

**Comment by kolenic-martin** [comment]
re:testing this: I'll most probably have to make sure the examples still work and that when the repo is bootstrapped and built by yarn, it pulls the package from another repo, correct?

**Comment by kolenic-martin** [comment]
Hi @Siegrift and @amarthadan , as mentioned above, it seems this could be tested by only running an example, which I've done several times today without any particular issues regarding the OIS package. I assume this is now done but feel free to ping me if not.
