### ISSUE TITLE
Remove remnants of Rinkeby and Ropsten networks

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#1280]
Ropsten and Rinkeby networks were used in Airnode for testing purposes. They are now planned to be shut down https://blog.ethereum.org/2022/06/21/testnet-deprecation/

We should remove the usages of these networks when they are shut down (ideally even before). This task should also remove references from to these networks in the docs.

**Comment by dcroote** [comment]
| Testnet | Status     | Shutdown timeline |
|---------|------------|-------------------|
| Ropsten | Deprecated | Q4 2022           |
| Rinkeby | Deprecated | Q2/Q3 2023        |
| Kovan   | Deprecated | ?                 |


Sources:
- Rinkeby & Ropsten: https://blog.ethereum.org/2022/06/21/testnet-deprecation/
- Kovan: https://ethereum.org/en/developers/docs/networks/#kovan

**Comment by bbenligiray** [comment]
There are people on Discord using these chains at the moment so I don't see the point

**Comment by dcroote** [comment]
Per [the Etherscan twitter account](https://twitter.com/etherscan/status/1569311894279958531?s=20&t=4MxzHpz_N3fMTQ9dxeQuRg):
> 📢 PSA: The Rinkeby and Ropsten testnet explorers will be deprecated on October 5th, 2022.

**Comment by dcroote** [comment]
> Then we should probably start supporting Sepolia in the same version

Created #1452

**Comment by Siegrift** [comment]
I've changed the milestone to 0.9. since https://github.com/api3dao/airnode/issues/1452 was merged to 0.9

**Comment by martinkolenic** [comment]
Hi @Siegrift, I see that these have been removed from the Airnode example script:


![Image](https://user-images.githubusercontent.com/884979/192799975-2c0f00f7-2119-49b6-b3a6-6101f1ee66d8.png)


Should I edit the config to manually force an attempt to access those testnets?

**Comment by martinkolenic** [comment]
Thanks for explaining, @dcroote! With that, I'm moving this to Done as the only user-facing change is already visible in the screenshot and working as intended.

**Comment by Siegrift** [comment]
Have you tried making RRP request using Sepolia?

**Comment by dcroote** [comment]
As part of cross-chain authorizer testing I performed the airnode-examples flow on Sepolia and it worked.
