### ISSUE TITLE
Update terraform dependencies

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#1282]
Finish https://github.com/api3dao/airnode/pull/1260 and https://github.com/api3dao/airnode/pull/1257 and ensure nothing is broken.

**Comment by amarthadan** [comment]
For this one @kolenic-martin you just need to deploy to both AWS and GCP (from the container) to make sure nothing was broken by the Terraform update.

**Comment by kolenic-martin** [comment]
Hi @Siegrift and @amarthadan, I've run an AWS and GCP deployment of the signed-data example, and the deployments were fairly smooth; the AWS deployment took about 2 minutes and the GCP about 7. I can confirm this works and the Terraform update did not break the deployment process.
