### ISSUE TITLE
Cross-chain authorizers

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1284]
Currently, the authorizer contracts specified in `chains.*.authorizers` are required to be located on the chain specified by `chains.*` (as in on Ethereum mainnet, only authorizer contracts that are deployed on mainnet can be used).

Especially for monetization functionality, we want to be able to specify authorizers on other chains. For example, say there is an authorizer on mainnet that authorizes requesters automatically when they pay USDC to the Airnode address. The Airnode is set up to have providers defined for both Rinkeby and mainnet. The authorizer on mainnet is only used on Rinkeby, while mainnet is closed to requests. This allows the Airnode operator to monetize their usage on Rinkeby.

This feature is required for ChainAPI, so I would have it in 0.9.0. Some issues with it:

- Currently, we have no way of specifying a chain with providers that doesn't accept any requests (as in the example above). In pre-alpha, when `authorizers` was defined to be `[]`, this meant everything is unauthorized on that chain. Currently, `[]` means everything is authorized, and one needs to remove the chain from `chains` to not accept any requests from it. However, in this case, we need to be able to specify providers without them being used to pick up requests, which is not supported with the current config format.
- We isolate interactions with providers (as in one Lambda invocation per provider). This flow requires two arbitrary providers to be used together. There are multiple ways of designing the Lambda invocation scheme for this and we need to decide on one (the solution below foresees no changes to the scheme, which is probably ideal since we want to wrap up v0).
- The config format needs to be updated to specify these cross-chain authorizers.

Here's a proposal (modifying https://github.com/api3dao/airnode/issues/1196 a bit):
```
"chains": [
    {
      "id": "3",
      "authorizers": [
        {
          "type": "crossChainRequesterAuthorizer",
          "chainType": "evm",
          "chainId": "1",
          "chainProvider": "${CP_SELF_HOSTED_MAINNET_URL}",
          "address": "0x1234..."
        }
      ]
    }
  ]
```

By embedding the entire chain information in the authorizer object, we don't need a chain object for Ethereum mainnet to exist. This means we don't need to worry about receiving requests on Ethereum mainnet. This provides flexibility in that we can come up with new authorizers that are not even on-chain conditions. So something like this:
```
"chains": [
    {
      "id": "3",
      "authorizers": [
        {
          "type": "http",
          "url": "https://some-authentication-api-that-is-practically-relay-metadata-but-much-nicer-because-it-lives-outside-of-ois.com"
        }
      ]
    }
  ]
```
Finally, this still allows provider-level redundancy to be specified, such as
```
"chains": [
    {
      "id": "3",
      "authorizers": [
        {
          "type": "crossChainRequesterAuthorizer",
          "chainType": "evm",
          "chainId": "1",
          "chainProvider": "${CP_SELF_HOSTED_MAINNET_URL}",
           "address": "0x1234..."
        },
        {
          "type": "crossChainRequesterAuthorizer",
          "chainType": "evm",
          "chainId": "1",
          "chainProvider": "${CP_INFURA_MAINNET_URL}",
           "address": "0x1234..."
        }
      ]
    }
  ]
```
We can also define same-chain authorizers as we did before
```
"chains": [
    {
      "id": "3",
      "authorizers": [
        {
          "type": "requesterAuthorizer",
          "address": "0x1234..."
        }
      ]
    }
  ]
```

**Comment by amarthadan** [comment]
I think the proposed solution looks good. Just to be clear, we want to support only `requesterAuthorizer` and  `crossChainRequesterAuthorizer. The `http` type was just an example of how that can be extended in the future.

**Comment by bbenligiray** [comment]
> Just to be clear, we want to support only requesterAuthorizer and crossChainRequesterAuthorizer. The http type was just an example of how that can be extended in the future.

Yes

**Comment by bbenligiray** [comment]
The two can be merged this way maybe?
```
"chains": [
    {
      "id": "3",
      "authorizers": {
        "requesterEndpointAuthorizers": [
          {
            "address": "0x1234..."
          }
        ],
        "crossChainRequesterEndpointAuthorizer": [
          {
            "chainType": "evm",
            "chainId": "1",
            "chainProvider": "${CP_SELF_HOSTED_MAINNET_URL}",
             "address": "0x1234..."
          },
          {
            "chainType": "evm",
            "chainId": "1",
            "chainProvider": "${CP_INFURA_MAINNET_URL}",
             "address": "0x1234..."
          }
        ]
      }
    }
  ]
```

**Comment by dcroote** [comment]
> The two can be merged this way maybe?

Generally it looks like it so far, and this structure lends itself to simpler validation as well 👍

**Comment by dcroote** [comment]
Thanks again for the thorough testing @martinkolenic!
