### ISSUE TITLE
Provide better validator error message for invalid "cloudProvider" settings

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#1295]
You can reproduce this by creating an invalid `cloudProvider` section inside `config.json`. E.g. missing the `projectId` for GCP configuration:

```
    ...
    "cloudProvider": {
      "type": "gcp",
      "region": "us-east1",
      "disableConcurrencyReservations": false
    }
    ...
```

results in ![Image](https://user-images.githubusercontent.com/22679154/176279959-d8b4856a-fe1e-4688-ac42-2f6b7e10dd24.png)

The issue is in https://github.com/api3dao/airnode/blob/master/packages/airnode-validator/src/config/config.ts#L186 where we should use `discriminatedUnion` instead of `union`

**Comment by dcroote** [comment]
For line at issue, I think you mean [this one](https://github.com/api3dao/airnode/blob/4c29e6b6a87389184fa2a7dfb18f39789a3d9085/packages/airnode-validator/src/config/config.ts#L232).

Using `discriminatedUnion` does not appear possible with `localOrCloudProviderSchema` because `cloudProviderSchema` is itself a `discriminatedUnion` while `localProviderSchema` is not. Others have also [run into this issue](https://github.com/colinhacks/zod/issues/1015#issuecomment-1112401462).

**Comment by dcroote** [comment]
The following works nicely, though it isn't quite as elegant given it's composed of `awsCloudProviderSchema` and `gcpCloudProviderSchema` directly rather than `cloudProviderSchema`
```ts
export const localOrCloudProviderSchema = z.discriminatedUnion('type', [
  localProviderSchema,
  awsCloudProviderSchema,
  gcpCloudProviderSchema,
]);
```

@Siegrift if you think this is OK I'll open the PR

**Comment by Siegrift** [comment]
Yeah, that looks fine. Go ahead.

**Comment by kolenic-martin** [comment]
Hi, this is one issue that I'm about to test today morning and I'm planning to test the error handling by breaking individual options, combinations of multiple options, all options, and by omitting some or all of those as well. Just to confirm, will that be a good strategy @Siegrift?

**Comment by dcroote** [comment]
> Hi, this is one issue that I'm about to test today morning and I'm planning to test the error handling by breaking individual options, combinations of multiple options, all options, and by omitting some or all of those as well. Just to confirm, will that be a good strategy @Siegrift?

That sounds great.

**Comment by kolenic-martin** [comment]
Let me just post a short report here (sorry if I overblew it with the formatting); it lists the testcases and the messages I received.

## GCP tests
### Missing cloud provider type identifier
"message": "Invalid discriminator value. Expected 'local' | 'aws' | 'gcp'"
### Missing project name
"message": "Required"
### Missing region
"message": "Required"
### Missing stage
"message": "Required"
### Completely missing cloudProvider section
Missing object, message same as above
### Combinations of the above
Multiple messages pertaining to individual sections
### Control: no changes to config.json
Successful deployment but took over 10 minutes as usual
### Removal of the control deployment
Successful removal

## AWS tests
### Missing cloud provider type identifier
"message": "Invalid discriminator value. Expected 'local' | 'aws' | 'gcp'"
### Missing region
"message": "Required"
### Missing stage
"message": "Required"
### Completely missing cloudProvider section
Missing object, message same as above
### Combinations of the above
Multiple messages pertaining to individual sections
### Control: no changes to config.json
Successful deployment, quick and easy
### Removal of the control deployment
Successful removal

### Notes
From a naive end-user perspective, the "invalid discriminator value" is nowhere near user-friendly. I'd suggest something like:

"The deployment type is not specified or is incorrect. The possible values are..." and maybe add that "invalid discriminator value" part somewhere at the end in parentheses as this is definitely not something an end-user has any idea about.

**Comment by Siegrift** [comment]
Yeah, the "invalid discriminator value" part is useless even for technical people. I think we could do a better job formulating what went wrong.

Created https://github.com/api3dao/airnode/issues/1381
