### ISSUE TITLE
Remove `heartbeatId` from `receipt.json`

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1296]
When working on https://github.com/api3dao/api3-docs/issues/825 I've noticed that we store heartbeat ID in the `receipt.json` even though it's just a copy of the heartbeat ID from `config.json`. To add to the confusion, we send that ID with the heartbeat with the name `deployment_id`. I propose removing the `hearbeatId` field from the `receipt.json` (and with it the whole `api` section as it will become empty).

**Comment by bbenligiray** [comment]
As per yesterday's call we're planning to autogenerate the heartbeat ID similar to Lambda function names

**Comment by amarthadan** [comment]
Is there a task for that? But in that case, we would probably want to keep the heartbeat ID in the receipt, right?

**Comment by bbenligiray** [comment]
@aquarat was supposed to create a few tasks out of that call, I'm not sure if he did it yet. Not sure about the receipt question.
