### ISSUE TITLE
Improve the heartbeat implementation

### ISSUE THREAD

**Issue by aquarat** [api3dao/airnode#1299]
[More context can be found here](https://api3workspace.slack.com/archives/C027V16FGN9/p1656432856324619?thread_ts=1656427125.112069&cid=C027V16FGN9)

- The heartbeat_id should be optionally specified in config.json. If it is not specified it should be generated by the deployer: the heartbeat_id should be programmatically generated by the `airnode-deployer` on deployment using the following pseudo template example:
```
provider_name(or oisTitle[0]?)-cloud_provider-airnode_address_short-deployment_timestamp_utc
e.g.
amberdata-aws-aabbcc-220627-1149
```
- The deployment_id/heartbeat_id should be unique per deployed instance of Airnode and should be useful to people reading it (hence the inclusion of oisTitle, GCP and AWS identifiers and a timestamp).
- The heartbeat payload will be cryptographically signed, allowing the recipient of the heartbeat payload to recover the public key and verify the public key+payload contents. The Airnode's "root" key should be used to sign the payload.
- The heartbeat URLs will be included in the heartbeat payload.
- The heartbeat URLs will have a UUID postfix, the postfix will replace the requirement for an API key to access signed gateways
- It should be possible to specify a header name and value for the heartbeat POST (currently it is hard-coded as `airnode-heartbeat-api-key`), but neither should be required (optional in config.json).
- [It would be useful to include the Airnode `startCoordinator` handler duration in the heartbeat payload: `durationMs`](https://github.com/api3dao/airnode/blob/6bc6f82a321e201135bfa0ac11428cd742a82470/packages/airnode-node/src/handlers/start-coordinator.ts#L23)
- `reportHeartbeat` has access to the coordinator state, we can therefore send some statistics, specifically errors per chain, total calls per chain, e.g.
```const errors = Object.values(state.aggregatedApiCallsById).filter(call => call.errorMessage).length;```

Questions to be discussed further:
- Benchmark signature verification (to confirm signature verification as an authentication means is feasible as a DoS-handling approach in concert with Cloudflare status-code based rate limiting)
- Is it acceptable to have optional config fields for heartbeats?

**Comment by bbenligiray** [comment]
Does this issue include signatures or not?

**Comment by aquarat** [comment]
Yes it does include signatures, it's a key requirement.
This issue needs to be updated according to the recent Slack thread: https://api3workspace.slack.com/archives/C02AYRX8D89/p1657021827991959
