### ISSUE TITLE
Use "ts-node --transpileOnly" for scripts

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#1304]
Our scripts should be linted using tsconfig.json, which is executed at build time and verified on CI. ts-node does the typechkecing before every command is executed, which is both slow and unnecessary.

**Comment by amarthadan** [comment]
But we're using `ts-node` only for development purposes, don't we? Is that really a problem? I would rather know that changes in the scripts have some issues sooner than after seeing it in the CI. But I don't feel strongly about it.

**Comment by Siegrift** [comment]
The wait time strongly annoys me.

**Comment by dcroote** [comment]
Closing based on the discussion in #1475
