### ISSUE TITLE
Create an authorizer example

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1318]
We can create an example in airnode-examples for implementing a custom authorizer and demonstrate its usage, similar to the relay security scheme example

**Comment by dcroote** [comment]
For anyone coming across this issue, the `coingecko-cross-chain-authorizer` [airnode-examples integration](https://github.com/api3dao/airnode/tree/master/packages/airnode-examples/integrations/coingecko-cross-chain-authorizer), introduced in #1488 and planned to be released as part of Airnode v0.10, demonstrates how very basic same-chain and cross-chain authorizer contracts can be used together to authorize requests.

Leaving the task open as there is still an opportunity to demonstrate more complex authorizer contract logic.

**Comment by dcroote** [comment]
Closing for the same reason as #1555: `RequesterAuthorizerWithAirnode` is unused and has been superceded. See https://github.com/api3dao/airnode/issues/1722 and https://api3workspace.slack.com/archives/C02AYRX8D89/p1680698758234279

**Comment by dcroote** [comment]
Changing to "Closing as not planned"
