### ISSUE TITLE
`generate-mnemonic` is too opinionated

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1320]
The `generate-mnemonic` admin CLI command assumes the user is creating an Airnode wallet mnemonic and prints its messages accordingly. Then, we recommend the user to use this command for other things like creating a sponsor wallet, which potentially confuses users (https://discord.com/channels/758003776174030948/765618225144266793/994595049880944692).

The command should be renamed as `generate-airnode-mnemonic`. We should add another command `generate-mnemonic` that only displays the mnemonic and doesn't mention an Airnode address in the messages (instead refer to it as "Default wallet address (path:m/44'/60'/0'/0/0)")i

**Comment by kolenic-martin** [comment]
The two commands produce results as intended:
![image](https://user-images.githubusercontent.com/884979/184172626-38941d7b-21d3-4463-839b-fa7a692482ee.png)

I also tried to break it by adding an unexpected argument but this was handled gracefully so I think this is good to go.
