### ISSUE TITLE
Move cloud auth files into the `config` directory

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1329]
Currently, we encourage putting the cloud auth files (`aws.env` and `gcp.json`) into the root of the deployer app (e.g. `/app/aws.env` for the Docker image). We want to flatten the directory structure provided in our examples so we should encourage users to put all the files into one directory and mount it under the `/app/config` directory in the Docker image.

As far as I can tell, this will require only one change in the [airnode-deployer Dockerfile](https://github.com/api3dao/airnode/blob/master/packages/airnode-deployer/docker/Dockerfile#L33) and all the other changes will be only in the documentation.

**Comment by amarthadan** [comment]
This will also require changes in `airnode-examples`, my mistake.

**Comment by kolenic-martin** [comment]
Hi @dcroote, I've run the coingecko example flow and indeed, the directory structure has been flattened and the deployment works just fine. I'm attaching a screenshot of the deploy command that indicates the change:

![Image](https://user-images.githubusercontent.com/884979/179221492-dafb5df8-3cdb-4986-b986-9664e3bec079.png)

Moving this to Done.

**Comment by dcroote** [comment]
Thanks @kolenic-martin!
