### ISSUE TITLE
Building Docker images from published NPM packages

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1331]
We can use published packages (either from a local NPM registry or from the official one) to build the Docker images. This will both make the Docker builds faster and the resulting docker images smaller.

**Comment by aTeoke** [comment]
mac needed to test this issue

**Comment by kolenic-martin** [comment]
@Siegrift, afaik, you have a Mac; would you be willing to test this?

**Comment by amarthadan** [comment]
@kolenic-martin Please, test it on a Linux machine as well. This is not strictly for Mac, it just needs to be tested also on Mac.

**Comment by Siegrift** [comment]
Works on macOS (ran it again just now)

**Comment by martinkolenic** [comment]
Oh, okay, sure :) I'll be done by our call.

Dňa po 29. 8. 2022, 9:05 Michal Kimle ***@***.***> napísal(a):
