### ISSUE TITLE
Benchmark signing and verifying heartbeat payload

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1336]
From https://github.com/api3dao/airnode/issues/1299:
> To confirm signature verification as an authentication means is feasible as a DoS-handling approach in concert with Cloudflare status-code based rate limiting

We basically need to make sure that the verification process is fast enough so it can be used as a base for dropping unwanted requests.

**Comment by Siegrift** [comment]
> I found that it takes on average 14.547 milliseconds to verify a signature on my laptop across 10000 heartbeat payloads.

This feels OK. I would expect the performance to downgrade on serverless (especially with low memory limit)

I guess what is left is to test the performance of signing and verifying on servlerless.

**Comment by bbenligiray** [comment]
Serverless will only be signing, the verification will be done on the heartbeat API and there's no need to assume that it will be serverless

**Comment by Siegrift** [comment]
> the verification will be done on the heartbeat API and there's no need to assume that it will be serverless

Yeah. So we only need to benchmark the signing on serverless.

**Comment by vponline** [comment]
I did benchmarking for the signing on AWS lambda with ARM architecture, three different memory sizes (128, 256, 512 mb) and a 30s timeout (max gateway limit) generating 100, 500, 1000, 5000 signatures with the following results:

![Image](https://user-images.githubusercontent.com/65347007/186145576-9ee330b5-73a4-4c13-b6f6-b8dbc519517c.png)

I used the following code:

```ts
export const benchmarkSignatures: APIGatewayProxyHandler = async (event): Promise<APIGatewayProxyResult> => {
  const { count } = event.queryStringParameters ?? {};
  if (!count) {
    return {
      statusCode: 400,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Cross-Origin-Resource-Policy': 'cross-origin',
        'Access-Control-Allow-Methods': '*',
        'Access-Control-Allow-Credentials': true,
        'content-type': 'application/json',
      },
      body: JSON.stringify({ error: 'Count required' }),
    };
  }
  const parsedCount = parseInt(count);
  const results = [];

  const start = Date.now();
  for (let i = 0; i < parsedCount; i++) {
    const start = Date.now();
    const heartbeat = {
      deployment_id: utils.randomBytes(32),
      http_gateway_url: utils.randomBytes(32),
      http_signed_data_gateway_url: utils.randomBytes(32),
    };
    const heartbeatJson = JSON.stringify(heartbeat);
    const messageHash = ethers.utils.solidityKeccak256(['string'], [heartbeatJson]);

    const signature = await wallet.signMessage(ethers.utils.arrayify(messageHash));

    const end = Date.now();
    const result = end - start;
    results.push({ result, signature });
  }
  const end = Date.now();
  const result = end - start;
  console.log('Total result', result, result / 1000);

  const averageResult = results.reduce((acc, result) => acc + result.result, 0) / results.length;

  console.log('Average result', averageResult, averageResult / 1000);

  return {
    statusCode: 200,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Cross-Origin-Resource-Policy': 'cross-origin',
      'Access-Control-Allow-Methods': '*',
      'Access-Control-Allow-Credentials': true,
      'content-type': 'application/json',
    },
    body: JSON.stringify({ averageResult, averageSeconds: averageResult / 1000, result, resultSeconds: result / 1000 }),
  };
};
```

**Comment by bbenligiray** [comment]
Seems adequately insignificant to me

**Comment by amarthadan** [comment]
Hmm, I've just realized that the test is measuring the signing and we need to know whether the message verification will be quick enough. Message verification will be used to determine whether the request is valid and whether we should process it or ignore it.

Can you modify the code and try that? I don't think you need to test for all the setups, feel free to test only with 128MB Lambda to see what's the worst-case scenario.

**Comment by vponline** [comment]
> Hmm, I've just realized that the test is measuring the signing and we need to know whether the message verification will be quick enough. Message verification will be used to determine whether the request is valid and whether we should process it or ignore it.
Can you modify the code and try that? I don't think you need to test for all the setups, feel free to test only with 128MB Lambda to see what's the worst-case scenario.

Oh, I was under the impression that only the signing should be benchmarked based on the above comments (since verification will not necessarily be on serverless), but I can also try the verification 👍

**Comment by amarthadan** [comment]
Oh, I've missed those. You're right. In that case that's fine, no need to test that :slightly_smiling_face:
