### ISSUE TITLE
Heartbeat payload signing

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1337]
Based on research done in https://github.com/api3dao/airnode/issues/1336

From https://github.com/api3dao/airnode/issues/1299:
> The heartbeat payload will be cryptographically signed, allowing the recipient of the heartbeat payload to recover the public key and verify the public key+payload contents. The Airnode's "root" key should be used to sign the payload.

One thing to make sure is that the message that is being signed here can’t be manipulated to match a transaction hash or a Beacon update. So make sure to [sign a message](https://docs.ethers.io/v5/api/signer/#Signer-signMessage) that includes some salt (e.g. `"Airnode heartbeat authentication”`) so that it can’t be used for anything else.

**Comment by martinkolenic** [comment]
I've successfully tested this and documented the results in [#1411](https://github.com/api3dao/airnode/issues/1411). Moving this to Done.
