### ISSUE TITLE
Making heartbeat API key optional and with configurable header name

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1338]
Since the heartbeat payload will be singed (https://github.com/api3dao/airnode/issues/1337) we don't necessarily need an API key for some flow but we want to keep it available.

So, the heartbeat API key will be optional. In addition to this, we want to allow to configure the header name in which the API key will be sent (currently it's hardcoded to `airnode-heartbeat-api-key`).

**Comment by bbenligiray** [comment]
@aquarat The reasoning for making this optional is for backwards compatibility for ChainAPI. We want the signatures for the data feed deployment flow. Don't these two assume we won't use ChainAPI in data feed deployments?

**Comment by amarthadan** [comment]
@aquarat @andreogle Is this actually needed? Based on [this discussion](https://api3workspace.slack.com/archives/C037NLX1R8T/p1660138497583909?thread_ts=1658505015.182699&cid=C037NLX1R8T) it looks like it's not. Can you confirm it?

**Comment by bbenligiray** [comment]
This is mostly an Andre question, I can't recall what was the decision on heartbeat authentication and ChainAPI

**Comment by andreogle** [comment]
On the ChainAPI side, we will likely keep supporting the API key in the header (at least for a while), as there are existing heartbeats that would break if we removed that authentication. However, going forward I think it would be fine to remove the API key or make it optional. We want ChainAPI to move to the signature approach

**Comment by bbenligiray** [comment]
So Airnode can do a hard switch between versions and ChainAPI can start supporting the new Airnode version after the signature verification is implemented at the ChainAPI end. So we're not necessarily keeping the heartbeat key available for ChainAPI and I can't tell who we'd be doing this for.

**Comment by Siegrift** [comment]
That means we can close this issue as non-actionable right?

**Comment by aTeoke** [comment]
@bbenligiray should we close this task?

**Comment by kolenic-martin** [comment]
Hi @Siegrift, as I understand, this is not testable. Can this be moved to Done?

**Comment by amarthadan** [comment]
This was closed as we won't implement it. Should have been already moved to Done.
