### ISSUE TITLE
Use GCP API keys in the GCP recipes

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1340]
GCP [recently added](https://stackoverflow.com/a/71556294) support for API key management via their API and it's already available in [Terraform](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/api_gateway_api_config). We can (hopefully) use this and get rid of the custom API key checking we currently have in the GCP handler.

**Comment by vponline** [comment]
The terraform docs say;
```
Warning:
This resource is in beta, and should be used with the terraform-provider-google-beta provider. See [Provider Versions](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_versions) for more details on beta resources.
```

Is this ok to change?

**Comment by Siegrift** [comment]
I think non beta GCP didn't support some core feature we needed. I remember @amarthadan mentioning this when he worked on GCP integration (can't remember what exactly it was though).

**Comment by Siegrift** [comment]
To be discussed in https://api3workspace.slack.com/archives/C02AYRX8D89/p1659538932266949

**Comment by amarthadan** [comment]
Closing based on the [Slack discussion](https://api3workspace.slack.com/archives/C02AYRX8D89/p1659538932266949).
