### ISSUE TITLE
Add gas oracle strategies by default to airnode-examples

### ISSUE THREAD

**Issue by vponline** [api3dao/airnode#1342]
Add `latestBlockPercentileGasPriceStrategy` and `providerRecommendedGasPrice` to airnode-examples configs and config creation scripts.

**Comment by kolenic-martin** [comment]
Hi @vponline, this was my testing strategy:

- I deployed Airnode with the coingecko example flow and performed a request (successful)
- I checked config.json for the presence of the gas oracle entries (present)

This is thus working just fine :)
