### ISSUE TITLE
Update hardhat to ^2.10.0

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#1346]
Hardhat version 2.10 consists of [considerable changes](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.10.0) and got slower so our e2e tests started failing (because it takes a long time until the node initializes).

We've excluded update of this dependency in https://github.com/api3dao/airnode/pull/1325 but we should look at this again at some point.

**Comment by andreogle** [comment]
RIP semver 😭

I wonder how feasible it would be to try [Foundry](https://github.com/foundry-rs/foundry) instead of Hardhat. Foundry obviously isn't written in JS so integrating it with a JS/TS repo like Airnode may or may not be tricky, but it's _extremely_ fast (instant in most cases)

**Comment by dcroote** [comment]
> I wonder how feasible it would be to try [Foundry](https://github.com/foundry-rs/foundry) instead of Hardhat. Foundry obviously isn't written in JS so integrating it with a JS/TS repo like Airnode may or may not be tricky, but it's _extremely_ fast (instant in most cases)

New title: Update hardhat to Rust 😂

**Comment by dcroote** [comment]
The issue is the number of accounts we were initializing (1000!) - I reduced it to 100 in https://github.com/api3dao/airnode/pull/1647 and tests pass.
