### ISSUE TITLE
Add more extensive logging for gateway requests

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#1351]
Currently, HTTP gateways (testing and signed) x (gcp, aws,local) do not log the incoming request before the arguments are validated. This means, we can end up with a rejected request but have no log entry about it (and what went wrong).

**Comment by dcroote** [comment]
A [user on discord](https://discord.com/channels/758003776174030948/765618225144266793/1028888218822770688) could have been helped with more detailed logging:
> But it just return api call failed
I cannot figure out what is going wrong with this api call
Is there anyway to get more detail about failed calling?

**Comment by martinkolenic** [comment]
Hi, I've tested this and reviewed it on the CloudWatch console.

Steps: Deploy Airnode on AWS, perform a HTTP request and check for log data on the CloudWatch console
Expected result: Request metadata logged in the console
Actual result: Matches expected result.

Screenshot:
![Image](https://user-images.githubusercontent.com/884979/203580752-664f77cc-2d8d-42c3-a10f-0dc3f8d31ff0.png)

**Comment by dcroote** [comment]
Thanks @martinkolenic, but the logging changes were mostly added under the log level of `DEBUG`, so to see the updates you would need to deploy with `logLevel` set to `DEBUG` within `config.json` before making a gateway request.

**Comment by Siegrift** [comment]
That's a good point. I think we the Airnode examples should use the DEBUG logger in config.json by default... WDYT?

**Comment by martinkolenic** [comment]
Hi @dcroote, thanks for the information. I'll redeploy with that flag set to `DEBUG` and report back with results. @Siegrift, that might actually be a good idea in terms of investigating potential mishaps.

**Comment by martinkolenic** [comment]
Hi @dcroote, I've rerun the test now.

Steps: In the coingecko-signed-data integration config.json, set the `logLevel` property to `DEBUG` and redeploy Airnode (if not deployed, deploy from scratch). Then, perform another POST request using `curl`. 

Expected result: Meaningful request response and a more extensive set of log entries compared to the `INFO` level that was set by default in the previous deployment (if any).
Actual result: Matches expected result

Screenshots:

AWS CloudWatch console:
![Image](https://user-images.githubusercontent.com/884979/203747371-251f54a4-72f3-4b75-a7a4-015cd0ce7a4a.png)

Airnode/`curl` output:
![Image](https://user-images.githubusercontent.com/884979/203747519-71d302bc-40f9-4497-8b9d-228e921af323.png)

**Comment by dcroote** [comment]
@martinkolenic - great, your screenshot includes the expected extra logging entries.

@Siegrift - having `DEBUG` as the log level for `airnode-examples` (and also probably tutorials in the docs) sounds beneficial to both the user and also to us if there are user issues

**Comment by Siegrift** [comment]
I guess feel free to create an issue, or just straight up implement. It should be a trivial config change.
