### ISSUE TITLE
Deployer doesn't validate config.json

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#136]
The deployer should validate the `config.json` and `security.json` provided by the user using the validator package.

Tracked by: https://api3dao.atlassian.net/browse/AN-159

**Comment by bbenligiray** [comment]
Waiting on https://github.com/api3dao/airnode/issues/99 and the merging of the related PR

**Comment by bbenligiray** [comment]
Blocked by https://github.com/api3dao/airnode/issues/207 being closed, the [validator branch](https://github.com/api3dao/airnode/tree/validator) being updated accordingly and merged.

**Comment by MrAngus666** [comment]
#207 was merged. Removing blocked label

**Comment by bbenligiray** [comment]
Resolved in v0.2.0
