### ISSUE TITLE
Deployer doesn't test the chain providers

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1363]
As an idea for a new feature, the deployer can get the chain ID from each provider and confirm that it matches the chain ID it was used under

**Comment by dcroote** [comment]
The `ping-providers.ts` script from the api3dao/chains repo has a related example of confirming `chainId`:

https://github.com/api3dao/chains/blob/338b1b700af404a2620c5451bf0c50839f09f742/scripts/ping-providers.ts#L1-L12C4

**Comment by bbenligiray** [comment]
Good point. As in @api3/chains we should validate that the provider is synced

**Comment by Siegrift** [comment]
We've agreed on the call not to do this. (cc: @dcroote )
