### ISSUE TITLE
Rename `stage` field in the configuration to `deploymentId`

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1375]
We're using the `stage` field to distinguish between deployments anyway so we should make it official. The change is pretty much just the rename of the field but we should mention in the documentation that it is used to distinguish between the deployments and should be unique for each Airnode/deployment.

[Slack discussion](https://api3workspace.slack.com/archives/C037NLX1R8T/p1658505015182699)

**Comment by bbenligiray** [comment]
This should be blocked by the cloud resource naming rework (because the assumption for this issue was that `stage` needs to be temporally unique, which may not be the case)

**Comment by kolenic-martin** [comment]
Hi, the new configs now show the change and the validator complains if you rename it back. Working well.
