### ISSUE TITLE
Fix behavior of some GCP regions

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1380]
Based on @vponline's [report](https://api3workspace.slack.com/archives/C02AYRX8D89/p1660299786586649?thread_ts=1660225845.222229&cid=C02AYRX8D89) it looks like that [two GCP App Engine locations differ from what is used for other resources](https://cloud.google.com/appengine/docs/locations).
Namely `europe-west1` and `us-central1` are recognized only under `europe-west` and `us-central` in the App engine. We should add this "translation" to the deployer/Terraform recipes.

**Comment by amarthadan** [comment]
@kolenic-martin Please, test that when you choose either `europe-west1` or `us-central1` as a GCP region both deployments will work. Remember that you can't change the region once you use it, you will have to create a different project and try it there.

**Comment by kolenic-martin** [comment]
Hi @amarthadan, I can now confirm that the deployment to us-central1 and europe-west1 regions have been succesful, the request fulfilled and a POST request to the signed data gateway returned a regular response (screenshot included for the us-central1 region for demonstration).

![Image](https://user-images.githubusercontent.com/884979/185596652-a20290f6-5e25-46d9-9c55-52479bc16da3.png)
