### ISSUE TITLE
Research which GCP regions should be considered as supported

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1385]
Some of the GCP regions (and this can potentially apply to AWS as well) don't support all the resources we deploy during the Airnode deployment (e.g. us-west1  doesn't support the API Gateway). We need to go through all the regions (that have support for the resources we use) and make sure that we can deploy Airnode there.

**Comment by wkande** [comment]
In the process could we make sure that the resources listed on **[this docs page](https://docs.api3.org/airnode/v0.7/reference/cloud-resources.html)** are up-to-date?

**Comment by kolenic-martin** [comment]
Hi @amarthadan and @wkande, the following regions support all features we need and can be sccessfully deployed to:

Americas
us-west1, us-west2, us-west4, us-central1 [previously had issues, seems to be working after the latest changes], us-east1, us-east4

Europe
europe-west2, europe-west1 [similar to us-central1]

Asia-Pacific
asia-northeast1, australia-southeast1

**Comment by dcroote** [comment]
@martinkolenic - are you sure `us-west1` worked? According to @amarthadan's initial comment and the [GCP docs](https://cloud.google.com/api-gateway/docs/deployment-model#choosing_a_gcp_region), `us-west1` isn't supported for the API Gateway.

**Comment by martinkolenic** [comment]
You're correct, Derek, that was a mistake on my part. That one does not
work, I actually found out by testing.

Dňa št 8. 9. 2022, 7:32 Derek Croote ***@***.***> napísal(a):

**Comment by martinkolenic** [comment]
Update: I know how this actually happened - I listed this one incorrectly in some of my own older notes as a candidate for testing based on what Google says about the supported features and did not re-check the final list. The rest of the locations are definitely working as I cherry picked them from the 34 regions, filtering out those which did not have supported features. Other than this mistake, for which I'm really sorry, all regions are deployable.
