### ISSUE TITLE
Broken v0.7.3 npx packages

### ISSUE THREAD

**Issue by dcroote** [api3dao/airnode#1389]
Originally [reported on Discord](https://discord.com/channels/758003776174030948/765618225144266793/1011033336027828315), `v0.7.3` of `airnode-validator`, `airnode-admin`, and `airnode-deployer` are broken due to a missing `airnode-validator` file (see error below).

This is reminiscent of #1246 and #1247, however the `v0.7.3` release includes [the fix](https://github.com/api3dao/airnode/blob/v0.7.3/packages/airnode-validator/package.json#L10) from #1268, which corrected the validator binary path. Given the missing file **is** the correct validator binary path (which we know works in `v0.7.2`) this might have resulted from not running `yarn build` prior to release? Further evidence for this is from socket.dev, which shows [the file missing from the package](https://socket.dev/npm/package/@api3/airnode-validator/files/0.7.3/dist/cjs) for `v0.7.3`, [but present for](https://socket.dev/npm/package/@api3/airnode-validator/files/0.7.2/dist/cjs) `v0.7.2`.

Error:
```sh
> npx @api3/airnode-validator@0.7.3
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/derek/.npm/_npx/23478/lib/node_modules/@api3/airnode-validator/dist/cjs/bin/validator.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/derek/.npm/_npx/23478/lib/node_modules/@api3/airnode-validator/dist/cjs/bin/validator.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/derek/.npm/_logs/2022-08-22T01_37_58_062Z-debug.log
Install for [ '@api3/airnode-validator@0.7.3' ] failed with code 254
```

**Comment by kolenic-martin** [comment]
When I was testing this on Friday, I pulled the release from the repo, which might explain why it did work for me (and for some reason I did not use the docker image provided in the cloud). Retesting with the Docker image from the cloud does reproduce the same error.

**Comment by bbenligiray** [comment]
Fixed by https://github.com/api3dao/airnode/releases/tag/v0.7.5
