### ISSUE TITLE
Rework deployments to use a common bucket

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1402]
In order to avoid bucket name conflicts, we want to keep files necessary for the deployments under one common bucket (per AWS account/GCP account + project).

During the first deployment, we will create a bucket with the name `airnode-{unique ID}`. Under this bucket, we will create a "directory path" with a format `/{full Airnode address}/{stage}/{timestamp}`. This directory will be used to store all the necessary files for the deployment - `config.json`, `secrets.env` and Terraform state files.

If the user decides to deploy another Airnode instance with either a different Airnode address or a different stage, the corresponding path will be created for that deployment under the common bucket.

If the user decides to update their current deployment (e.g. changing the OIS part of the config) a new `{timestamp}` directory will be created under the same `/{full Airnode address}/{stage}/` path and the updated files will be stored there.

Deploying an Airnode that has the same Airnode address and stage name but a different region or Airnode version won't be possible. If the users want to change the region, they would first have to remove the old deployment and then make a new one. The same goes for changing the Airnode version. Airnode deployment will be possible to remove only with the airnode-deployer of the same version as it was deployed with.

When the deployment is removed and there are still other deployments with the same Airnode address, we remove just the specific stage directory (and its subdirectories). The same goes for multiple deployments with a different Airnode address. When removing the last deployment we also remove the common `airnode-{unique ID}` bucket.

To summarize:

Deployment steps:
1. Look for the common bucket - the name must be in a `airnode-AABBCCDDEEFF` format. If there is one, reuse it. If there is none, create one. If there is more than one, fail with an error.
2. Look for the corresponding `/{full Airnode address}/{stage}/` path. If there is none, create one.
3. If there already is a deployment with the same Airnode address and stage, check that the region and Airnode version match. Fail with an error if they don't.
4. Deploy the Airnode / update the old deployment.
5. Create a new `{timestamp}` directory and store `config.json`, `secrets.env` & Terraform state files.

Deployment removal steps:
1. Look for the common bucket - the name must be in a `airnode-AABBCCDDEEFF` format. If there is none or there is more than one, fail with an error.
2. Look for the `/{full Airnode address}/{stage}/` path. If there is no such path, fail with an error - there's no such deployment.
3. Check that the Airnode version match. Fail with an error if they don't.
4. Select the latest deployment (newest timestamp) and remove the Airnode deployment.
5. Remove the `{stage}` directory and its files.
6. If there's no other `{stage}` directory remove the {full Airnode address} directory
7. If there's no other {full Airnode address} directory remove the common bucket

**Comment by bbenligiray** [comment]
> When removing the last deployment we also remove the common airnode-{unique ID} bucket.

I don't really see a point in doing so. We can have a cute "We detected that this is the first time you're deploying an Airnode on this cloud provider account" message if we keep the bucket.

> Deployment removal step 3: Check that the region and Airnode version match

We don't need the region as an argument, we can fetch it from the config

> Deployment removal step 6: If there's no other {stage} directory remove the {full Airnode address} directory

Again, not deleting this would allow us to know if it is the first time this Airnode is being deployed on this account. I think this would be really helpful against accidentally using the wrong cloud provider credentials.

**Comment by amarthadan** [comment]
> I don't really see a point in doing so. We can have a cute "We detected that this is the first time you're deploying an Airnode on this cloud provider account" message if we keep the bucket.

I would personally prefer if the tool I'm using cleans up after itself. Especially when I delete everything :man_shrugging: No other reason really.

> We don't need the region as an argument, we can fetch it from the config

Right, my mistake.

> Again, not deleting this would allow us to know if it is the first time this Airnode is being deployed on this account. I think this would be really helpful against accidentally using the wrong cloud provider credentials (I don't care as much about leaving an empty stage directory, though may be a good idea for consistency).

I'm ok with leaving empty subdirectories but I would prefer removing the whole bucket once everything is gone. But I don't feel that strongly about it.

**Comment by bbenligiray** [comment]
I guess I'm fine with deleting the directories

**Comment by Siegrift** [comment]
> If there is none, create one. If there is more than one, fail with an error.

How can there be >1 ?

> Deploying an Airnode that has the same Airnode address and stage name but a different region or Airnode version won't be possible.

Why?

> Select the latest deployment (newest timestamp) and remove the Airnode deployment.

Shouldn't you be able to choose from the list of timestamp to remove the Airnode specified by that? It feels you most often want to remove the older timestamped one (but I can also imagine removing the newer one in case there was a mistake).

**Comment by amarthadan** [comment]
> > Select the latest deployment (newest timestamp) and remove the Airnode deployment.
> 
> Shouldn't you be able to choose from the list of timestamp to remove the Airnode specified by that? It feels you most often want to remove the older timestamped one (but I can also imagine removing the newer one in case there was a mistake).

But there is only one active Airnode, the rest is just historical data (a preparation for https://github.com/api3dao/airnode/issues/1406).
