### ISSUE TITLE
Allow listing of active Airnode deployments

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1403]
Allow users to list the active Airnode deployment via airnode-deployer CLI in a similar fashion as `docker ps` command.

```bash
airnode-deployer list

Deployment ID   Cloud provider   Airnode address   Stage       Region        Node version   Last Update
1697238d        AWS              0x1234567...      dev         us-east-1     0.7.3          2022-08-29T09:12:34+0000
ada40890        AWS              0x1234567...      prod        us-east-1     0.6.5          2022-09-29T07:34:33+0000
1c4dbc3d        GCP              0xabcdef0...      mainnet-2   eu-central1   0.6.5          2022-08-12T10:17:09+0000
```
The output will be ordered by the cloud provider, Airnode address, region, stage, and Airnode version in this order. There's an argument to be made about ordering the list by the last update time but I would prefer if the output didn't move around every time I redeploy an Airnode. we can add options for multiple orderings later on.

The deployment ID will be constructed as the first 8 characters of `sha([cloudProvider, region, airnodeAddress, stage, airnodeVersion])`. The last update time is not included so the update to the given Airnode won't change it's deployment ID.

There will be a `--cloud-providers` option allowing the listing of Airnodes only from the given cloud provider(s). With no option provided, the deployer will try to list all (both) the cloud providers.

**Comment by bbenligiray** [comment]
Deployer would need to be able to use multiple cloud provider credentials to be able to have the cloud provider column. That would be cool though (and useful especially for multi-region/project GCP deployments).

**Comment by amarthadan** [comment]
Credentials for different cloud providers come from different sources so that shouldn't be a problem (even now).

**Comment by amarthadan** [comment]
@aquarat @bbenligiray I've updated the description, let me know whether it makes sense this way.

**Comment by bbenligiray** [comment]
Looks good. How about this though?

```bash
airnode-deployer list

Deployment ID   Cloud provider   Airnode address   Stage       Node version   Last Update
1697238d        AWS (us-east-1)     0x1234567...      dev         0.7.3          2022-08-29T09:12:34+0000
ada40890        AWS (us-east-1)     0x1234567...      prod        0.6.5          2022-09-29T07:34:33+0000
1c4dbc3d        GCP (eu-central1)   0xabcdef0...      mainnet-2   0.6.5          2022-08-12T10:17:09+0000
```

**Comment by amarthadan** [comment]
Also a viable option, I'm ok with that.
This is how it looks at the moment (still WIP)
![Screenshot_20220920_155819](https://user-images.githubusercontent.com/1655405/191278242-60c3be5a-757e-45d3-b0cc-602ed83e80f6.png)

**Comment by bbenligiray** [comment]
I normally view `docker ps` like this so I think it should be as short as possible
![Screenshot from 2022-09-20 17-31-55](https://user-images.githubusercontent.com/19530665/191286487-b0064b71-9ea2-4ac0-8e26-8b64251c010d.png)

**Comment by amarthadan** [comment]
The longest part will be the Airnode address, not sure we can do much about it. The time is just not formatted yet.

**Comment by andreogle** [comment]
If we want to go with shortened addresses, I think it's more common to include the last few characters as well. e.g. Something like `0x1234...6789`

**Comment by amarthadan** [comment]
I wanted to keep the full address because that's what they need to provide if they want to remove the Airnode without the receipt (with `remove-without-receipt`) and also because it's part of the path in the bucket. But I can shorten it and provide the full address only with the future [`info`](https://github.com/api3dao/airnode/issues/1404) command.

**Comment by amarthadan** [comment]
What about this for a final form?
![Screenshot_20220921_090257](https://user-images.githubusercontent.com/1655405/191436771-ca0d7f79-63b2-4a90-9be5-eb1850757ab1.png)

**Comment by aquarat** [comment]
This is looking very good/polished.

**Comment by bbenligiray** [comment]
Agreed. Feels like "Airnode version" could be "Version" but I don't feel too strongly.

**Comment by andreogle** [comment]
I personally don't think we should be showing the "Airnode" ascii art for this. Feels like a big waste of space (although I do like it when deploying)

**Comment by amarthadan** [comment]
> I personally don't think we should be showing the "Airnode" ascii art for this. Feels like a big waste of space (although I do like it when deploying)

Yeah, I was thinking the same thing. I'll keep the ASCII art only for the deploying and removal then.

**Comment by martinkolenic** [comment]
This is working very smoothly and is a great thing user experience-wise. It detects even an old deployment without any error.

**Comment by amarthadan** [comment]
> It detects even an old deployment without any error.

What do you mean by an old deployment?

**Comment by amarthadan** [comment]
No idea why this wasn't closed automatically when the PR was merged. Closing.

**Comment by martinkolenic** [comment]
Hi @amarthadan, an old deployment = an older version of Airnode than the v0.10 branch (0.8 in this case). These were the testcases:

- 3 AWS deployments (different stages and regions) + 1 GCP deployment
    - successfully tested displaying only the AWS part and the GCP part as well   
- Only the AWS deployments (after GCP deployment removal; 2x v0.8 and 1x vNext)
- Only 2 GCP projects (after removing AWS deployments and deploying 2 GCP projects with different stages and regions; v0.8 and vNext)
