### ISSUE TITLE
Allow users to retrieve info about their deployments

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1404]
Allow users to see info and history of changes for a specific deployment.
```bash
airnode-deployer info 40207f25

Cloud provider: AWS (us-east-1)
Airnode address: 0xd0624E6C2C8A1DaEdE9Fa7E9C409167ed5F256c6
Stage: dev
Airnode version 0.9.0
┌────────────┬───────────────────────────┐
│ Version ID │ Deployment time           │
├────────────┼───────────────────────────┤
│ 5bbcd317   │ 2022-08-29 09:12:34 GMT+2 │
├────────────┼───────────────────────────┤
│ 21f1b492   │ 2022-09-29 07:34:33 GMT+2 │
├────────────┼───────────────────────────┤
│ 2c8b8bbe   │ 2022-08-12 10:17:09 GMT+2 │
└────────────┴───────────────────────────┘
```
Based on the deployment ID from the `list` command (https://github.com/api3dao/airnode/issues/1403).
The version ID will be constructed as the first 8 characters of sha([cloudProvider, region, airnodeAddress, stage, airnodeVersion, deploymentTime]) so it's unique for the deployment and its historical version.

Basically a preparation for https://github.com/api3dao/airnode/issues/1406

**Comment by amarthadan** [comment]
@bbenligiray @aquarat I've updated the description, let me know if you're ok with this.

**Comment by Siegrift** [comment]
Maybe:
```
Cloud provider: AWS (us-east-1)
Airnode address: 0xd0624E6C2C8A1DaEdE9Fa7E9C409167ed5F256c6
Stage: dev
Airnode version 0.9.0
┌────────────┬───────────────────────────┐
│ Version ID │ Deployment time           │
├────────────┼───────────────────────────┤
│ 5bbcd317   │ 2022-08-29 09:12:34 GMT+2 │ (current)
├────────────┼───────────────────────────┤
│ 21f1b492   │ 2022-09-29 07:34:33 GMT+2 │
├────────────┼───────────────────────────┤
│ 2c8b8bbe   │ 2022-08-12 10:17:09 GMT+2 │
└────────────┴───────────────────────────┘
```

**Comment by Siegrift** [comment]
This info command will only show Airnodes deployed with the current Airnode version. Correct me if I am wrong, but this means that the user will first have to remove all of these (which will remove the files in AWS) and then redeploy with a new deployer version.

**Comment by amarthadan** [comment]
The `(current)` is a nice touch. But the table is generated by a library :sweat_smile: I'll figure something out :smile:

> This info command will only show Airnodes deployed with the current Airnode version. Correct me if I am wrong, but this means that the user will first have to remove all of these (which will remove the files in AWS) and then redeploy with a new deployer version.

I think there's some confusion. This is info about one deployment. The dates are the dates of previous "versions" of the same deployment (e.g. updated `config.json`). It's basically just preparation for https://github.com/api3dao/airnode/issues/1406.
But yes, if you would want to upgrade the Airnode version you would have to remove this one deployment and deploy the new version. But that's just one `remove-with-receipt`/`remove-with-deployment-details` command.

**Comment by bbenligiray** [comment]
I like it. "(current)" or something to that effect would be good.

**Comment by martinkolenic** [comment]
I tested this for both AWS and GCP. I tested with no redeployment, one, and two. The (current) indicator always pointed at the correct one.
