### ISSUE TITLE
Allow users to fetch deployment files from the cloud provider

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1405]
```bash
airnode-deployer fetch-files awsd1f89c33 # Stores a file awsd1f89c33-1662558010204.zip with the latest config.json and secrets.env to ./config directory
airnode-deployer fetch-files awsd1f89c33 --version 586f79c8 # Stores a file awsd1f89c33-1662557983568.zip (specific version) to ./config
airnode-deployer fetch-files awsd1f89c33 --output-dir /some/path/somewhere  # Stores a file awsd1f89c33-1662558010204.zip to /some/path/somewhere directory
airnode-deployer fetch-files awsd1f89c33 --output-dir /some/path/somewhere --version 586f79c8 # Combination of options
```
This command will download file(s) of the specified deployment based on the deployment ID from the `list` command (https://github.com/api3dao/airnode/issues/1403).
Users will be able to download both `config.json` and `secrets.env` in a zip archive.
They can provide a `--version` option to specify the deployment version from which the file(s) should be downloaded based on the version ID from the `info` command (https://github.com/api3dao/airnode/issues/1404). Without the option, the latest deployment version will be used.
They can also use the option `--output-dir` to specify where the files should be stored. Without the option, `./config` directory is used.

**Comment by amarthadan** [comment]
Should be refined based on the [Slack discussion](https://api3workspace.slack.com/archives/C02AYRX8D89/p1663586385441409?thread_ts=1663228424.184189&cid=C02AYRX8D89).

**Comment by amarthadan** [comment]
@bbenligiray @aquarat I've updated the description, let me know whether it makes sense this way.

**Comment by bbenligiray** [comment]
- `--files` weirded me out a bit, the interface didn't feel elegant. I guess the reasoning is that you may want to not expose sensitive files, but I'm not sure if that's an actual requirement. I would wait for the users to ask for this.
- Could have "fetch all versions" and "fetch everything" commands. I see myself using "fetch everything" for convenience. This can also be a wishlist item.
- Is `--output-dir` an absolute path? I'd suggest [`--directory-prefix`](https://www.gnu.org/software/wget/manual/html_node/Directory-Options.html) instead.

**Comment by amarthadan** [comment]
> --files weirded me out a bit, the interface didn't feel elegant. I guess the reasoning is that you may want to not expose sensitive files, but I'm not sure if that's an actual requirement. I would wait for the users to ask for this.

I thought that the main requirement is to be able to download the secrets ([Slack discussion](https://api3workspace.slack.com/archives/C02AYRX8D89/p1663586385441409?thread_ts=1663228424.184189&cid=C02AYRX8D89)).

I wanted to provide an option to download just the config file or just the secrets file but I guess that's not really needed. We can download always just the zip file.

> Could have "fetch all versions" and "fetch everything" commands. I see myself using "fetch everything" for convenience. This can also be a wishlist item.

What would be included in everything? All the versions and all the files? But I feel like that can be added later.

> Is --output-dir an absolute path? I'd suggest [--directory-prefix](https://www.gnu.org/software/wget/manual/html_node/Directory-Options.html) instead.

I agree with @Siegrift , I'd say `--output-dir` is more common.
Yeah, it can support both absolute and relative paths.

**Comment by amarthadan** [comment]
> I was thinking of this as rollback in deconstructed form (so you download the files of an older version and redeploy, which gives you rollback), though I remember that the main reasoning was to download your previous secrets file and copy paste stuff from there/reuse it. I'm not sure if missing the only secrets download will degrade UX but config gives context to secrets so downloading them together makes more sense to me.

Yeah, you're right. So, there will be no `--files` option it it will always download a zip with both config and secrets. I'll update the description.
