### ISSUE TITLE
Research potential substitutes for confluence

### ISSUE THREAD

**Issue by aTeoke** [api3dao/airnode#1410]

**Comment by kolenic-martin** [comment]
| Feature              | [Nuclino](https://nuclino.com) | [Quip](https://quip.com/) | [Notion](https://notion.so) | [Slab](https://slab.com/) | [Gitbook](https://gitbook.com) | [Basecamp](https://basecamp.com) |
| -------------------- | :----------------------------: | :-----------------------: | :-------------------------: | :-----------------------: |:-----------------------------: |:-----------------------------: |
| Separate documents   |               ✔️                |           ✔️              |             ✔️               |           ✔️              |              ✔️                 |              ✔️                 |
| Markdown             |               ✔️                |           ✔️              |             ✔️               |           ✔️              |              ✔️                 |              ✔️                 |
| Inline comments      |               ✔️                |           ✔️              |             ✔️               |           ✔️              |              ✔️                 |              ✔️                 |
| Discussion           |               ✔️                |           ✔️              |             ✔️               |           ✔️              |              ✔️                 |              ✔️                 |
| Notify on reactions  |               ✔️                |           ✔️              |             ✔️               |           ✔️              |              ✔️                 |              ✔️                 |
| Search               |               ✔️                |           ✔️              |             ✔️               |           ✔️              |              ✔️                 |              ✔️                 |
| No need to selfhost  |               ✔️                |           ✔️              |             ✔️               |           ✔️              |              ✔️                 |              ✔️                 |
| Price (user & month) | €5 (as €60 per year)           | $10 (as $120 per year)    | $8 (as $96 per year)        | $6.67 (as ~$80 per year) | Free* or $6.40 (billed monthly) | $99/month flat (unlim. users) |

*there seems to be an option for open-source projects, all spaces are public though; private spaces for paid users

**Comment by kolenic-martin** [comment]
Personally, it seems to me that Gitbook or Nuclino could be a good match for us, both price- and feature-wise.

**Comment by amarthadan** [comment]
I've posted my findings in https://api3workspace.slack.com/archives/C01N6001YCE/p1662545864558579
