### ISSUE TITLE
Remove "animated" spinner from airnode-deployer

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1425]
We're currently using [ora](https://github.com/sindresorhus/ora) library to provide a somewhat animated spinner in the terminal output while the Airnode is being deployed.

I don't think this is worth it though. Ora's usage is a bit complicated and it results in a more complex code. It also sometimes cleans the terminal's history which is quite irritating.

I would suggest removing the library and using just ellipses to communicate an action in progress. Something like:
```bash
Deploying Airnode...
Airnode successfully deployed # once done
```

**Comment by amarthadan** [comment]
> I personally like the feature very much (not talking about the code complexity at all though). But it makes me feel OK when deployments take too long, since I see the spinner which tells me that something is happening.

I see your point. I personally don't care much whether I see ... or a spinner so I might be biased.
@bbenligiray @aquarat thoughts?

**Comment by andreogle** [comment]
I quite like the spinner as well. Makes the tool seem more polished imo

**Comment by aquarat** [comment]
Much like above I think the spinner is nice for end users but I also agree @ code complexity and terminal clear.
I'd settle for something like an animated ellipsis which could be done using the `\r` character alone.
Maybe there's a lighter library that does that? 🤷 
I quite like seeing the debug output of the underlying tools, but that scares most people.

**Comment by amarthadan** [comment]
You all think that it's a nice enough feature so I'm ok with keeping it. I'm going to close this issue then and open a new [one for researching an alternative/fixing the weird behavior](https://github.com/api3dao/airnode/issues/1436).

**Comment by bbenligiray** [comment]
(as a note, I agree that the fancy spinner is a big difference)
