### ISSUE TITLE
Research which AWS regions should be considered as supported

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1429]
Pretty much the same thing as https://github.com/api3dao/airnode/issues/1385 but for AWS

**Comment by martinkolenic** [comment]
Successful deployments:
Americas:
us-east-1, us-east-2, us-west-1, us-west-2, ca-central-1, sa-east-1

APAC:
ap-south-1, ap-northeast-1, ap-northeast-2, ap-northeast-3
ap-southeast-1, ap-southeast-2

EMEA:
eu-central-1, eu-west-1, eu-west-2, eu-west-3, eu-north-1

Unsuccessful deployments:
ap-east-1, ap-southeast-3, cn-north, cn-northwest-1, eu-south-1, af-south-1, me-south-1 (aws - s3 - qreports invalid location constraint)
ap-northeast-3 (aws reports invalid security token, 403 error)

**Comment by dcroote** [comment]
Nice @martinkolenic! I think it would be great if you could incorporate this info into the docs like in https://github.com/api3dao/api3-docs/pull/1012

**Comment by amarthadan** [comment]
I've opened a separate issue for the [`ap-northeast-3` error](https://github.com/api3dao/airnode/issues/1503). Closing this one.
