### ISSUE TITLE
Check if the user has noted down the mnemonic during deployment

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#143]
Currently, we ask the user to note down the randomly generated mnemonic during the first deployment
https://github.com/api3dao/airnode/blob/421822c2799dda9d6e9a8e6dab79b939f7a1984b/packages/deployer/src/commands.ts#L35
However, the user may skip to do this. To make sure, we should clear the terminal afterwards and do a check such as "Enter the Nth word of you mnemonic" where N is a randomly generated integer between 1-12.
This check should be able to be disabled with a flag for debugging, etc.

**Comment by Arrowana** [comment]
What behaviour do we expect if one of the word is wrong when verifying? Should it give the mnemonic sentence again, then disappear after pressing return only to go throught the verification process again?

**Comment by bbenligiray** [comment]
Yes, that sounds right.
I think it should be the same mnemonic, because it's likely because they have actually noted it down but simply made a typo while entering a word.

**Comment by bbenligiray** [comment]
Implemented in https://github.com/api3dao/airnode/pull/186
