### ISSUE TITLE
Bump OIS version references every time OIS package is updated

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1441]
We already have a [script](https://github.com/api3dao/airnode/blob/master/scripts/update-config-fixtures.ts) for bumping node version in tests, example config files, etc. We need something similar for bumping OIS version references because otherwise, some tests will fail as the validator will incorrectly catch an OIS version mismatch.

**Comment by dcroote** [comment]
@aTeoke - this is an internal-facing script that will be run on the next OIS version bump so I don't think there is anything to test at the moment.
