### ISSUE TITLE
Allow retrieval of existing secrets (to enable redeployment with those secrets)

### ISSUE THREAD

**Issue by aquarat** [api3dao/airnode#1443]
TBD - currently being discussed [on Slack](https://api3workspace.slack.com/archives/C02AYRX8D89/p1663228424184189).

**Comment by amarthadan** [comment]
As discussed [on Slack](https://api3workspace.slack.com/archives/C02AYRX8D89/p1663586385441409?thread_ts=1663228424.184189&cid=C02AYRX8D89), this is kind of a duplicate of https://github.com/api3dao/airnode/issues/1405. I'll refine #1405 to reflect that. Closing.
