### ISSUE TITLE
📌 Issue Tag Policies 

### ISSUE THREAD

**Issue by aquarat** [api3dao/airnode#1447]
This is a PSA educational issue that will remain pinned.

The following only applies to existing issues; if you are creating an issue the following does not apply to you.

**General**
- Issues marked as deferred will not be implemented in the short to medium term and should not be considered for development.
- Deferred issues should remain open - this is to prevent duplication.
- An issue marked as "needs documentation" will automatically have an associated documentation task created.
- Issue size is set by the implementer and is purely for others' context.
- Issues should either be deferred or added to the backlog.
- A deferred issue should not be added to the API3 project board.

**TODO**
- Developers can pick up tasks from the TODO state in order of priority and size; 
- - eg. if you have two or three days left in the week you could pick up a low priority small task

**Releases**
- A [migration guide](https://github.com/api3dao/airnode/issues/1444) must be produced for every major and minor release.

**Comment by bbenligiray** [comment]
> Concern

Can you give an example?

**Comment by bbenligiray** [comment]
We should make it clear that these rules don't apply to a user creating an issue
