### ISSUE TITLE
Airnode Migration Guide v0.9

### ISSUE THREAD

**Issue by aquarat** [api3dao/airnode#1448]
[As per discussion](https://api3workspace.slack.com/archives/C02AYRX8D89/p1662645770275269) we need a migration guide. This should be along the lines of breaking changes and how to deal with them.

We need an issue like this for every release.

This is an important task as it impacts the public and ChainAPI.

**Comment by Siegrift** [comment]
Draft PR is ready, but I moved this to blocked state since it's not decided we want to keep this in Airnode repo or docs...

**Comment by aTeoke** [comment]
@Siegrift What is the status of the migration guide please? we agreed it will be part of docs

**Comment by Siegrift** [comment]
I've closed the Airnode PR and created a new one one for docs. You can check the latest (open) linked PR.
