### ISSUE TITLE
Fix failing redeployment when the HTTP gatewayes become disabled

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1450]
Based on the [discussion](https://github.com/api3dao/airnode/pull/1424#issuecomment-1244965821) in https://github.com/api3dao/airnode/pull/1424

During the PR review for https://github.com/api3dao/airnode/pull/1424 @Siegrift run into an issue where he got an error message noting a cyclic dependency in the Terraform recipes
```
Error: Cycle: module.httpSignedGw[0].aws_api_gateway_deployment.deployment (destroy), module.httpSignedGw[0].aws_api_gateway_rest_api.api_gateway (destroy), module.httpSignedReq[0].aws_lambda_function.lambda (destroy), module.httpSignedReq[0].null_resource.fetch_lambda_files (destroy), module.startCoordinator.aws_lambda_function.lambda
```

Steps to reproduce (not reliably though :smile:):
1. Deploy Airnode with both HTTP gateways enabled
2. Redeploy the same Airnode (running `deploy` again without a removal) with one of the gateways disabled
3. Redeploy the same Airnode (running `deploy` again without a removal) with both of the gateways disabled

**Comment by martinkolenic** [comment]
Hi, @amarthadan, I'm happy to report that despite various combinations of gateways enabled and disabled (and then both of them disabled), the deployments have been successful so far. I'll move this to Done then :)
