### ISSUE TITLE
Disable concurrency in airnode-examples

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#1451]
Initially found during testing when hit maximum concurrency limit. See: https://github.com/api3dao/airnode/pull/1424#pullrequestreview-1104590686

As Burak pointed out we should disable concurrency reservations so the deployment also works with fresh AWS accounts.

**Comment by bbenligiray** [comment]
Examples should enable https://docs.api3.org/airnode/v0.8/reference/deployment-files/config-json.html#cloudprovider-disableconcurrencyreservations so that they work with a default fresh AWS account. 1 will cause the deployment to fail.

**Comment by Siegrift** [comment]
Updated description.

**Comment by martinkolenic** [comment]
Hi @Siegrift, final report from this:

- I attempted setting concurrency to 1000, which is way over the limit for my account, and it made no difference
- I also attempted several deployments with both gateways turned on, which normally fills the concurrency after 3 such deployments. Having 5 of them was no problem.
