### ISSUE TITLE
Deploy Airnode contracts on Sepolia

### ISSUE THREAD

**Issue by dcroote** [api3dao/airnode#1452]
Motivated by deprecation of Rinkeby, Ropsten, and Kovan testnets and retirement of their associated block explorers, see #1280.

I would also suggest this include adding sepolia to the list of `airnode-examples` supported networks:
https://github.com/api3dao/airnode/blob/eeda6e3108b0dd95cf1c1f8c96eae4491a36fa39/packages/airnode-examples/src/utils.ts#L19

**Comment by dcroote** [comment]
Related to api3dao/airnode-protocol-v1#16

**Comment by bbenligiray** [comment]
@aquarat added to 0.10.0

**Comment by aquarat** [comment]
Also for your visibility @aTeoke ^

**Comment by bbenligiray** [comment]
Will be tested along with https://github.com/api3dao/airnode/issues/1280

**Comment by Siegrift** [comment]
I've changed the milestone to 0.9. since this was merged to master (which will be released as 0.9.)

**Comment by bbenligiray** [comment]
@Siegrift should I have waited to merge?

**Comment by Siegrift** [comment]
I think so. I noticed the milestone 0.10. only after you merged. For 0.10. features we are using https://github.com/api3dao/airnode/tree/temp-v0.10.0 ...

I don't think this is a big deal, but we should refrain from working on multiple versions at once in the future.

**Comment by bbenligiray** [comment]
Tested [here](https://github.com/api3dao/airnode/issues/1280#issuecomment-1268007699)
