### ISSUE TITLE
Update Airnode to use Node 16

### ISSUE THREAD

**Issue by aquarat** [api3dao/airnode#1457]
Node 16 has been out and stable for some time now. Airnode should be updated to use Node 16.
[AWS added support for Node 16 earlier this year](https://aws.amazon.com/about-aws/whats-new/2022/05/aws-lambda-adds-support-node-js-16/) and GCP also added support a few months ago.

Why update?
- Node 14 via NVM ships with a buggy npm version (which has been responsible for some issues in publishing Airnode in the past). Node 16 does not have this problem.
- Node 14 via NVM does not support arm64; there are potentially pricing-related savings for arm64 on Cloud; the main providers charge less for said platform and arm64 tends to be more efficient for certain I/O tasks. New Apple machines since 2020 are arm64 based and tools like eslint, tsc, prettier, etc. will run faster in dev environments on Mac machines.
- While not exhaustive, Node 14 is generally slower than 16 [1](https://medium.com/@ersun.warncke/benchmarking-node-js-v12-vs-v10-v8-v6-v4-and-go-89d28eee603d) [2](https://www.reddit.com/r/node/comments/nnkgri/node_16_is_so_damn_fast_i_didnt_expect_this/) 

This task should also bump the TS output (which will take advantage of newer Node features which should also improve performance).

**Comment by bbenligiray** [comment]
Note that we specify the node version in the pre/post processing snippets, but we don't have a way of honoring these. We can bump the snippet specs from `node14` to `node16` but that's not a nice solution. Instead, we should just change these to `node` (or `node.js` to be specific) and use the current node version that Airnode uses, and leave more strict specification to a later version.

**Comment by bbenligiray** [comment]
The alternative solution is keep it as `node14` and don't respect the version (use node v16), document this as such and come back to it later

**Comment by aTeoke** [comment]
seems like too much work now, postponing to later milestone

**Comment by dcroote** [comment]
For recordkeeping, this blocks https://github.com/api3dao/airnode/pull/1625.

On a positive note, [Node.js 18 runtime for GCP App Engine](https://cloud.google.com/appengine/docs/standard/nodejs/release-notes#January_17_2023) is now generally available and Node.js 18 is recommended for GCP [Cloud Functions](https://cloud.google.com/functions/docs/concepts/nodejs-runtime). It has been supported on AWS Lambda [since Nov 2022](https://aws.amazon.com/fr/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/).

**Comment by bbenligiray** [comment]
We should address https://github.com/api3dao/airnode/issues/1544 before or together with this

**Comment by aTeoke** [comment]
Do we want to skip Node.js 16 and go straight to Node.js 18?

**Comment by andreogle** [comment]
I think it's worth going straight to Node 18 since Node 16 is going to be EOL on 11 September 2023

**Comment by aTeoke** [comment]
Closing this issue, we will track progress in #1631
