### ISSUE TITLE
Allow users to remove the deployment based on the deployment ID

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1460]
User will be able to remove the deployment based on the deployment ID, e.g.:

```bash
airnode-deployer remove aws1697238d
```
Based on the deployment ID from the `list` command (https://github.com/api3dao/airnode/issues/1403).

This will replace the current `remove-with-deployment-details` command.

The deployment ID will be also added to the `receipt.json` and will be printed on the console at the end of the deployment process.

**Comment by amarthadan** [comment]
@bbenligiray @aquarat I've updated the description, let me know if it's ok.

**Comment by bbenligiray** [comment]
l-g-t-m

**Comment by martinkolenic** [comment]
Hi, I tested the following:

- removal of an AWS project (success)
- removal of a GCP project (success)

This looks well and from an end-user perspective, is also much easier to use than providing all the individual deployment details.
