### ISSUE TITLE
Prefix deployment ID with the cloud provider identification

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1473]
Prefixing deployment ID with the cloud provider identification will allow us to access only the cloud provider hosting the deployment for `info` and other commands. 
More information in the [Slack discussion](https://api3workspace.slack.com/archives/C02AYRX8D89/p1664179287904649)

Part of this is also a refactor of the `info` command mentioned in https://github.com/api3dao/airnode/pull/1477

**Comment by martinkolenic** [comment]
Hi, I've tested this in conjunction with the deployment ID-based removal. The IDs are all prefixed depending on the cloud I'm uploading to; I did not notice any mishaps (i.e. no incorrect prefixation).
