### ISSUE TITLE
Release Airnode v0.9

### ISSUE THREAD

**Issue by aquarat** [api3dao/airnode#1485]
Release Airnode v0.9

Requires testing of snapshot packages prior to actual publish.

**Comment by aquarat** [comment]
Snapshot packages have been published.

Please test when you can @martinkolenic , thanks :D

(v0.9)
🦋  info Publishing "@api3/airnode-abi" at "0.0.0-snapshot-v0.9.0-20221003100627"                                                                                                                                                                                                                                                                                         
🦋  info Publishing "@api3/airnode-adapter" at "0.0.0-snapshot-v0.9.0-20221003100627"                                                                                                
🦋  info Publishing "@api3/airnode-admin" at "0.0.0-snapshot-v0.9.0-20221003100627"                                                                                                  
🦋  info Publishing "@api3/airnode-deployer" at "0.0.0-snapshot-v0.9.0-20221003100627"    
🦋  info Publishing "@api3/airnode-examples" at "0.0.0-snapshot-v0.9.0-20221003100627"                                                                                               
🦋  info Publishing "@api3/airnode-node" at "0.0.0-snapshot-v0.9.0-20221003100627"                                                                                                   
🦋  info Publishing "@api3/airnode-operation" at "0.0.0-snapshot-v0.9.0-20221003100627"                                                                                              
🦋  info Publishing "@api3/airnode-protocol" at "0.0.0-snapshot-v0.9.0-20221003100627"                                                                                               
🦋  info Publishing "@api3/airnode-utilities" at "0.0.0-snapshot-v0.9.0-20221003100627"                                                                                              
🦋  info Publishing "@api3/airnode-validator" at "0.0.0-snapshot-v0.9.0-20221003100627" 

(v0.8.1)
🦋  info Publishing "@api3/airnode-abi" at "0.0.0-snapshot-v0.8.1-20221003104125"
🦋  info Publishing "@api3/airnode-adapter" at "0.0.0-snapshot-v0.8.1-20221003104125"
🦋  info Publishing "@api3/airnode-admin" at "0.0.0-snapshot-v0.8.1-20221003104125"
🦋  info Publishing "@api3/airnode-deployer" at "0.0.0-snapshot-v0.8.1-20221003104125"
🦋  info Publishing "@api3/airnode-examples" at "0.0.0-snapshot-v0.8.1-20221003104125"
🦋  info Publishing "@api3/airnode-node" at "0.0.0-snapshot-v0.8.1-20221003104125"
🦋  info Publishing "@api3/airnode-operation" at "0.0.0-snapshot-v0.8.1-20221003104125"
🦋  info Publishing "@api3/airnode-protocol" at "0.0.0-snapshot-v0.8.1-20221003104125"
🦋  info Publishing "@api3/airnode-utilities" at "0.0.0-snapshot-v0.8.1-20221003104125"
🦋  info Publishing "@api3/airnode-validator" at "0.0.0-snapshot-v0.8.1-20221003104125"

Docker images to follow.

**Comment by aquarat** [comment]
Docker images for v0.8.1:
api3/airnode-client-dev:0.8.1-2210031455
api3/airnode-admin-dev:0.8.1-2210031455
api3/airnode-deployer-dev:0.8.1-2210031455

**Comment by aquarat** [comment]
Docker images for v0.9.0:
api3/airnode-admin-dev:0.9.0-2210031518
api3/airnode-deployer-dev:0.9.0-2210031518
api3/airnode-client-dev:0.9.0-2210031518

**Comment by martinkolenic** [comment]
Hi @aquarat, I've tried to run the airnode-admin snapshot for 0.9.0 but it doesn't seem to be accessible:
```
Starting: @api3/airnode-admin:0.0.0-snapshot-v0.9.0-20221003100627 generate-mnemonic
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/home/martin/Development/@api3/airnode-admin:0.0.0-snapshot-v0.9.0-20221003100627'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
```
My command was simply "npx run @api3/airnode-admin:...". I don't think I did anything wrong.

**Comment by Siegrift** [comment]
What command did you run? I was curious, so I tried it myself and it seems to work for me (both docker and npx):

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/22679154/193842489-f0f59bfb-0024-4d23-a551-4cd7c2d87d32.png">

**Comment by aquarat** [comment]
I'll try from a separate machine just in case (as an extra precaution) (thanks to you both).

**Comment by aquarat** [comment]
Works for me too when the `@` is swapped in 💪

**Comment by martinkolenic** [comment]
Right, works for me too with the changed character. Sorry about that. Most packages seem to be working but I'll only be able to test the rest later tonight.

**Comment by martinkolenic** [comment]
Hi @aquarat, I tested both v0.8.1 and v0.9.0 and run basic functionality checks of:

- admin, 
- validator, 
- node, 
- deployer.

All seem to be working as intended. Sorry for the delay, I'm on the train and it took me a moment to get the connection up and running.

**Comment by aquarat** [comment]
Absolutely no problem @martinkolenic , thanks for testing 🚜 😄

**Comment by aquarat** [comment]
FYI Currently building before publish.
