### ISSUE TITLE
Use the region of the first Airnode deployment for the bucket location

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1487]
[Slack discussion](https://api3workspace.slack.com/archives/C02AYRX8D89/p1664799843233839)

**Comment by martinkolenic** [comment]
Hi, I tested with several deployments in different regions; the common bucket was in non-default region (ap-southeast-1) and stayed that way even after removing that Airnode itself and keeping the other two. I think this functions as intended and, most importantly, actually allows for successful deployment to a non-default region.
