### ISSUE TITLE
Airnode fails at runtime if secrets are quoted

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#1510]
Raised internally in https://api3workspace.slack.com/archives/C02R79STBRA/p1666803628395139

**Comment by andreogle** [comment]
Made this comment on the PR, but I think the issue is more appropriate so moving it here:

Is the plan to release a v0.9.1 for this fix? Does this affect any other prior versions?

**Comment by amarthadan** [comment]
> Is the plan to release a v0.9.1 for this fix?

Yes, it just slipped my mind, thanks for reminding me :slightly_smiling_face: 

> Does this affect any other prior versions?

It does not. I've introduced the bug in this commit https://github.com/api3dao/airnode/commit/b67047b7e04703ffef5cacc44197975a2e12bc38 and it's only part of the v0.9.

**Comment by martinkolenic** [comment]
Test: Check if quotation marks in secrets cause deployment errors
Versions tested: v0.9.1 snapshots; master
Deployed to: AWS
Testnet: Görli

Test flow: Create secrets.env and wrap secret values in quotation marks, then attempt deployment
Subtests: Only wrap one of the values in quotes, vary the values quoted

Expected results: Quotation marks are ignored, deployment successful and Airnode works, fulfilling API requests.
Actual results: Matches expected results.
