### ISSUE TITLE
OpenAPI specifications to OIS converter

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#152]
We need an OIS tool to convert [OpenAPI specifications](https://github.com/OAI/OpenAPI-Specification) to [Oracle Integration Specifications](https://github.com/api3dao/api3-docs/blob/master/airnode/ois.md) automatically (see [this](https://github.com/api3dao/api3-docs/blob/master/provider-guides/api-integration.md#step-1-specifying-the-api)). Please comment below if you are interested in building this.

**Comment by gpor0** [comment]
Can you provide more details? Also link is broken.

**Comment by bbenligiray** [comment]
Thanks for pointing that out, I fixed links in a bunch of issues.

Say we want to integrate the Petstore API to the Airnode and we have the OpenAPI specs for it
https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.json
Currently, you would need to create an [OIS](https://github.com/api3dao/api3-docs/blob/master/airnode/ois.md) following this guide
https://github.com/api3dao/api3-docs/blob/master/provider-guides/api-integration.md#step-1-specifying-the-api
However, the [`apiSpecifications`](https://github.com/api3dao/api3-docs/blob/master/airnode/ois.md#4-apiSpecifications) field of the OIS is pretty much in the same format as OpenAPI specifications with a few differences. So a tool can generate OIS from existing OpenAPI specifications and allow us to integrate APIs that provide their OpenAPI specifications automatically.

The OIS docs include some guidelines for how this tool should work. For example, [here](https://github.com/api3dao/api3-docs/blob/master/airnode/ois.md#41-servers), it says that this field should be sourced from the `servers.0` field of OpenAPI specs and the tool should raise a warning if `servers` consists of multiple elements (because this means that there are multiple base URLs that can be chosen from and just using the first one may not be correct and whoever is doing the integration should verify that the correct base URL is entered in the OIS).

Ideally this would be a JS/TS script because we don't want to diversify our stack too much. It would look like [this validator tool](https://github.com/api3dao/airnode/tree/master/packages/validator).
