### ISSUE TITLE
Fix incorrect merge of temp-v10 branch to master

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#1521]
At the start of v0.10.0 we worked on a separate branch that we later merged to master. One of the issues we implemented was to [move from API-keys authentication to URL path based ones](https://github.com/api3dao/airnode/pull/1418). Once the temporary branch was merged to main, it was not merged correctly some of the previously removed code was reintroduced again https://github.com/api3dao/airnode/blob/master/packages/airnode-deployer/src/handlers/gcp/index.ts#L126.

We should check how the merge was performed, why it was incorrectly merged and check all of the features implemented in the temporary branch to see if they were merged correctly.

**Comment by Siegrift** [comment]
Part of the reason why the broken merge occurred was my fault... I accidentally removed few commits while force pushing https://github.com/api3dao/airnode/pull/1434. I think I haven't pulled the latest changes from the origin before doing the rebase... The lesson for me is to use merge on shared branches and make the branch protected to avoid force pushes.

**Comment by martinkolenic** [comment]
### Feature tests
**Heartbeat signature testing (and ID removal)**
Steps: Check for the presence of heartbeat signature using the coingecko-signed-data Airnode example, enabling heartbeat, deploying Airnode to AWS and then listening to it using Beeceptor. 

_Expected result: the Beeceptor endpoint should receive a request that includes a heartbeat signature; the heartbeat ID should not be present in the payload (nor the config)
Actual result: Matches expected result
Environment: Beeceptor, AWS cloud provider, Goerli testnet_

**HTTP Gateways not requiring API keys for authentication**
Steps: Deploy the coingecko-testable example integration, send request to the generated address via CURL without the API key parameter

Expected result: Receive a valid response
Actual result: Matches expected result
Environment: local OS Fedora 37 Beta, Linux 5.19.16, AWS cloud provider, CURL utility
0
### Standard tests
**Basic Airnode functionality test (Docker and npm package tests)**
Steps: Use airnode-deployer docker image to deploy Airnode to AWS (via Docker) and GCP (via the npm package), use the coingecko-signed-data example integration (altered to enable the basic gateway as well) and test making request via the provided script, and test the gateways via CURL.

_Expected result: Successful request fulfillment
Actual result: Matches expected result
Environment: AWS and GCP cloud providers, Görli testnet_

**Basic Airnode functionality test (Client Docker and image and npm package)**
Steps: Run Airnode locally on a local chain using the coingecko example and make a request.

_Expected result: Successful request fulfillment
Actual result: Matches expected result
Environment: Fedora 37 Beta, Linux 5.19.16, local Airnode, local hardhat node._

**Validator test (npm package)**
Steps: Produce a malformed config.json and feed it to the airnode-validator npm package. Then, fix errors and rerun the validation

_Expected result: The malformed config file does not pass validation, the fixed one does.
Actual result: Matches expected result
Environment: local OS Fedora 37 beta, Linux 5.19.16_

**Admin test (npm package)**
Steps: Generate a mnemonic to check that the package works.

_Expected result: The admin script generates a mnemonic.
Actual result: Matches expected result
Environment: local OS Fedora 37 beta, Linux 5.19.16_

**Comment by martinkolenic** [comment]
Hi, I have run the basic functionality test again yesterday (see [the testing report](https://github.com/api3dao/airnode/issues/1530#issuecomment-131697822)) and it seems my requests time out repeatedly. I'm currently retesting this on GCP to check if the issue is present there as well.

**Comment by martinkolenic** [comment]
Hi, I have tested an example integration with signed data gateways. 

**Basic functionality test**
Steps: Deploy the coingecko-signed-data integration on AWS, attempt a  RRP request and a HTTP request

Expected results: Proper deployment and meaningful RRP and HTTP request responses
Actual results: The Airnode was deployed properly and both the RRP and the HTTP request returned a meaningful response.

Screenshots:
![Image](https://user-images.githubusercontent.com/884979/203562408-c3eeedda-c261-4b27-ac34-983776a7ec48.png)
![Image](https://user-images.githubusercontent.com/884979/203562410-0497ae3b-ae57-4e63-a2c6-e150a0a54b12.png)
![Image](https://user-images.githubusercontent.com/884979/203562407-09de72f7-105d-4dd4-bd0a-ff08a00489dc.png)
![Image](https://user-images.githubusercontent.com/884979/203563715-bb83c0f0-c24b-43ab-a6d1-b6d6a264c599.png)

**Comment by martinkolenic** [comment]
The above test does not utilize API keys to get the response and relies solely on the route-based authentication, which indicates this part of the merge works as intended as well.
