### ISSUE TITLE
Deployer broken after v0.10.0 merge fix attempt

### ISSUE THREAD

**Issue by dcroote** [api3dao/airnode#1530]
After #1522 it appears the latest `airnode-deployer` is broken based on running `airnode-examples` and `quick-deploy-aws` using the latest `master` commit i.e. `api3/airnode-deployer-dev:55dd3c68bd075f998dae1148ee246298d536347e`. I think it stems from work missing from #1418 as this is where `http_signed_data_api_key` and `http_api_key` were removed.

CC @amarthadan @Siegrift @vponline 

```sh
Error: Reference to undeclared input variable

  on main.tf line 30, in module "startCoordinatorNoGws":
  30:   count  = var.http_api_key == null && var.http_signed_data_api_key == null ? 1 : 0

An input variable with the name "http_api_key" has not been declared. This
variable can be declared with a variable "http_api_key" {} block.

Error: Reference to undeclared input variable

  on main.tf line 30, in module "startCoordinatorNoGws":
  30:   count  = var.http_api_key == null && var.http_signed_data_api_key == null ? 1 : 0

An input variable with the name "http_signed_data_api_key" has not been
declared. This variable can be declared with a variable
"http_signed_data_api_key" {} block.

Error: Reference to undeclared input variable

  on main.tf line 53, in module "startCoordinatorHttpGw":
  53:   count  = var.http_api_key != null && var.http_signed_data_api_key == null ? 1 : 0

An input variable with the name "http_api_key" has not been declared. This
variable can be declared with a variable "http_api_key" {} block.

Error: Reference to undeclared input variable

  on main.tf line 53, in module "startCoordinatorHttpGw":
  53:   count  = var.http_api_key != null && var.http_signed_data_api_key == null ? 1 : 0

An input variable with the name "http_signed_data_api_key" has not been
declared. This variable can be declared with a variable
"http_signed_data_api_key" {} block.

Error: Reference to undeclared input variable

  on main.tf line 77, in module "startCoordinatorHttpSignedGw":
  77:   count  = var.http_api_key == null && var.http_signed_data_api_key != null ? 1 : 0

An input variable with the name "http_api_key" has not been declared. This
variable can be declared with a variable "http_api_key" {} block.

Error: Reference to undeclared input variable

  on main.tf line 77, in module "startCoordinatorHttpSignedGw":
  77:   count  = var.http_api_key == null && var.http_signed_data_api_key != null ? 1 : 0

An input variable with the name "http_signed_data_api_key" has not been
declared. This variable can be declared with a variable
"http_signed_data_api_key" {} block.

Error: Reference to undeclared input variable

  on main.tf line 101, in module "startCoordinatorBothGws":
 101:   count  = var.http_api_key != null && var.http_signed_data_api_key != null ? 1 : 0

An input variable with the name "http_api_key" has not been declared. This
variable can be declared with a variable "http_api_key" {} block.

Error: Reference to undeclared input variable

  on main.tf line 101, in module "startCoordinatorBothGws":
 101:   count  = var.http_api_key != null && var.http_signed_data_api_key != null ? 1 : 0

An input variable with the name "http_signed_data_api_key" has not been
declared. This variable can be declared with a variable
"http_signed_data_api_key" {} block.
```

**Comment by martinkolenic** [comment]
Hi, I tested the issue on the latest commit (see `git log` screenshot).

**Test: Deployer functionality test and basic behaviour check**
_Remote environment:_ AWS, Gōrli testnet
_Local environment:_ Fedora 37, Linux 6.0.2

**Steps:**
Using the coingecko-signed-data example integration, attempt to make a request using the provided scripts.

**Expected result:**
Successful deployment of the latest Airnode is possible and a meaningful response is returned.

**Actual result:**
The deployment is successful; however, the request times out repeatedly.

**Screenshots:**
_Git log:_
![Image](https://user-images.githubusercontent.com/884979/202173101-79f2dfa8-f531-448a-94fa-fb7bd1f3e616.png)
_Successful deployment:_
![Image](https://user-images.githubusercontent.com/884979/202183913-c9601ee3-b4dc-4739-8000-0088091992df.png)
_Request failure:_
```
 martin@chikorita  ~/.../packages/airnode-examples   master  yarn deploy-airnode api3/airnode-deployer-dev:7f9ada096a4e12db48a6bcb6bb728297b175be57
yarn run v1.22.19
$ ts-node src/scripts/deploy-airnode.ts api3/airnode-deployer-dev:7f9ada096a4e12db48a6bcb6bb728297b175be57
docker run -it --rm -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v /home/martin/Dev/airnode/packages/airnode-examples/integrations/coingecko-signed-data:/app/config api3/airnode-deployer-dev:7f9ada096a4e12db48a6bcb6bb728297b175be57 deploy
  ___  _                      _      
 / _ \(_)                    | |     
/ /_\ \_ _ __ _ __   ___   __| | ___ 
|  _  | | '__| '_ \ / _ \ / _` |/ _ \
| | | | | |  | | | | (_) | (_| |  __/
\_| |_/_|_|  |_| |_|\___/ \__,_|\___|

          Airnode v0.9.0

✔ Deployed Airnode 0x9B450Bfc1680666ACef35EC7ee4385005ad28Ef0 dev to aws us-east-1
ℹ Outputted config/receipt.json
  This file does not contain any sensitive information.
ℹ HTTP signed data gateway URL: https://323m7a61db.execute-api.us-east-1.amazonaws.com/v1/70c8eabb-a2c1-7f58-6ebb-11664337dc86
Done in 118.81s.
 martin@chikorita  ~/.../packages/airnode-examples   master  yarn deploy-requester && yarn derive-and-fund-sponsor-wallet && yarn sponsor-requester && sleep 60 && yarn make-request
yarn run v1.22.19
$ ts-node src/scripts/deploy-requester.ts
Requester deployed to address: 0x79c6ADA12AcC02baD6288a7d80b66B51d15f1e55
Done in 31.13s.
yarn run v1.22.19
$ ts-node src/scripts/derive-and-fund-sponsor-wallet.ts
Successfully sent funds to sponsor wallet address: 0xf5f691B44b585293Cf004E05389A2FB67430beaa.
Current balance: 0.1
Done in 34.42s.
yarn run v1.22.19
$ ts-node src/scripts/sponsor-requester.ts
Requester address: 0x79c6ADA12AcC02baD6288a7d80b66B51d15f1e55 is now sponsored
Done in 13.02s.
yarn run v1.22.19
$ ts-node src/scripts/make-request.ts
Making request...
Waiting for fulfillment...
Timeout exceeded!
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 ✘ martin@chikorita  ~/.../packages/airnode-examples   master  yarn make-request
yarn run v1.22.19
$ ts-node src/scripts/make-request.ts
Making request...
Waiting for fulfillment...
Timeout exceeded!
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Siegrift** [comment]
I've reproduced the error as well. It seems the startCoordinator module is not deployed when deployed with signed data gateway... When you deploy Airnode without gateways it seems to work correctly. I've also checked https://github.com/api3dao/airnode/commit/4f3454cf40e1b0a1373e954df96ac22e1ce2e43f (latest commit before the merge of missing 0.10.0 features) and that works correctly.

It seems some of the functionality was not rebased correctly.

**Comment by Siegrift** [comment]
The same thing happens when I deploy just with the testing gateway... You can see this immediately after deployment in the AWS lambda or logs section and see that the coordinator is not there...

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/22679154/202303819-b67b30c9-9011-4f63-9609-7a897b278fb4.png">
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/22679154/202303865-f4ef36d9-4a0a-4326-98c7-133b895d3aa8.png">

@amarthadan Do you have an idea what could be wrong? I've looked at the AWS receipts, but they look correct to me... But it must have been caused by https://github.com/api3dao/airnode/commit/55dd3c68bd075f998dae1148ee246298d536347e or https://github.com/api3dao/airnode/commit/7f9ada096a4e12db48a6bcb6bb728297b175be57

**Comment by martinkolenic** [comment]
Hi, I have tested an example integration with signed data gateways. 

**Basic functionality test**
Steps: Deploy the coingecko-signed-data integration on AWS, attempt a  RRP request and a HTTP request

Expected results: Proper deployment and meaningful RRP and HTTP request responses
Actual results: The Airnode was deployed properly and both the RRP and the HTTP request returned a meaningful response.

Screenshots:
![Image](https://user-images.githubusercontent.com/884979/203562408-c3eeedda-c261-4b27-ac34-983776a7ec48.png)
![Image](https://user-images.githubusercontent.com/884979/203562410-0497ae3b-ae57-4e63-a2c6-e150a0a54b12.png)
![Image](https://user-images.githubusercontent.com/884979/203562407-09de72f7-105d-4dd4-bd0a-ff08a00489dc.png)
![Image](https://user-images.githubusercontent.com/884979/203563715-bb83c0f0-c24b-43ab-a6d1-b6d6a264c599.png)
