### ISSUE TITLE
Simplify Heartbeat packing/signing

### ISSUE THREAD

**Issue by aquarat** [api3dao/airnode#1536]
In Airnode v0.9 we introduced a new heartbeat schema, which involves a signature.

The signature mechanism itself is relatively well supported in languages other than JS/TS, but the binary packing method used as part of the signature process is not as well supported, particularly in Elixir, which is what ChainAPI uses.

Refer to [heartbeats.ts](https://github.com/api3dao/airnode/blob/55dd3c68bd075f998dae1148ee246298d536347e/packages/airnode-node/src/reporting/heartbeat.ts#L39), specifically:
```typescript
  return airnodeWallet.signMessage(
    ethers.utils.arrayify(
      ethers.utils.solidityKeccak256(['uint256', 'string'], [timestamp, JSON.stringify(heartbeatPayload)])
    )
  );
```
which should change to:
```typescript
  return airnodeWallet.signMessage(heartbeatPayload); // heartbeatPayload is a JSON string with heartbeatPayload as it's contents and a timestamp added
};
```

This removes the binary packing.
Ideally the JSON payload should be nested as a string to prevent encoding differences between languages causing verification to fail.

This is an urgent task.

Please check you're happy @andreogle

**Comment by martinkolenic** [comment]
Hi @aquarat, is this issue tested by André or do you need me to take a look?
