### ISSUE TITLE
Only AWS is supported for the serverless configuration

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#154]
Currently the deployer only supports AWS. We want to support others as well, starting from GCP and Azure. Please comment below if you are interested in contributing.

Tracked by https://api3dao.atlassian.net/browse/AN-157

**Comment by Arrowana** [comment]
I am willing to do the azure implementation of the deployer.
I am not familiar with terraform or azure function but this should be fine to learn.

**Comment by bbenligiray** [comment]
Sure, please go ahead. I want to give you a heads up about a few issues you may encounter:
- [This Serverless plugin](https://github.com/api3dao/airnode/blob/3bed327c64b72a73dc6dc3a8a8416aa3be9c73be/packages/deployer/serverless.aws.yml#L6) we use is [AWS-specific](https://github.com/FidelLimited/serverless-plugin-optimize/issues/51). We use it to both to reduce the size of the deployment and also to take care of the symlinks to the other packages in the monorepo (from the deployer to the node for example). We'll probably have to implement a custom packer first to port the node to non-AWS providers (and after doing that the port itself is trivial anyway).
- The deployer uses AWS SSM extensively to manage the mnemonic, but at the end of the day, it goes in the node environment variables under the name `MASTER_KEY_MNEMONIC`. We need to figure out how we want to deal with this:
  - Use the equivalent of SSM for each cloud provider (porting overhead, but maybe not that much)
  - Always keep the mnemonic in AWS SSM (the user always needs to have at least one AWS deployment, weird but fine imo, especially as a temporary solution)
  - Treat SSM as an optional feature (the user would have to handle their mnemonic at each redeployment, definitely not desirable)
  
  Feel free to join our Discord btw

**Comment by bbenligiray** [comment]
Related to this issue https://github.com/api3dao/airnode/issues/112

**Comment by Ashar2shahid** [comment]
There are some issues with directory structuring when deploying with Google Cloud in [particular](https://www.serverless.com/framework/docs/providers/google/guide/functions/)

> Google Cloud Functions assumes that you have a index.js or function.js file with the exported handler functions in the root of your project (you can read more about that in their docs).

Even after keeping the index.js in the directory and deploying the functions onto GCP there were issues in the packaging due to 
```
src/handlers/aws/index.ts:2:23 - error TS2307: Cannot find module '@airnode/node' or its corresponding type declarations.
```

I think serverless wouldn't really be a viable option for this particular task and have to use terraform instead.

**Comment by bbenligiray** [comment]
Blocked by https://github.com/api3dao/airnode/issues/206

**Comment by bbenligiray** [comment]
Blocked by the deployer being under development

**Comment by bbenligiray** [comment]
We now support GCP https://github.com/api3dao/airnode/releases/tag/v0.3.0
