### ISSUE TITLE
Relax engine specification for pre/post-processing

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1544]
Currently pre/post-processing snippets require the node version to be specified. We're also constantly updating the Airnode node version. For a lack of a better alternative, I suggest dropping the node version (so `node` or `node.js` instead of `node14`). The alternative is to deploy multiple pre/post-processing environments for these to be run on, but even this is not a permanent solution because node versions fall out of support and cloud providers stop providing these even earlier than that.

**Comment by dcroote** [comment]
> We're also constantly updating the Airnode node version.

You don't think we'll stay on 18 for a while after https://github.com/api3dao/airnode/issues/1631?

**Comment by Siegrift** [comment]
These versions are supported roughly for ~2years, so they are not permanent. 

I support the idea of dropping the node version from processing name and use whatever node the Airnode was deployed on. Other alternatives don't seem feasible to me.

**Comment by dcroote** [comment]
Blocked by https://github.com/api3dao/ois/issues/65 and a subsequent OIS release.

**Comment by aTeoke** [comment]
Hey, I was trying to test this via `coingecko-pre-processing` example, but got this error. 
```
Error details:
2023-02-20T16:29:56.218Z ✖ Invalid Airnode configuration file: [
  {
    "code": "custom",
    "message": "oisFormat major.minor version must match major.minor version of \"1.4.0\"",
    "path": [
      "ois",
      0,
      "oisFormat"
    ]
  },
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_literal",
            "expected": "Node 14",
            "path": [
              "ois",
              0,
              "endpoints",
              0,
              "preProcessingSpecifications",
              0,
              "environment"
            ],
            "message": "Invalid literal value, expected \"Node 14\""
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_literal",
            "expected": "Node 14 async",
            "path": [
              "ois",
              0,
              "endpoints",
              0,
              "preProcessingSpecifications",
              0,
              "environment"
            ],
            "message": "Invalid literal value, expected \"Node 14 async\""
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      "ois",
      0,
      "endpoints",
      0,
      "preProcessingSpecifications",
      0,
      "environment"
    ],
    "message": "Invalid input"
  }
]
```

@dcroote could you please help?

**Comment by dcroote** [comment]
Sure. For testing a new feature recently merged to `master`, you need to use one of the `-dev` Docker images and the appropriate commit sha. For this feature I would suggest the merge commit of #1652 , which is `b2f1edfad867bb027f845b3dd2d601258ba7091d`. With that, refer to the [airnode-examples README](https://github.com/api3dao/airnode/tree/master/packages/airnode-examples#9-only-if-deploying-to-a-cloud-provider-deploy-airnode) for how to use either the `api3/airnode-deployer-dev` or `api3/airnode-client-dev` image and sha depending on whether you're deploying to a cloud provider or running locally, respectively. An example of the former would be `yarn deploy-airnode api3/airnode-deployer-dev:b2f1edfad867bb027f845b3dd2d601258ba7091d`

**Comment by aTeoke** [comment]
another error during deploying requester - cannot estimate gas

![Image](https://user-images.githubusercontent.com/82645914/220282848-4c0134ad-4fca-412f-ab3d-7c28a810d5fe.png)

**Comment by aTeoke** [comment]
fixed the issue above, tested it via coingecko-pre-processing example, worked ok

**Comment by dcroote** [comment]
> fixed the issue above, tested it via coingecko-pre-processing example, worked ok

Nice 👍
