### ISSUE TITLE
Add an API failure e2e test

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1550]
Add an e2e test where the API responds with a non-2XX code and the Airnode responds by calling [`fail()`](https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/contracts/rrp/AirnodeRrpV0.sol#L277)

**Comment by dcroote** [comment]
@bbenligiray - we actually have this: the following `airnode-node` e2e test calls `fail` and reports the failed request API status code (404 in this case) on-chain:

https://github.com/api3dao/airnode/blob/c77e843e5c060a6d1400d42f56e5b8dae9645f63/packages/airnode-node/test/e2e/request-status.feature.ts#L10-L47

**Comment by bbenligiray** [comment]
Indeed, thanks for checking
