### ISSUE TITLE
[v0.9] Investigate coordinator failure for faulty provider

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#1565]
Backport of https://github.com/api3dao/airnode/issues/1581

**Comment by martinkolenic** [comment]
Hi @Siegrift, I've tested the issue.

Steps: Deploy Airnode with a faulty provider URL (a Beeceptor URL with a 1000s delay before a response)
Expected result: Coordinator keeps functioning but displays an error message
Actual result: Matches expected result

I tested this on snapshots of v0.9.2 pre-release packages but wiped the logs by accident. I can retest this if you want a screenshot.

**Comment by Siegrift** [comment]
No need. Thanks.
