### ISSUE TITLE
The deploy:verify-local script in airnode-protocol only works for undeterministic deployments

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1567]
The `deploy:verify-local`  npm script in `airnode-protocol` only work for undeterministic deployments. This is actually fine, because deterministic deployments all have the same address, and the address being the same is the verification (that they have the correct bytecodes and constructor arguments). However, it would still be nice if it worked for all deployments so that when it's added to CI one doesn't need to make exceptions for deterministic deployments, which may be cumbersome to detect.

**Comment by Ashar2shahid** [comment]
PR https://github.com/api3dao/airnode/pull/1590

**Comment by martinkolenic** [comment]
Hi @bbenligiray, is this testable from an end-user perspective? Thanks.
