### ISSUE TITLE
Log fulfillments and failures

### ISSUE THREAD

**Issue by aTeoke** [api3dao/airnode#1571]
Ashar mentioned that he would have expected the node to log the error message while fulfilling with it [here](https://github.com/api3dao/airnode/blob/1c9ea904aee1c99f712faba3b3c584b1932cd362/packages/airnode-node/src/evm/fulfillments/api-calls.ts#L122). Logging regular responses shouldn’t be a problem too, since they are already being written to a blockchain. So the node should log both the successful and unsuccessful fulfillment details/contents.

**Comment by dcroote** [comment]
Closing as both successes and failures are already logged by functions called from within `testAndSubmitFulfill`. For example, `testFulfill` logs errors here:

https://github.com/api3dao/airnode/blob/9193df3c55a8a46e578465aec8a2585af46ea5e2/packages/airnode-node/src/evm/fulfillments/api-calls.ts#L67-L73

`submitFail` logs API call fail submission here: https://github.com/api3dao/airnode/blob/9193df3c55a8a46e578465aec8a2585af46ea5e2/packages/airnode-node/src/evm/fulfillments/api-calls.ts#L163

and logs errors with that just below. Lastly, `submitFulfill` creates similar logs as `submitFail`.
