### ISSUE TITLE
Replace references to milkomeda to milkomeda-cardano

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1575]
We currently refer to a Milkomeda C1 as `milkomeda`, which is awkward when considering there is also a Milkomeda A1. I suggest referring to these as `milkomeda-cardano` and potentially `milkomeda-algorand`, respectively. A precedent is different boba L2s here https://github.com/api3dao/airnode/pull/1562

**Comment by dcroote** [comment]
Closing as complete. The transition to using @api3/chains in https://github.com/api3dao/airnode/pull/1739 changed `milkomeda` to `milkomeda-c1`.
