### ISSUE TITLE
Replace references to Ethereum-related chains

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1576]
Currently we refer to Ethereum mainnet as `mainnet` and Ethereum testnets with `goerli` and `sepolia`. This may be confusing, we may want to switch to `ethereum`, `ethereum-goerli`, `ethereum-sepolia`, respectively.

**Comment by dcroote** [comment]
Closing as complete. The transition to using @api3/chains in https://github.com/api3dao/airnode/pull/1739 changed `mainnet` to `ethereum`, `goerli` to `ethereum-goerli-testnet` and `sepolia` to `ethereum-sepolia-testnet`.
