### ISSUE TITLE
Release 0.9.2

### ISSUE THREAD

**Issue by aTeoke** [api3dao/airnode#1578]
Backport tasks for 0.9.2 release:
- [x] - https://github.com/api3dao/airnode/issues/1583
- [x] - https://github.com/api3dao/airnode/issues/1565

The release is blocked until all of the issues here are completed (cc: @aTeoke )

**Comment by amarthadan** [comment]
Created snapshot packages and Docker images for v0.9.2 and testing issue for them https://github.com/api3dao/airnode/issues/1588.

Once tested, I'll do a proper release.

**Comment by amarthadan** [comment]
The release is done. Moving to Testing.

@martinkolenic 
All NPM packages and Docker images are available under the `0.9.2` tag (or `latest` at the moment).

**Comment by martinkolenic** [comment]
Hi, @amarthadan, this has been tested. The test reports are below; unfortunately I automatically cleared the terminal screen when I was done before being able to stop myself so I have no screenshots. Please let me know if you wish me to rerun the tests with the screenshots. Airnode deployer screen did show v0.9.2.

1: Deploy and remove Airnode (Docker, npm) - PASS
Steps: I deployed (using the Docker image) and removed (using the npm package) Airnode with the coingecko-signed-data example. I then ran a POST request to the gateway to check that functionality.
Expected result: Successful deployment and meaningful POST request response
Actual result: Matches the expected result

2: Test admin (Docker, npm) - PASS
Steps: I tested mnemonic generation in both the npm package and the Docker image.
Expected result: Successful command execution
Actual result: Matches the expected result

3: Test validator (npm) - PASS
Steps: Run it against a valid and invalid config file
Expected result: Confirm the (in)validity of the config files
Actual result: Matches expected result
