### ISSUE TITLE
Implement the HTTP gateway to facilitate OEV auctions

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1579]
See https://github.com/api3dao/oev-litepaper/blob/main/fig/oev-relay/oev-relay.pdf

On step 1, the OEV relay uses the current signed HTTP gateway to collect signed data of Beacons for which there are auctions being held. No need to do build anything new here.

On step 4, we need a new HTTP gateway that can be called with the signed data from step 1 and additional OEV auction bid parameters such as the amount. The gateway verifies the signature, validates the bid parameters (in the current version there will be no validation, i.e., the Airnode will trust the OEV relay with determining the winning bid), then signs the same data with the bid parameters from the call.

Links:
- [This](https://github.com/api3dao/airnode-protocol-v1/blob/268682841b25857ffd8f132c3e91327c414d78a1/contracts/dapis/DapiServer.sol#L1283) is how the signature should look like
- [This](https://github.com/api3dao/airnode-protocol-v1/blob/268682841b25857ffd8f132c3e91327c414d78a1/contracts/dapis/DapiServer.sol#L791) is the metadata hash that will be sent to Airnode as payload.

**Comment by bbenligiray** [comment]
As a note, this will be affected by the updates after the audit

**Comment by amarthadan** [comment]
There will be some changes in requirements based on the results of the audit. Moving to Blocked. Should be back on track next week.
