### ISSUE TITLE
Investigate coordinator failure for faulty provider

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#1581]
https://api3workspace.slack.com/archives/C02AYRX8D89/p1669812538505089?thread_ts=1669715564.101439&cid=C02AYRX8D89

**Comment by Siegrift** [comment]
The reason is the `JSON.parse` in https://github.com/api3dao/airnode/blob/master/packages/airnode-node/src/workers/cloud-platforms/aws.ts#L23

I've created PR's that fix the issue:
- https://github.com/api3dao/airnode/pull/1580
- https://github.com/api3dao/airnode/pull/1582

**Comment by martinkolenic** [comment]
Hi @Siegrift, I'm not sure how to test this specific case, could you please advise? I understand I'd need a faulty provider but where to find/mock one?

**Comment by amarthadan** [comment]
@metobom You can use the v0.9.2 snapshot packages/Docker images to test it.
https://github.com/api3dao/airnode/issues/1588

**Comment by martinkolenic** [comment]
Hi @Siegrift, I've tested the issue.

Steps: Deploy Airnode with a faulty provider URL (a Beeceptor URL with a 1000s delay before a response)
Expected result: Coordinator keeps functioning but displays an error message
Actual result: Matches expected result

![Image](https://user-images.githubusercontent.com/884979/206211747-eae3de6a-3987-43cd-ade8-c87bddb23901.png)

**Comment by Siegrift** [comment]
> @metobom is periodically trying to reproduce the issue using 0.9.1 and the problematic provider. When he does, he will check if 0.9.2 still causes the same issue. Maybe skip testing this one.

@bbenligiray Just to clarify, I asked Martin to test this on master and leave the 0.9.2 for @metobom. Thanks @martinkolenic, this can be moved to DONE.
