### ISSUE TITLE
Deploy protocol contracts on new chains

### ISSUE THREAD

**Issue by Ashar2shahid** [api3dao/airnode#1626]
Deploy protocol contracts on the following chains:

- boba-ethereum
- boba-avalanche
- boba-bnb
- boba-moonbeam
- arbitrum-nova
- sx-network
- sx-network-testnet
- aurora 
- aurora-testnet
- godwoken 
- godwoken-testnet

Use deterministic deployment whenever possible

**Comment by aTeoke** [comment]
documentation task here [#1175](https://github.com/api3dao/api3-docs/issues/1175)
