### ISSUE TITLE
Update gnosis-testnet and metis-testnet integrations

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1628]
New gnosis-testnet chain ID: 10200 (https://docs.gnosischain.com/about/networks/chiado/)
New metis-testnet chain ID: 599 (https://docs.metis.io/dev/get-started/metis-connection-details)

**Comment by dcroote** [comment]
Closing as complete. The transition to using @api3/chains in https://github.com/api3dao/airnode/pull/1739 changed `gnosis-testnet` chain ID 77 to 10200 and changed `metis-testnet` with chain ID 588 to `metis-goerli-testnet` with chain ID 599.
