### ISSUE TITLE
Verify protocol contracts on block explorers

### ISSUE THREAD

**Issue by Ashar2shahid** [api3dao/airnode#1630]
The following chains do not have the protocol contracts verified on their block-explorers due to technical issues (block explorer being decommissioned, verification api failing etc). When the issues are resolved, the contracts have to verified on the explorer

- [x] [aurora](https://explorer.mainnet.aurora.dev/)
- [ ] [aurora-testnet](https://explorer.testnet.aurora.dev/)
- [ ] [sx](https://explorer.sx.technology/)
- [ ] [sx-testnet](https://explorer.toronto.sx.technology/)
- [ ] [godwoken-testnet](https://gw-explorer.nervosdao.community/)

**aurora** and **aurora-testnet**:
Etherscan discontinued from 1st Feb. They are migrating to blockscout but their blockscout doesn't support verification at the moment.

**sx-network** and **sx-network-testnet**:
Not sure why verification is failing, have to check with their team

**godwoken-testnet**:
Not sure why verification is failing, have to check with their team

**Comment by bbenligiray** [comment]
Note to @aTeoke, this is blocked externally so don't add it to milestones

**Comment by bbenligiray** [comment]
Our current protocol is that if the contract verification API of the main block explorer of a chain doesn't work, we don't verify. These are documented to a degree on the https://github.com/api3dao/chains README.

**Comment by dcroote** [comment]
Does our opinion change if we're unable to verify via the API, but are able to via the web interface? Example: I was just able to verify AirnodeRrpV0 on Aurora: https://explorer.mainnet.aurora.dev/address/0xE338f63170c42bA0d2a888f18F6185369779009c/contracts#address-tabs

**Comment by bbenligiray** [comment]
The graphical interface works in a lot of cases where the API doesn't. However, that creates so much additional workload that we can't feasibly do this for all chains (or we can, but I'd rather we didn't).

**Comment by dcroote** [comment]
I played just a couple of minutes more on web interfaces- the aurora-testnet verification hung endlessly and the sx compiler dropdown was broken (there just weren't any compiler options), so yeah, I agree.

**Comment by bbenligiray** [comment]
I guess this means that this issues can be closed

As a note, I want to [check if a block explorer API is working at @api3/chains](https://github.com/api3dao/chains/issues/91) (and omit the API info if it doesn't work) so the deployment script here automatically knows if we need verification or not
