### ISSUE TITLE
No airnode-examples integration with both gateways enabled

### ISSUE THREAD

**Issue by dcroote** [api3dao/airnode#1635]
## Description

There is currently no `airnode-examples` integration that has both the HTTP gateway and signed HTTP gateway enabled. This makes [testing more difficult](https://github.com/api3dao/airnode/issues/1633#issuecomment-1418322152) and forces the user to repeat the deployment process twice or manually edit the config file if they want to test both gateways.

## Suggested fix

Combine the `coingecko-testable` and `coingecko-signed-data` integrations into a single `coingecko-gateways` integration.

**Comment by aTeoke** [comment]
HHTP gateway worked ok

HTTP signed data gateway I got an error: {"message": "Invalid request body"} using curl
request: 
curl -X POST -H 'Content-Type: application/json' -d '{"encodedParameters": "0x3173000000000000000000000000000000000000000000000000000000000000636f696e49640000000000000000000000000000000000000000000000000000657468657265756d000000000000000000000000000000000000000000000000"}' 'https://zgdh35zfb0.execute-api.us-east-1.amazonaws.com/v1/7041ca12-0671-2608-f7ca-57c7fd526f4f/0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4'


where could be the issue?

**Comment by dcroote** [comment]
Can you describe how you set up the test and deployed the airnode?

I ran `yarn choose-integration`, selected `coingecko-http-gateways` then:
```sh
yarn create-airnode-config && yarn create-airnode-secrets
```
Then deployed to AWS using the `airnode-deployer-dev` image corresponding to the current master commit: 
```sh
yarn deploy-airnode api3/airnode-deployer-dev:e1746a1d123809fb09edd9e24e307c910731f7b6
```

Both an HTTP gateway curl request and an HTTP signed data gateway curl request worked for me.

**Comment by aTeoke** [comment]
tried to redeploy the airnode and it suddenly worked - not sure what was the problem since I used the same hash. But working on GCP and AWS as well.
