### ISSUE TITLE
v0.9.2 docker images fail(ed) to build

### ISSUE THREAD

**Issue by dcroote** [api3dao/airnode#1636]
## Description

Locally using WSL2 and also in our CI, the v0.9.2 image(s) fail(ed) to build. I noticed this when trying to assist a user in generating a custom Airnode deployer docker image based on the v0.9.2 release (see [my branch here](https://github.com/api3dao/airnode/tree/dcroote/v0.9-discord-user-mod-do-not-merge)). The idea was for me to make the quick change and let our CI build the deployer image for the user given they were on Windows and we don't support building Docker images on Windows (it fails, they tried).

In looking back, the v0.9.2 release [commit](https://github.com/api3dao/airnode/commit/173b69a5c1ab6e68acfd1cb47a6687fc5591635b) CI run step that builds the docker images [actually failed](https://github.com/api3dao/airnode/actions/runs/3655405979/jobs/6176726963). Note that while the failing step appears to be "Push airnode-admin to Docker Hub", the build step before it actually failed. Interestingly the [commit before the merge commit](https://github.com/api3dao/airnode/commit/c9e8f7dfe7bcb10649e4dc71016319adbd8513b5) succeeded in building the images.

This may be in the "won't fix" category as the build process has been reworked a bit in v0.10, but wanted to note this nonetheless.

**Comment by amarthadan** [comment]
I'm pretty sure this is a duplicate of https://github.com/api3dao/airnode/issues/1585.

It's not fixed yet, not even in v0.10, I didn't get to it.

Try adding a changeset to your branch, it should work then. If that's the case, please, close this as a duplicate.

**Comment by dcroote** [comment]
Thanks @amarthadan. Closing as duplicate. Notably, though, an [empty changeset](https://github.com/api3dao/airnode/commit/b516a06f529a204ea4d668bff3875fc05962ffba) still results in failure of the images to build- a changeset needs to [affect a package](https://github.com/api3dao/airnode/commit/117daca77c66866b6c067c61700e38df6371abff) in order to succeed.
