### ISSUE TITLE
`update-config-fixtures.ts` script formats output differently than Prettier

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1638]
I run into this during the v0.10.0 release
https://github.com/api3dao/airnode/pull/1637/files#diff-3317278434633fa1c9c58606616c717e25638b589a62d7ad79de68c2b98e2c77

**Comment by Siegrift** [comment]
We can execute prettier programatically just on those affected files. That should fix the issue.

**Comment by dcroote** [comment]
@aTeoke - if you'd like to test this one what you can do is pull the latest `master` branch and run `npx ts-node scripts/update-config-fixtures.ts` from the root Airnode directory and confirm there are no changed files (because otherwise it would indicate that the script changes formatting).

**Comment by aTeoke** [comment]
![Image](https://user-images.githubusercontent.com/82645914/220896451-ae3da5bd-4664-4961-9eca-7c3b94736953.png)

seem ok?

**Comment by dcroote** [comment]
Yes perfect
