### ISSUE TITLE
Fix `airnode-node` tests breaking on package version update

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1641]
This happened during [the v0.10.0 release](https://github.com/api3dao/airnode/actions/runs/4105569837/jobs/7092296880) and was temporarily fixed by [updating the fixtures](https://github.com/api3dao/airnode/pull/1640). This needs to be fixed permanently so it won't break for every new release.

**Comment by dcroote** [comment]
@aTeoke - no testing needed for this one as it is strictly related to the test suite. Moving to done.
