### ISSUE TITLE
Include the deployment_id in the heartbeat payload

### ISSUE THREAD

**Issue by aTeoke** [api3dao/airnode#1649]
This is requested by ChainAPI to improve the UX of removing the deployed Airnode. Command `airnode-deployer remove-with-deployment-details` no longer exists. It was replaced by a command `airnode-deployer remove <deployment ID>` in Airnode 0.10. ChainAPI needs to obtain the deployment_id in order to suggest the new command to the user via their UI

**Comment by aTeoke** [comment]
tested aws - worked deployment_id:	awsd9f43605
tested gcp - worked deployment_id:	gcpd42e2555

![Image](https://user-images.githubusercontent.com/82645914/227216700-211572d7-d438-4a97-b73f-35f75d90e80e.png)
![Image](https://user-images.githubusercontent.com/82645914/227216701-7250964f-3075-480f-832c-bc58dca9ce81.png)

and matching the deployment_id generated via list command

**Comment by dcroote** [comment]
Great, thanks
