### ISSUE TITLE
Add retries to performApiCall

### ISSUE THREAD

**Issue by aTeoke** [api3dao/airnode#1658]
We want to add 2 retries for the [Airnode API call](https://github.com/api3dao/airnode/blob/e4d3bee6e70bc733f4d95245fa320753d4204061/packages/airnode-node/src/api/index.ts#L200-L219). First retry should take 10s, second should take 20s. Since the [function](https://www.npmjs.com/package/@api3/promise-utils) is not configurable to have differently timed timeouts, we must have 2 different retries.

Requirements

- 1st retry - 10s timeout
- 2nd retry - 20s timeout

**Comment by bbenligiray** [comment]
@bdrhn9 mentioned a concern that @aquarat agreed with but I didn't understand the significance

**Comment by bdrhn9** [comment]
[Here](https://github.com/api3dao/airnode/blob/e4d3bee6e70bc733f4d95245fa320753d4204061/packages/airnode-node/src/api/index.ts#L206), 
```typescript
const goRes = await go(() => adapter.buildAndExecuteRequest(options, { timeout }), {
    totalTimeoutMs: timeout,
  });
```
I think, we need to pass same timeout for both adapter and promise-utils. Because timeout passed to adapter is actually passed to axios. If timeout passed to adapter (axios) is higher than the one to promise-utils, opened axios socket can hang until timeout for adapter is exceeded. Because AWS Lambda has limited number of file-descriptor, it'd be better take this consideration.

**Comment by Ashar2shahid** [comment]
> [Here](https://github.com/api3dao/airnode/blob/e4d3bee6e70bc733f4d95245fa320753d4204061/packages/airnode-node/src/api/index.ts#L206), I think we need to pass same timeout for both adapter and promise-utils. Because timeout passed to adapter is actually passed to axios. If timeout passed to adapter (axios) is higher than the one to promise-utils, opened axios socket can hang until timeout for adapter is exceeded. Because AWS Lambda has limited number of file-descriptor, it'd be better take this consideration.
> 
> ```ts
> const goRes = await go(() => adapter.buildAndExecuteRequest(options, { timeout }), {
>     totalTimeoutMs: timeout,
>   });
> ```

if both the same `totalTimeout`, it shouldn't be an issue right?

**Comment by Ashar2shahid** [comment]
there is a way to do the different timeout retries via multiple `go()` calls but I decided it would be better to add this functionality to promise-utils here: https://github.com/api3dao/promise-utils/pull/92 . Once that is merged we can have retries with custom timeouts

**Comment by aTeoke** [comment]
Since we are changing the function do we want the end user to have the possibility to configure it themselves? Is there a scenario where this would be useful?

**Comment by bdrhn9** [comment]
> > [Here](https://github.com/api3dao/airnode/blob/e4d3bee6e70bc733f4d95245fa320753d4204061/packages/airnode-node/src/api/index.ts#L206), I think we need to pass same timeout for both adapter and promise-utils. Because timeout passed to adapter is actually passed to axios. If timeout passed to adapter (axios) is higher than the one to promise-utils, opened axios socket can hang until timeout for adapter is exceeded. Because AWS Lambda has limited number of file-descriptor, it'd be better take this consideration.
> > ```ts
> > const goRes = await go(() => adapter.buildAndExecuteRequest(options, { timeout }), {
> >     totalTimeoutMs: timeout,
> >   });
> > ```
> 
> if both have the same `totalTimeout` (i.e timeout across all attempts), it shouldn't be an issue right?

Yea, it looks okay 👍🏼
