### ISSUE TITLE
Ensure beacon set ID is derived from ordered beacons in OEV gateway

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#1690]
Beacon order is important when deriving a beacon set ID. The gateway receives beacons record and needs to order the beacons before deriving the beacon set ID.

Either sort the beacons, or make the order be provided via the request. If this ends up changing the request body/response do not forget to update relevant documentations.

**Comment by bbenligiray** [comment]
I wouldn't enforce this to be consistent with the contract implementation
