### ISSUE TITLE
airnode-validator allows duplicate provider names in chains[n].providers

### ISSUE THREAD

**Issue by dcroote** [api3dao/airnode#1709]
## Version

master

## Present Behaviour

A `config.json` with duplicate `chains[n]` provider names is valid.

## Expected Behaviour

I think this should be disallowed by `airnode-validator` because of how the provider URL is fetched using the name in `buildEVMState`, and to avoid confusion within logs.

https://github.com/api3dao/airnode/blob/ad642715afcfb9fe690239ce5f3e0482a4b289fb/packages/airnode-node/src/providers/state.ts#L11-L19

## Steps to reproduce

Run `airnode-validator`, e.g. its CLI, against a `config.json` with duplicated `chains[n].providers`, for example:
```json
      "providers": {
        "exampleProvider": {
          "url": "${PROVIDER_URL}"
        },
        "exampleProvider": {
          "url": "${PROVIDER_URL2}"
        }
      },
```
(and also update the `secrets.env` to have both url variables for interpolation).

**Comment by dcroote** [comment]
Closing as new duplicate keys overwrite old ones when JSON is parsed upstream of any validation. Consequently it's not worth checking for this rather silly and unlikely error.
```ts
const p = JSON.parse(`{
  "providers": {
    "provider1": "text",
    "provider1": "new"
  }
}`);
console.log(p);
```

Output:
```
{ providers: { provider1: 'new' } }
```

**Comment by bbenligiray** [comment]
Interesting that `JSON.parse()` doesn't mind this
