### ISSUE TITLE
Update the @api3/airnode-protocol package to use @api3/chains

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1715]
Currently, to deploy the protocol new contracts on a chain, one needs to add the chain information to https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/credentials.example.json
We now have an @api3/chains that acts as a single source for this kind of information, which is used successfully in https://github.com/api3dao/airnode-protocol-v1/
@api3/airnode-protocol should also use @api3/chains

**Comment by aquarat** [comment]
@cserb indicates this is complete and that does appear to be the case - closing.

**Comment by cserb** [comment]
completed over here: https://github.com/api3dao/airnode/commit/6f4ea71093fc577b505eaabd0cefedab93904865
