### ISSUE TITLE
Make all protocol contract addresses optional

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1717]
See https://api3workspace.slack.com/archives/C02AYRX8D89/p1680603934257579

Currently, the user needs to enter all protocol contract addresses in the config file. This is awkward because @api3/airnode-protocol already knows what these addresses are, and there is no realistic use-case that requires the user to specify these themselves. Therefore, we should make these optional, and default to our deployments of the protocol contract addresses when they are left unspecified.

**Comment by dcroote** [comment]
In `airnode-validator` it is trivial to make the contracts optional, but rather than just do this, what about importing `airnode-protocol` and confirming that the `id` of the chain for which a contract is optional has the contract deployed for it?

The user story would be that FancyNewChain just launched and we have not deployed contracts on it (or won't) and the user omits the contract address. The config would pass validation but then the Airnode would fail without this check.


> there is no realistic use-case that requires the user to specify these themselves

Local hardhat deployments require deploying the AirnodeRrpV0 contract and saving the address, which is done through the `yarn deploy-rrp` step of `airnode-examples`.

**Comment by bbenligiray** [comment]
> In airnode-validator it is trivial to make the contracts optional, but rather than just do this, what about importing airnode-protocol and confirming that the id of the chain for which a contract is optional has the contract deployed for it?

That's definitely how we should do it

> Local hardhat deployments require deploying the AirnodeRrpV0 contract and saving the address, which is done through the yarn deploy-rrp step of airnode-examples.

I guess I meant non-Airnode developer when I said user

**Comment by bbenligiray** [comment]
@andreogle ChainAPI should probably stop providing contract addresses after this goes live

**Comment by aTeoke** [comment]
tested it multiple times, already wrote to Derek last week, but putting here for visibility as well: 
Tested coingecko example
- deleted contracts object and it worked as expected both via AWS and GCP

Tested coingecko-cross-chain-authorizers example
- I was able to deploy to AWS, but request got timed out. 

here is the JSON:
`{
  "chains": [
    {
      "maxConcurrency": 100,
      "authorizers": {
        "requesterEndpointAuthorizers": ["0xc7416D8694D7ab2461A4829fA47494f5eFBeD6Bc"],
        "crossChainRequesterAuthorizers": [
          {
            "requesterEndpointAuthorizers": ["0x61c7e8d7FbdEEC2CDbD3AAE9e60a6eCb8D74E8D1"],
            "chainType": "evm",
            "chainId": "5",
            "chainProvider": {
              "url": "${CROSS_CHAIN_PROVIDER_URL}"
            }
          }
        ],
        "requesterAuthorizersWithErc721": [],
        "crossChainRequesterAuthorizersWithErc721": []
      },
      "authorizations": {
        "requesterEndpointAuthorizations": {}
      },
      "id": "11155111",
      "providers": {
        "exampleProvider": {
          "url": "${PROVIDER_URL}"
        }
      },
      "type": "evm",
      "options": {
        "fulfillmentGasLimit": 500000,
        "gasPriceOracle": [
          {
            "gasPriceStrategy": "latestBlockPercentileGasPrice",
            "percentile": 60,
            "minTransactionCount": 20,
            "pastToCompareInBlocks": 20,
            "maxDeviationMultiplier": 2
          },
          {
            "gasPriceStrategy": "providerRecommendedGasPrice",
            "recommendedGasPriceMultiplier": 1.2
          },
          {
            "gasPriceStrategy": "constantGasPrice",
            "gasPrice": {
              "value": 10,
              "unit": "gwei"
            }
          }
        ]
      }
    }
  ],
  "nodeSettings": {
    "cloudProvider": {
      "type": "aws",
      "region": "us-east-1",
      "disableConcurrencyReservations": true
    },
    "airnodeWalletMnemonic": "${AIRNODE_WALLET_MNEMONIC}",
    "heartbeat": {
      "enabled": false
    },
    "httpGateway": {
      "enabled": false
    },
    "httpSignedDataGateway": {
      "enabled": false
    },
    "oevGateway": {
      "enabled": false
    },
    "logFormat": "plain",
    "logLevel": "DEBUG",
    "nodeVersion": "0.11.0",
    "stage": "dev"
  },
  "triggers": {
    "rrp": [
      {
        "endpointId": "0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4",
        "oisTitle": "CoinGecko basic request",
        "endpointName": "coinMarketData",
        "cacheResponses": false
      }
    ],
    "http": [],
    "httpSignedData": []
  },
  "templates": [],
  "ois": [
    {
      "oisFormat": "2.0.0",
      "title": "CoinGecko basic request",
      "version": "1.0.0",
      "apiSpecifications": {
        "servers": [
          {
            "url": "https://api.coingecko.com/api/v3"
          }
        ],
        "paths": {
          "/coins/{id}": {
            "get": {
              "parameters": [
                {
                  "in": "path",
                  "name": "id"
                },
                {
                  "in": "query",
                  "name": "localization"
                },
                {
                  "in": "query",
                  "name": "tickers"
                },
                {
                  "in": "query",
                  "name": "market_data"
                },
                {
                  "in": "query",
                  "name": "community_data"
                },
                {
                  "in": "query",
                  "name": "developer_data"
                },
                {
                  "in": "query",
                  "name": "sparkline"
                }
              ]
            }
          }
        },
        "components": {
          "securitySchemes": {}
        },
        "security": {}
      },
      "endpoints": [
        {
          "name": "coinMarketData",
          "operation": {
            "method": "get",
            "path": "/coins/{id}"
          },
          "fixedOperationParameters": [
            {
              "operationParameter": {
                "in": "query",
                "name": "localization"
              },
              "value": "false"
            },
            {
              "operationParameter": {
                "in": "query",
                "name": "tickers"
              },
              "value": "false"
            },
            {
              "operationParameter": {
                "in": "query",
                "name": "market_data"
              },
              "value": "true"
            },
            {
              "operationParameter": {
                "in": "query",
                "name": "community_data"
              },
              "value": "false"
            },
            {
              "operationParameter": {
                "in": "query",
                "name": "developer_data"
              },
              "value": "false"
            },
            {
              "operationParameter": {
                "in": "query",
                "name": "sparkline"
              },
              "value": "false"
            }
          ],
          "reservedParameters": [
            {
              "name": "_type",
              "fixed": "int256"
            },
            {
              "name": "_path",
              "fixed": "market_data.current_price.usd"
            },
            {
              "name": "_times",
              "fixed": "1000000"
            }
          ],
          "parameters": [
            {
              "name": "coinId",
              "operationParameter": {
                "in": "path",
                "name": "id"
              }
            }
          ]
        }
      ]
    }
  ],
  "apiCredentials": []
}`

Attaching errors for lambda run and start coordinator @dcroote could you please take a look? Thanks!


![Image](https://github.com/api3dao/airnode/assets/82645914/58353c9c-0897-427e-af2c-10fb7311e187)
![Image](https://github.com/api3dao/airnode/assets/82645914/0f0f1a3c-f344-4133-be26-8730bb6fd903)

**Comment by dcroote** [comment]
I think there may be a bug here that has to do with loading a trusted config that is missing the default address, which would explain the error I've been able to reproduce. This could happen because we validate the config, but then don't "save" the updated, validated config and instead assume it valid after passing validation (where we provide the default address).
```ts
[2023-06-06 06:58:03.280] ERROR TypeError: Cannot read properties of undefined (reading 'AirnodeRrp')
    at fetchPendingRequests (/usr/local/share/.config/yarn/global/node_modules/@api3/airnode-node/dist/src/evm/handlers/fetch-pending-requests.js:35:34)
    at /usr/local/share/.config/yarn/global/node_modules/@api3/airnode-node/dist/src/evm/handlers/initialize-provider.js:154:117
    at /usr/local/share/.config/yarn/global/node_modules/@api3/promise-utils/build/cjs/index.js:100:47
    at Generator.next (<anonymous>)
    at /usr/local/share/.config/yarn/global/node_modules/@api3/promise-utils/build/cjs/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/share/.config/yarn/global/node_modules/@api3/promise-utils/build/cjs/index.js:4:12)
    at attempt (/usr/local/share/.config/yarn/global/node_modules/@api3/promise-utils/build/cjs/index.js:95:43)
    at /usr/local/share/.config/yarn/global/node_modules/@api3/promise-utils/build/cjs/index.js:117:16
    at Generator.next (<anonymous>) Coordinator-ID:cefe8ef5adcec9de, Chain-ID:11155111, Provider:exampleProvider
```

**Comment by aTeoke** [comment]
@dcroote so what is the fix here please? Or is it just an issue with our examples? not sure if I understand what do you mean.

**Comment by aTeoke** [comment]
The fix for the bug is tracked here: [Default contract addresses are not present after validation](https://github.com/api3dao/airnode/issues/1809)

**Comment by dcroote** [comment]
@aTeoke - although I've tested the merged fix as described [here](https://github.com/api3dao/airnode/pull/1814#issuecomment-1608653138), I think you should independently confirm it's working

**Comment by aTeoke** [comment]
sorry it took so long, but tested it again with the same scenarios as above, seems to be working properly. nice!
