### ISSUE TITLE
Airnode attempts to fulfil the same requests multiple times every now and then

### ISSUE THREAD

**Issue by aTeoke** [api3dao/airnode#1718]
## Description

When having 2 providers Airnode doesn't get VM exception / static call errors / nonce errors and sends fulfillment transactions thinking they will succeed and they revert on-chain

## Version
Airnode 0.10 and up

Discussion here: https://api3workspace.slack.com/archives/C02AYRX8D89/p1680274185877999

**Comment by bdrhn9** [comment]
I suspect that using both `Skipping API call` and `cacheResponses` features at the same time can cause this issue.

**Comment by Siegrift** [comment]
Waiting until we agree internally on the resolution.
