### ISSUE TITLE
airnode-node depends on `networks` in `references.json` exported by airnode-protocol

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1741]
airnode-protocol generates `references.json` using `scripts/generate-references.ts` and exports it. `references.json` has the fields `chainNames` and `networks`. These should be removed in favor of values exported by `@api3/chains`. This can't be done at the moment because airnode-node depends on it.

**Comment by dcroote** [comment]
The docs also depend on the exported `references.json` within a script that generates JSON files containing various contract addresses:

https://github.com/api3dao/vitepress-docs/blob/f0af6e73cd767ab98ac53f23ce231c6d20fefb94/libs/axiosBuildScripts.js#L117-L123

**Comment by bbenligiray** [comment]
So the issue is that `references.json` should only be depended on for contract addresses so that usage is not a problem. airnode-node depends on it to get chain aliases (to use in logging IIRC). The actual source of truth for that information is now @api3/chains.

**Comment by dcroote** [comment]
With this completed I think we can consider removing `chainNames` and `networks` from [references.json](https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/deployments/references.json)
