### ISSUE TITLE
Is it suitable to deploy RrpRequesterV0.sol on my own?

### ISSUE THREAD

**Issue by jiguantong** [api3dao/airnode#1792]
I want to test my airnode on my chain, but I see in the documentation about ["Making an RRP Request"](https://docs.api3.org/guides/airnode/rrp-request.html) that I need to use airnodeRrpAddress, and this contract doesn't exist on my chain. Can I deploy this contract by myself to call my airnode on my chain?

**Comment by bbenligiray** [comment]
Hi, here are the instructions to deploy the protocol contract
- Clone https://github.com/api3dao/airnode
- Run `yarn run bootstrap && yarn run build`
- Go to `packages/airnode-protocol/`
- Create a `.env` file similar to https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/example.env
- Fill in `MNEMONIC` in your `.env` file
- Modify `hardhat.config.js` to include your chain
- Run [`deploy:deterministic`](https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/package.json#L19) with your chain

Once AirnodeRrpV0 is deployed, you can use it's address in your Airnode config and requester contracts

**Comment by jiguantong** [comment]
Thanks! Your team is really excellent.
Let me try it.
