### ISSUE TITLE
Add opBNB (Binance Smart Chain L2)

### ISSUE THREAD

**Issue by EthanBlockson** [api3dao/airnode#1815]
1) [Introducing opBNB](https://www.bnbchain.org/en/blog/introducing-opbnb-unleashing-a-new-era-of-scalability/): Unleashing a New Era of Scalability

2) Will Quintessence and [QRNG providers](https://docs.api3.org/reference/qrng/chains.html) will support opBNB?

**Comment by EthanBlockson** [comment]
> Hi @EthanBlockson we will be looking at additional QRNG deployments later in the year. Do you have a requirement for RNG on the network?

opBNB will be main L2 of Binance Chain, so it will be perfect to have QRNG in onBNB, with the same config set as Arbitrum, or any other current EVM network.

**Comment by bbenligiray** [comment]
@KenCarvAPI any updates regarding where I can transfer this issue? Otherwise I'll close it because we're not taking RRP integration requests.

**Comment by KenCarvAPI** [comment]
Sharing a space in the ecosystem github that request can be directed to.

Also speaking with BNB team re potential deployment to opBNB for price so
could consider this actioned.

**Comment by bbenligiray** [comment]
Seems to be done in https://github.com/api3dao/airnode/pull/2000
