### ISSUE TITLE
Docker image build step is broken

### ISSUE THREAD

**Issue by dcroote** [api3dao/airnode#1843]
The CI in several current PRs is failing on the Docker build step e.g. [here](https://github.com/api3dao/airnode/actions/runs/5655996208/job/15322293737#step:7:53), with errors like the following:
```
error Couldn't find any versions for "@api3/airnode-admin" that matches "snapshot-e62c3fe05ad66062458d892f3a099df5a8bd1555"
```

Likely introduced by #1840 as the same error first appears there.

**Comment by amarthadan** [comment]
That's most likely caused by https://github.com/api3dao/airnode/issues/1585

**Comment by dcroote** [comment]
> That's most likely caused by #1585

I'm not so sure. Renovate PRs that were passing are now failing. Specifically, PRs that were opened and passing before #1840 are now failing

**Comment by amarthadan** [comment]
That still checks out. I did that right before releasing and release cleared the changelogs. The PRs then automatically rebased and can't build the Docker images anymore.

**Comment by dcroote** [comment]
Indeed a duplicate of #1585. My misunderstanding originated from there being *no* changesets at all following a release as the cause of this.
