### ISSUE TITLE
Have the non-signed HTTP gateway response schema be consistent

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1845]
Currently, the non-signed HTTP gateway attempts to encode the result and returns the following schema if successful
```
{
  "encodedValue": "...",
  "values": [...],
  "rawValue": {...}
}
```
If the encoding is not successful, it instead returns the `rawValue` from above as the body. This is not nice because it causes the response schema to be dependent on a condition that can only be determined at runtime, which means the caller can't know what schema to expect as the response.

Two alternative solutions:

1. Return only the post-processed API response in the body

Assuming that `encodedValue` and `values` won't be needed, just get rid of them and have the response body be the post-processed API response.

2. Fix the schema for the case that the encoding fails

Assuming that `encodedValue` and `values` are useful and we want to keep them around, the following response schema should be used if encoding fails 

```
{
  "rawValue": {...}
}
```

As a note, unlike Solution 1, this keeps the `rawValue` name, which is misleading. This is not the raw response of the API, but rather the response that is post-processed by the Airnode. So if Solution 2 will be implemented, this field should be renamed to something more accurate, such as `postProcessedResponse`/`postProcessedBody`/`postProcessedValue`.

**Comment by dcroote** [comment]
I rather strongly favor option 2. If one makes a valid request, I think the gateway should return the response [extracted according to the reserved parameters](https://github.com/api3dao/airnode/blob/fc287d3d5691dbf00f2b03e26a515a8e9dc429a2/packages/airnode-node/src/api/index.ts#L230-L236) i.e. `values`. Returning only `rawValue` wouldn't allow for one to understand if reserved parameters have been set correctly.  I see having the `encodedValue` as an additional minor benefit for prototyping expected responses of the signed HTTP gateway.
