### ISSUE TITLE
Wrong API call parameters don't fulfill with an error code

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#185]
This is not certain and needs to be tested. Conveying the reported bug:

Say we have an endpoint with parameters `startDate` and `endDate`. We're making a request to this endpoint with only the parameter `coinId`. The node doesn't respond with an error code.

**Comment by andreogle** [comment]
Will check this out. Do we know what API? You can message me directly if you want

**Comment by bbenligiray** [comment]
The parameters weren't required, so it shouldn't have returned an error code anyway. I was also told that it didn't respond either, but I doubt that without further information.
