### ISSUE TITLE
Capture Airnode gateway URLs programmatically

### ISSUE THREAD

**Issue by dcroote** [api3dao/airnode#1911]
Gateway URLs are printed to the console at the end of a cloud deployment as [described in the docs here](https://docs.api3.org/reference/airnode/latest/understand/http-gateways.html#when-deployed-on-a-cloud-provider). The URLs aren't easily retrievable otherwise.

To facilitate #1858, #1904, and #1786 (because airnode-client is used in gateway E2E tests) there should be a helper function to capture these URLs.

**Comment by bbenligiray** [comment]
I suppose it wouldn't be easy to mock a heartbeat server for this

**Comment by dcroote** [comment]
The heartbeat is an interesting thought. It turns out it was pretty easy to do in #1904 with a simple regex against the deployment command output logged to the console:

https://github.com/api3dao/airnode/blob/3a05d77936a1dacd8c5990f1edf44d7233e814b1/scripts/test-release.ts#L59-L74

**Comment by dcroote** [comment]
Closing as the regexs work well
