### ISSUE TITLE
Ensure API call can be skipped using Airnode validator

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#1915]
[This check](https://github.com/api3dao/airnode/blob/02d15254dfc431b4c0aa06b36f64953c550849fd/packages/airnode-node/src/api/index.ts#L312C1-L312C1) should be performed in Airnode validator so the user is presented with the error at deploy time (instead of at runtime).

**Comment by dcroote** [comment]
This makes sense 👍

**Comment by dcroote** [comment]
Actually I think our Airnode runtime validation is redundant because we have this validation in `@api3/ois`, here are the tests:

https://github.com/api3dao/ois/blob/7a4b59edfc178fb49e93b48fc7c46b6c276c9a23/src/ois.test.ts#L600-L633

**Comment by Siegrift** [comment]
Oh, I missed that. I will need to edit the check in https://github.com/api3dao/airnode/pull/1914 though. Thanks for noticing.
