### ISSUE TITLE
Remove `chainNames` and `networks` from `references.json`

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1926]
The [`generate-references` script](https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/scripts/generate-references.ts) in `airnode-protocol` adds two redundant fields to `references.json`, `chainNames` and `networks`. `airnode-node` used to depend on this but [this was fixed recently](https://github.com/api3dao/airnode/issues/1741#issuecomment-1867645851), and from what I can see, the old docs (https://github.com/api3dao/api3-docs/blob/57c56b8f6b0c096af91580f4e90e7476683d3083/docs/.vuepress/components/airnode/ContractAddresses.vue#L92) and the new docs (https://github.com/api3dao/vitepress-docs/blob/1e357c0bccdd2fc91f0cce6d2fbafaf53934317c/libs/axiosBuildScripts.js#L28) still depend on this even though they don't need it because they have access to `@api3/chains`.

@wkande please remove all dependency to `chainNames` and `networks` in `references.json` (both for `airnode-protocol` and `airnode-protocol-v1`) in all documentation that is currently live (including versions that are only supported by the old docs) and update this issue, after which we will remove these fields

**Comment by dcroote** [comment]
Docs issues:
- [ ] https://github.com/api3dao/vitepress-docs/issues/687
- [ ] https://github.com/api3dao/api3-docs/issues/1242

**Comment by wkande** [comment]
@dcroote See PR **[688](https://github.com/api3dao/vitepress-docs/pull/688)** for the changes to `vitepress-docs`.
