### ISSUE TITLE
Update validate command

### ISSUE THREAD

**Issue by Drgy** [api3dao/airnode#196]
Add more validate commands that don't require validation template, should be something resembling [convert command](https://github.com/api3dao/airnode/blob/converter/packages/validator/README.md#Usage), for example: `validate [format] [specification]`, where `format` can be `APISpecs`, `Endpoints`, `OIS` or `ConfigSecurity`.

In case of OIS and Config & Security validation, read version of the specification and validate with correct template.

**Comment by bbenligiray** [comment]
For reference:
https://github.com/api3dao/airnode/pull/132#pullrequestreview-558912567

**Comment by Drgy** [comment]
Updated in https://github.com/api3dao/airnode/commit/34f85e80327a5d327b30bc5b7f5764334b926470
