### ISSUE TITLE
Update validation templates

### ISSUE THREAD

**Issue by Drgy** [api3dao/airnode#197]
* [x]  API operations in OIS endpoints must match the ones in the API specifications (operation paths & parameters)
* [x] OIS security schemes must match the ones in `security.json`
* [x] Triggers in `config.json` must match the ones in OIS endpoints
* [x] Update server's regular expression according to https://tools.ietf.org/html/rfc3986#appendix-B, as mentioned [here](https://github.com/api3dao/airnode/pull/195#discussion_r578886984)
* [x] `config.triggers.request` in `configSecurity.json` template should not be optional ([reference](https://github.com/api3dao/airnode/pull/195#discussion_r579671835))
* [x] Replace regexps for versions with `^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$` ([reference](https://github.com/api3dao/airnode/pull/195#discussion_r579686086))
* [x] security scheme names should be lower case ([reference](https://github.com/api3dao/airnode/pull/195#discussion_r578922765))

**Comment by bbenligiray** [comment]
For reference:
https://github.com/api3dao/airnode/pull/132#pullrequestreview-558912567
