### ISSUE TITLE
Support MFA for AWS CLI

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#201]
MFA can be enabled for AWS IAM users.
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_enable_virtual.html#enable-virt-mfa-for-iam-user
This requires the user to get a token that expires
https://aws.amazon.com/premiumsupport/knowledge-center/authenticate-mfa-cli/
and put that in their `.env` used during deployment. That will be fed to Terraform/Serverless as an environment variable with the name `AWS_SESSION_TOKEN` 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs#authentication

**Comment by bbenligiray** [comment]
It'll be better to wait for the deployer to reach a stable state for this.

**Comment by amarthadan** [comment]
The new deployer distinguish between cloud provider specific credentials and airnode specific secrets. Exporting any env variables that Terraform (or the underlying AWS library) recognizes is enough. So using MFA with `AWS_SESSION_TOKEN` env variable is no problem (I myself used it during testing). Closing.
