### ISSUE TITLE
Refactor validator readme

### ISSUE THREAD

**Issue by drgy** [api3dao/airnode#203]
Whole [readme](https://github.com/api3dao/airnode/blob/converter/packages/validator/README.md) needs multiple parts updated/rewritten, mainly:

* [x] explanation `__actions` are used by convertor (as mentioned [here](https://github.com/api3dao/airnode/pull/195#discussion_r578039974))
* [x] order of parameters in template is irrelevant except order of items in the `__actions`
* [x] splitting into multiple files might help with readability, quicker access to various topics and draw clearer line between differences of each functionality
* [x] clear definition of terminology (key, value, object, array) and unified use throughout the readme
* [x] rewrite explanation of `__objectItem` and `__arrayItem`
* [x] add more examples and description of `{{X}}`, `[]` and `[_]`
* [x] add example of template converting specification to completely different format
* [x] mention each `\` should be doubled in regular expressions, mention why
* [x] Example of `__any` outside of `__condition`
* [x] Add example of multiple objects in `__optional`

**Comment by bbenligiray** [comment]
Use double spaces instead of tabs in JSON examples
