### ISSUE TITLE
Standardize the .env file used by airnode-client

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#228]
## Description

The client container expects secrets to be provided in a `.env` file. If the contents of this `.env` file are
```sh
ENV_NAME="ENV_VALUE"
```
Docker sets `ENV_NAME` as `"ENV_VALUE"` (and not `ENV_VALUE`). See [this](https://docs.docker.com/compose/env-file/#syntax-rules). 

## Version

The `api3/airnode-client:pre-alpha` image built from the [pre-alpha branch](https://github.com/api3dao/airnode/tree/pre-alpha)

## Present Behaviour

The client container treats quotation marks in `.env` as a part of the environment variable value.

## Expected Behaviour

The client container should omit the quotation marks in `.env`. See [this](https://github.com/motdotla/dotenv#rules).

## Steps to reproduce

Launch airnode-client with a `.env` file with quotation marks. It will fail with `invalid mnemonic` because quotation marks are included in the mnemonic.

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

The easiest way to fix this would be to copy `.env` in the container along with `config.json` and have the node `dotenv` pick it up.

**Comment by bbenligiray** [comment]
Docs should be updated after this: https://github.com/api3dao/airnode/blob/daf3108517386ba424335c3fcfeb57b2338a658f/Docker-client.md

**Comment by Ashar2shahid** [comment]
Can have a look at the PR #243

**Comment by MrAngus666** [comment]
This was included in 243
