### ISSUE TITLE
Expand Github issue templates

### ISSUE THREAD

**Issue by andreogle** [api3dao/airnode#235]
## Description
A basic issue template was added a few weeks ago that prompts the user to capture additional information when logging a bug report. However, we don't only use Github issues for logging bugs so this template doesn't always apply.

[Next.js issues](https://github.com/vercel/next.js/issues/new/choose) has a nice flow for logging an issue (or pointing the user in the right direction). You can select a template and go through a process of filling out a form where certain fields are required.

We should consider adding additional issue templates. I think we should have selectable options for:

1. Bug reports
1. Feature requests
1. Discussions
1. Security Policy (redirects the user)
1. Ask a question (redirects the user. Discord?)

2 & 3 could maybe be combined since they're pretty much the same thing(?). Thoughts?

If this is implemented, we should first test it on a temporary new repo before merging to master

**Comment by bbenligiray** [comment]
I hate issue templates as a user but pointing people towards the Discord after they create the issue would be pretty helpful

**Comment by andreogle** [comment]
Yeah I'm starting to dislike them too actually

**Comment by Siegrift** [comment]
Especially if it's that "boilerplaty" and verbose and even we (api3 devs) don't use it...

I'd just write only the relevant bits. For example, mention our support channels (discord, telegram..) and maybe tell them to distinguish between versions (pre-alpha, 0.1.0...)

**Comment by bbenligiray** [comment]
TRacked by https://api3dao.atlassian.net/browse/CT-12
