### ISSUE TITLE
Improve the node/e2e test setup

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#251]
Improve the test setup directory structure, and potentially how test environment variables are handled.

https://github.com/api3dao/airnode/pull/250#discussion_r599427827
https://github.com/api3dao/airnode/pull/250#discussion_r599418509

**Comment by MrAngus666** [comment]
Adding coverage threshold should be a must #259

**Comment by MrAngus666** [comment]
Include #259 as another improvement

**Comment by bbenligiray** [comment]
Do we close this?

**Comment by andreogle** [comment]
Yeah I think so
