### ISSUE TITLE
Merging pre-alpha PRs into master

### ISSUE THREAD

**Issue by MrAngus666** [api3dao/airnode#254]
## Description
 #222 #228 and #224 are in PR to be merged into pre-alpha, we should merge them into master after bellow PRs are merged into pre-alpha:

https://github.com/api3dao/airnode/pull/253
https://github.com/api3dao/airnode/pull/243

**Comment by bbenligiray** [comment]
The PRs related to `.env` and `HEALTHCHECK` will probably not be relevant for v0.1.0 because the client container will be done from scratch

**Comment by bbenligiray** [comment]
@MrAngus666 Is there any reason why we are not doing these right away?

**Comment by MrAngus666** [comment]
I just know that this issues were done in pre-alpha and I wanted to have them tracked. 

In my opinion we should merge pre-alpha into master ASAP and remove what we don't want in master / 0.1.0

**Comment by bbenligiray** [comment]
I guess this is outdated
