### ISSUE TITLE
Add Unit Test Coverage Thresholds

### ISSUE THREAD

**Issue by MrAngus666** [api3dao/airnode#259]
We should add the current coverage thresholds so future development won't affect the current test coverage we have

 https://jestjs.io/docs/configuration#coveragethreshold-object

Example

```
coverageThreshold: {
  global: {
      statements: 100,
      branches: 97,
      functions: 100,
      lines: 100,
  },

```

**Comment by andreogle** [comment]
Test coverage is a nice metric but it's not really definitive. A codebase can pretty easily have 100% coverage but the tests aren't checking the right things or things are being missed.

I don't think we need to be forcing 100% coverage everywhere

**Comment by MrAngus666** [comment]
I agree that we should not be enforcing a 100%, probably I copied and pasted a bad example. 
In my opinion we can do:
1. Set the current values that we have, so we define a baseline with the current stage.
2. We define a minimums
I think there is more room to improve in the e2e test (cover more scenarios, working on review on that)

**Comment by Siegrift** [comment]
Admin package will probably not need this, because I am adding e2e tests for the CLI package which are better suited then unit tests in this case.

**Comment by bbenligiray** [comment]
Tracked by https://api3dao.atlassian.net/browse/AN-152
