### ISSUE TITLE
API responses can't be cached

### ISSUE THREAD

**Issue by andreogle** [api3dao/airnode#26]
### Description
API calls may or may not be idempotent so the API provider might not want to make duplicate API calls between serverless function invocations while the transaction is pending. The API response needs to be optionally cached. 

The cache should store the following information against the `requestId`:

1. The raw value extracted from `_path` or the error
1. The timestamp
1. The status boolean - either successful or failure.

Cache keys need to have an expiration mechanism too.

Before making an API call, the cache should be checked for the `requestId`. If a value is found, skip making that call and attempt another transaction with that value.

API calls should default to cached if a cache is configured. Otherwise, a new call should be made each serverless invocation.

### Questions
1. How exactly to implement the cache. What AWS service to use etc.
1. When should the cache key be cleared? If a `requestid` exists in the cache, but no unfulfilled request is found?

**Comment by bbenligiray** [comment]
One option we have for this is to call the API through a gateway and let it handle the caching (AWS can go up to an hour)
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-caching.html
The issue here is that how reliable the cache is (because an unexpected cache miss would mean a duplicate API call).

The obvious solution is to use a NoSQL database, cache by `requestId` and expire each item in an hour.

**Comment by MrAngus666** [comment]
An implementation that supports the AWS, Azure and GCP can use the redis services that are provided as a service on the three providers:
https://cloud.google.com/memorystore
https://azure.microsoft.com/en-us/services/cache/#overview
https://aws.amazon.com/elasticache/redis/

We will have code specific for each provider but at the end it is the same core product, redis, using it as as key, value pair.

**Comment by bbenligiray** [comment]
This will be easier to implement if we migrate to bare Terraform, which is currently being worked on

**Comment by bbenligiray** [comment]
We'll probably not support this for the containerized version (at least initially)

**Comment by bbenligiray** [comment]
0.7.0 allows caching in the global scope with no hard guarantees. Closing this issue in line with the changes in how we use Github issues internally.
