### ISSUE TITLE
Add Jest support to ESLint

### ISSUE THREAD

**Issue by andreogle** [api3dao/airnode#262]
We should consider adding https://www.npmjs.com/package/eslint-plugin-jest with some sensible defaults - probably `"extends": ["plugin:jest/recommended"]` as a start.

I wasn't aware of this plugin before

**Comment by MrAngus666** [comment]
Added to #251

**Comment by bbenligiray** [comment]
Do we close this?

**Comment by andreogle** [comment]
I added eslint-plugin-jest here: https://github.com/api3dao/airnode/pull/477 Definitely worth adding it
