### ISSUE TITLE
Consistent output of admin CLI

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#275]
Currently some of the commands use ad-hoc format, e.g.

```js
console.log(`Requester admin: ${requesterAdmin}`);
```

and some output the whole JSON:

```js
console.log(toJSON(parameters));
```

The output of the commands should be consistent and I'd say it's better to avoid ad-hoc format and just display the data. Reasons:
1) It's easier to test - no need to strip the ad-hoc prefix
2) Easier to process if someone uses the CLI in some pipeline - for the same reason as 1)
3) The output of the command has enough context for user to know what is returned - it should be clear even from the command name, but there is also description
4) We can wrap the response from blockchain as JSON in the SDK - e.g. return `{"requesterIndex": "2"}` from the CLI.

We could also introduce something like `--pretty` flag to pretty print json, but I think it's not necessary as users can just format it in code editor or online tool.

**Comment by bbenligiray** [comment]
I know it's not really a bug-fix, but it's closer to that than an enhancement.

**Comment by bbenligiray** [comment]
Tracked by https://api3dao.atlassian.net/browse/AN-151
