### ISSUE TITLE
Allow specifying gas limit/price in admin CLI

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#276]
Allow specifying ethers overrides from the command line and SDK: https://docs.ethers.io/v4/api-contract.html#overrides

**Comment by bbenligiray** [comment]
Would also need to support EIP-1559

**Comment by Siegrift** [comment]
What exactly has to change?

**Comment by bbenligiray** [comment]
See https://docs.ethers.io/v5/api/utils/transactions/
The user can either specify `gasPrice` or `maxFeePerGas` and `maxPriorityFeePerGas`. We can only support `gasPrice` for now and create another issue for this.

**Comment by bbenligiray** [comment]
Tracked by https://api3dao.atlassian.net/browse/AN-149
