### ISSUE TITLE
Remove ad-hoc fixes regarding TypeChain

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#285]
In https://github.com/api3dao/airnode/pull/270 I've integrated https://github.com/ethereum-ts/TypeChain into protocol package.

Unfortunately, there were two minor issues for which there are ad-hoc fixes:
1) Unable to get the ABI of the contract - Will be resolved by https://github.com/ethereum-ts/TypeChain/pull/368
2) https://github.com/ethereum-ts/TypeChain/issues/369

Both issues have workaround in place at the moment.

**Comment by bbenligiray** [comment]
What is the status on this @Siegrift ?

**Comment by Siegrift** [comment]
1. Was blocked by issue in external library, but that is now fixed.
2. Was probably due to mismatched dependency versions and maybe is not a problem anymore.

But it's mostly cleanup task, so we can close this and track it in Jira only.

**Comment by bbenligiray** [comment]
Tracked by https://api3dao.atlassian.net/browse/AN-156
