### ISSUE TITLE
Add examples to admin CLI

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#286]
For now we have examples of commands in README.

It would be nice if they were printed out from the CLI as well. We can use: http://yargs.js.org/docs/#api-reference-examplecmd1-desc1-cmd2-desc2

**Comment by jeebster** [comment]
@Siegrift addressed in #327

**Comment by Siegrift** [comment]
Unfortunately, it is not supported by https://yargs.js.org/docs/ 
See more in: https://github.com/api3dao/airnode/pull/327
