### ISSUE TITLE
Autogenerate admin CLI documentation

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#287]
Currently, the SDK documentation is written by hand, but it can get out of sync with the implementation quite quickly.

This probably makes sense only after (if) https://github.com/api3dao/airnode/issues/286 is implemented.

I'd propose:
1) Auto generating it from the CLI
2) Or how just output from the CLI help command (possibly auto generated). I don't think there is much need for documenting individual commands - especially if there are examples in the CLI.

**Comment by bbenligiray** [comment]
I think we'll need autogenerated docs because the admin package will continue to grow with authorizer interactions

**Comment by bbenligiray** [comment]
Tracked by https://api3dao.atlassian.net/browse/AN-148
