### ISSUE TITLE
Validate OIS title

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#293]
OIS title isn't validated but it should be
https://github.com/api3dao/airnode/blob/c3ffc8daf06f86ee8cc37c3bf46cbeb967b90ae8/packages/validator/templates/ois.json#L5
Waiting on the discussion at ChainAPI to be resolved for what is allowed

**Comment by bbenligiray** [comment]
Title field is at most 32 characters, can only include alphanumeric characters, hyphen, underscore, whitespace
@drgy can you please update the template and @wkande can you add it to OIS docs please?

**Comment by drgy** [comment]
Updated in af5e4eb9da85414e24a99caf878e1b860e890784

**Comment by bbenligiray** [comment]
Actually 32 is too short, let's make this 64

**Comment by wkande** [comment]
Added both to /pre-alpha and /next. See [docs.api3.org/next/reference/specifications/ois.html#_1-oisformat](docs.api3.org/next/reference/specifications/ois.html#_1-oisformat)

From api3-docs issue: #60

----

# 2. `title`

(Required) The OIS title. Title field is at most 64 characters, can only include alphanumeric characters, hyphens, underscores and whitespaces.

OAS equivalent: `info.title`

**Comment by bbenligiray** [comment]
Thanks @wkande !
