### ISSUE TITLE
Simplify checking log (event) type

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#331]
## Description
Currently, inside airnode we fetch all logs and then we filter them by the topic (we check if the event contains a specific topic) and sometimes we just check the event name (mainly in tests).

It seems solidity supports events with same name, but I don't think we will (nor should) use it in airnode. Implementation could create utility functions for this and we should just use a single consistent style.

See also comment: https://github.com/api3dao/airnode/pull/304#discussion_r624689383

**Comment by bbenligiray** [comment]
Should this be closed @Siegrift ?

**Comment by Siegrift** [comment]
I don't think it's worth doing so I'd just close, wdyt?

**Comment by bbenligiray** [comment]
Agreed, closing
