### ISSUE TITLE
Add more infrastructure specific options to deployer

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#343]
https://github.com/api3dao/airnode/pull/333#discussion_r626508755

**Comment by andreogle** [comment]
Also worth considering letting the user specify any throttling/quotas for the testing API

**Comment by bbenligiray** [comment]
Should these be specified in `nodeSettings.cloudProvider` in `config.json`, assuming they will be cloud provider-specific?

**Comment by amarthadan** [comment]
> Should these be specified in `nodeSettings.cloudProvider` in `config.json`, assuming they will be cloud provider-specific?

Yes, that would probably be a good place for them.

**Comment by bbenligiray** [comment]
Tracked by https://api3dao.atlassian.net/browse/AN-145
