### ISSUE TITLE
Extract re-usable utility functions into a new package

### ISSUE THREAD

**Issue by andreogle** [api3dao/airnode#347]
## Description
There are some utility functions (especially promise utilities) that are re-implemented in other projects. It would be nice to extract these into a separate package so that they can use consistent API and implementation. It may also make sense to do this in a new repository.

**Comment by acenolaza** [comment]
@andreogle is the idea to host the new package in a registry like Github Packages?

**Comment by andreogle** [comment]
I'm not sure about Github Packages - I was just thinking about putting it on NPM. It should probably be it's own repo too, since these utlities are not directly related to Airnode.

This is actually becoming more of an issue lately as we are starting more and more projects that re-implement and change the implementations in subtle ways

**Comment by bbenligiray** [comment]
Tracked by https://api3dao.atlassian.net/browse/AN-144
