### ISSUE TITLE
Building Docker container

### ISSUE THREAD

**Issue by joshcaskie** [api3dao/airnode#367]
## Description

Building the docker container for Airnode is giving me errors.

## Version

OS: Windows 10 Pro 64-bit
Docker Desktop: 3.3.1
Node.js version: 12.13.1
Yarn version: 1.22.10
npm: 6.12.1

I'm building from the master branch cloned at [https://github.com/api3dao/airnode.git](url)

## Present Behaviour

I'm attempting to build the Airnode container by following the steps in **airnode/docker/Docker.md**. However, upon running 
`docker build -f docker/Dockerfile -t api3/airnode:latest .` 
I'm getting an error that looks like this:
![image](https://user-images.githubusercontent.com/57299645/120520438-ca881900-c3a1-11eb-9365-32aafe92a446.png)

## Expected Behaviour

I'm assuming that the command should run normally and build the container properly.

## Steps to reproduce

I'm simply cloning the repo, running `yarn run bootstrap` then running `docker build -f docker/Dockerfile -t api3/airnode:latest .`

After doing some troubleshooting, I believe it has something to do with the capitalized names in the Dockerfile as Docker might not like them (buildPrep, buildBuild, buildDependencies). 
![image](https://user-images.githubusercontent.com/57299645/120522956-55b5de80-c3a3-11eb-8adc-e2e6ec79b4e2.png)

I changed them all to fully lowercase variants and the `build` command started to execute, but then I reached another error:
![image](https://user-images.githubusercontent.com/57299645/120522879-4f276700-c3a3-11eb-9a2b-1736ffc42c0f.png)

**Comment by amarthadan** [comment]
Hi @joshcaskie

> After doing some troubleshooting, I believe it has something to do with the capitalized names in the Dockerfile as Docker might not like them (buildPrep, buildBuild, buildDependencies).

I'm guessing this would be a Windows-specific issue. But if changing the image aliases to lowercase works that's an easy fix. I created an issue (https://github.com/api3dao/airnode/issues/369) to track it. Thanks for pointing it out.

 > I changed them all to fully lowercase variants and the build command started to execute, but then I reached another error

Yes, that's an expected behavior at the moment. The Docker image building process was reworked recently and the new version is expecting the packages to be available in the NPM registry which is not yet the case. We're working on releasing them but it will still take some time until we can do that. Also the documentation is outdated as well, we're working on updating it at the moment.

You can still try the deployer CLI, just not via Docker at the moment. You can do the following:
```bash
git clone git@github.com:api3dao/airnode.git
cd airnode
yarn bootstrap
yarn build
cd packages/deployer
cp config/config.json.example config/config.json
cp config/secrets.env.example config/secrets.env
# Edit config/config.json and config/secrets.env
yarn cli
```

You also need to have Terraform installed and AWS credentials exported/stored in a configuration file before running the CLI.

If you have any more questions or need help don't hesitate to ask :slightly_smiling_face:

**Comment by joshcaskie** [comment]
Thanks! I'm also wondering how this might apply to the [airnode-starter](https://github.com/api3dao/airnode-starter) repo? I started with that Readme but moved here to debug when things didn't work.

**Comment by amarthadan** [comment]
Airnode-starter references a [`pre-alpha`](https://github.com/api3dao/airnode/tree/pre-alpha) version (branch) of airnode packages, deployer included. What problems did you run into when you were trying out the airnode-starter?

**Comment by joshcaskie** [comment]
When I get to the **[Deploy](https://github.com/api3dao/airnode-starter#deploy)** phase of airnode-starter, running 
```
docker run -it --rm ^
  --env-file .env ^
  --env COMMAND=deploy-first-time ^
  -v %cd%:/airnode/out ^
  api3/airnode-deployer:pre-alpha
```
throws this Docker error:
![image](https://user-images.githubusercontent.com/57299645/120821548-90468500-c523-11eb-83fc-b418d961fbfb.png)

From your last comment I realized I was working with the master airnode branch, so I switched to pre-alpha and built the container `api3/airnode-deployer:pre-alpha` using the Dockerfile, but I'm still getting this error. (But also, there's no reference to do that in the airnode-starter Readme, it just says do the above command without building any containers, so is that assumption correct?)

Thanks!

**Comment by amarthadan** [comment]
Yes, you don't need to build the container, it's already available on [DockerHub](https://hub.docker.com/r/api3/airnode-deployer).
Your error is most likely caused by the spaces in your current directory path that's being substituted within the command. Try enclosing the variable with quotes (`"`):
```
-v "%cd%":/airnode/out
```

**Comment by joshcaskie** [comment]
That did it thank you!

**Comment by amarthadan** [comment]
Happy to help :slightly_smiling_face:
