### ISSUE TITLE
Obsolete type

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#371]
These are obviously outdated
https://github.com/api3dao/airnode/blob/62fb83763f9c3592acfcfcd6a2a8721ae4cf67f4/packages/node/src/types.ts#L169

and it looks like it's being hardcoded
https://github.com/api3dao/airnode/blob/04df0c176765b6dc582ecf3c78204ab3be5c551c/packages/node/src/coordinator/calls/aggregation.ts#L11

Do we even need this type?

**Comment by andreogle** [comment]
Good catch. This can be removed
