### ISSUE TITLE
"Reserved parameters" are referred to as "response parameters"

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#372]
Reserved parameters used to be referred to as response parameters previously, but now changed in the OIS format. The node/adapter code still refers to these as response parameters, even in [error code 14](https://docs.google.com/spreadsheets/d/1DanVn7WyP96D5max2_5T5enJz7TcCsRceoqDfDfCcnA/edit#gid=0).

**Comment by acenolaza** [comment]
Done. Just need to update error code 14

**Comment by andreogle** [comment]
@acenolaza can this be closed now?

**Comment by acenolaza** [comment]
> @acenolaza can this be closed now?

Yes, I believe we can. I'll also close [371](https://github.com/api3dao/airnode/issues/371)
