### ISSUE TITLE
Adding functional rules for ESLint

### ISSUE THREAD

**Issue by andreogle** [api3dao/airnode#404]
A lot of effort was put in to ensure Airnode is as functional in nature as possible. This especially applies to the `node` package, but includes some of the other packages too. In order to keep this style consistent going forward, I think we should include https://github.com/jonaskello/eslint-plugin-functional

I did a quick check and this can't be applied to some packages (like `deployer`) without massive changes, but it can be applied to the other packages relatively easily by disabling a few of the default rules. I also don't think it needs to be applied everywhere either so that's not a problem.

**Comment by Siegrift** [comment]
I don't think there is anything fundamentally wrong in doing local mutations, so I actually dislike this rule. 

(And not only me: https://twitter.com/dan_abramov/status/1209116108122415104 )

**Comment by sitch** [comment]
I started to play with some functional rules: https://github.com/chainapi/chainapi-ui/blob/main/packages/eslint-plugin-api3/fp.recommended.js We could probably move/publish some of that into the `api3dao` org namespace

I found most rules were more annoying than helpful in the react/web context, but could prove frutiful here.

@Siegrift I agree that there is nothing _fundamentally_ wrong with mutations, in fact it's pretty much required for fast code execution, but using a linting rule like this is very helpful bc it requires manually declaring local mutation, meaning that now the codebase is either safer and riper for optimization or it's developers have declared the rationale behind it's use (i.e., it's a hot code path and we determined it critical for XYZ)

**Comment by sitch** [comment]
another thing you can do is match `.fp.ts` as a file suffix for these rules

**Comment by andreogle** [comment]
I also don't think there's anything necessarily wrong with local mutations, but I do lean pretty strongly to avoiding them where possible. I think it should be opt-out if you want to mutate a local variable. i.e. the developer should make a conscious decision that mutability is necessary for a given function and then add an `eslint-disable-line ...` comment.

I don't like the different extensions like `.fp.ts`. I think this is going to be too easy to forget.

I'm busy working on this at the moment and what I did is to create a separate `.eslintrc.fp.js` config with some base functional rules. Packages that are able to then extend this extra config, do so. Each package can optionally have it's own `.eslintrc.js` (that [extends the base config and the "functional" config](https://github.com/api3dao/airnode/blob/eslint-plugin-functional/packages/ois/.eslintrc.js)), or it can just get it's config from the base `.eslintrc.js`. Seems like this works pretty well

**Comment by amarthadan** [comment]
I'm not really sure how I feel about this. I'm affraid it'll be more anoying than usefull. But it depends on the rules we decide to enable. So I'm not against it but the set of rules should be sane enough not to be anoying :smile:

**Comment by andreogle** [comment]
I spent some time looking into this over the weekend. You can set a pattern for variable names so that they can opt-out of the immutable data rule. I went with variable names prefixed with `mutable` and I quite like it since it makes the intention clear. There are very few places (outside tests) where it's even needed at the moment. I haven't added these rules to the `protocol` or `deployer` packages
