### ISSUE TITLE
The "require minimum confirmations" feature is not implemented

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#41]
When idempotence is important, a client request should only be attempted to be fulfilled when the node is sure that the request exists, which requires a configurable parameter for how many blocks it should wait for. I think it's perfectly fine to not have this for now.

Tracked by https://api3dao.atlassian.net/browse/AN-160

**Comment by bbenligiray** [comment]
See `minConfirmations` here
https://github.com/api3dao/api3-docs/blob/master/airnode/2-7-config-json.md#potential-update-to-nodesettings

**Comment by bbenligiray** [comment]
Added as a part of [config.json](https://github.com/api3dao/api3-docs/blob/master/airnode/2-7-config-json.md#chains) but not being used yet.

**Comment by bbenligiray** [comment]
Is this v0.1.0 worthy?

**Comment by andreogle** [comment]
If we're considering v0.1.0 an MVP, then no, but I don't think this is particularly difficult to implement though (?)

**Comment by bbenligiray** [comment]
I guess we shouldn't mark things v0.1.0 on the basis that they are easy to implement so I won't

**Comment by bbenligiray** [comment]
Closing this as an issue, as we removed the references to it in the docs and it became like any of the other features that are not implemented yet
