### ISSUE TITLE
If statusCode is not 0, data should return an empty bytes string

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#416]
Currently, `data` returns `bytes32(0)` if there is no valid value.
https://github.com/api3dao/airnode/blob/6f31a4c27d40e86101673bf37d223fef6625dfdd/packages/node/src/evm/fulfillments/api-calls.ts#L97
Most people don't handle `statusCode!=0` and then complain about the Airnode incorrectly returning 0. To prevent this, the data should return `0x` so that if they attempt to to decode it it will revert.

Also, should this happen if `statusCode!=0 || !request.responseValue`?

**Comment by andreogle** [comment]
I think we should always return `0x` if `requests.statusCode > 0`. I'm not sure about checking `!request.responseValue` since there might be valid falsey values, like 0 or empty string, that we want to return (?)

**Comment by acenolaza** [comment]
`bytes` data type in solidity is just syntactic sugar for `byte[] `so I'm wondering if sending an empty array isn't the best option here instead of forcing a revert on the client side. This way they will not have side effects when status code != 0.

**Comment by bbenligiray** [comment]
I don't think so, I think doing checks like `aParameterOfBytesType.length != 0` is pretty common (so an empty `bytes` type variable is valid). If we reverted then we wouldn't be able to return a non-zero status code.

**Comment by bbenligiray** [comment]
Tracked by https://api3dao.atlassian.net/browse/AN-143
