### ISSUE TITLE
Admin package is not listening for the correct event

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#427]
See the initial implementation of the admin package
https://github.com/api3dao/airnode/blob/8925313e42a79137f9a342f5bf4267702e3c48a4/packages/admin/src/index.ts
It listens for the specific transaction receipt, then parses the log associated with that

The current implementation listens for unfiltered events from the contract. For example here
https://github.com/api3dao/airnode/blob/master/packages/admin/src/implementation.ts#L61
it makes a transaction to create a template and returns the first template ID that is emitted from the contract, which may very well belong to some other template.

**Comment by Siegrift** [comment]
Fixed by https://github.com/api3dao/airnode/pull/455
