### ISSUE TITLE
Add support for variable interpolation to validator

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#430]
Depending on #429

**Comment by bbenligiray** [comment]
Blocks https://github.com/api3dao/airnode/issues/470

**Comment by bbenligiray** [comment]
Related to https://github.com/api3dao/airnode/issues/431#issuecomment-895075999

**Comment by bbenligiray** [comment]
Tracked by https://api3dao.atlassian.net/browse/AN-141
