### ISSUE TITLE
Availability of env variables in `secrets.env` is not checked

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#431]
Both known variables (e.g. `HEARTBEAT_API_KEY`) and custom variables (based on expected variables in `config.json` - see #429).
Check will happen both as part of deployment process (before the deployment) and as part of the node run (before the actual run).

Tracked by https://api3dao.atlassian.net/browse/AN-140

**Comment by bbenligiray** [comment]
Won't the validator already do this?

**Comment by amarthadan** [comment]
I don't think validator does this. This is ment to be a check for expected secrets, e.g. `HEARTBEAT_API_KEY`, `MASTER_KEY_MNEMONIC`, `ENDPOINT_TESTING_API_KEY`. And the plan is to implement the test at one place and use it both before the node run and before its deployment.

**Comment by bbenligiray** [comment]
Should checking `secrets.env` not be in the scope of the validator at all then? I think being clear about this is better than the current vague duplication.

**Comment by amarthadan** [comment]
But how do you want to do that? Validator is built to validate JSON documents. We would have to convert the `secrets.env` to JSON first and check the result. Since there are just few known secrets to be checked so far it feels a bit unnecessary.

**Comment by bbenligiray** [comment]
Let's talk about it at the Airnode call

**Comment by bbenligiray** [comment]
Not applicable to pre-alpha
