### ISSUE TITLE
Specify double quotes in Windows deployment command docs

### ISSUE THREAD

**Issue by camronh** [api3dao/airnode#457]
## Description

The [deployment command instructions](https://docs.api3.org/pre-alpha/guides/provider/deploying-airnode.html#deployment) specify that windows users should replace `$(pwd)` with `%cd%`. 

This results in the invalid command:

```bash 
docker run -it --rm ^
  --env-file .env ^
  --env COMMAND=deploy-first-time ^
  -v %cd%:/airnode/out ^
  api3/airnode-deployer:pre-alpha
```

`%cd%` should be wrapped in double quotes as `"%cd%"`.

## Steps to reproduce
Fails: 

```bash 
docker run -it --rm ^
  --env-file .env ^
  --env COMMAND=deploy-first-time ^
  -v %cd%:/airnode/out ^
  api3/airnode-deployer:pre-alpha
```

Good:
```bash 
docker run -it --rm ^
  --env-file .env ^
  --env COMMAND=deploy-first-time ^
  -v "%cd%":/airnode/out ^
  api3/airnode-deployer:pre-alpha
```

**Comment by bbenligiray** [comment]
Weird, I tried the one without quotations myself and know about at least two people who have used it successfully. Does this happen with cmd?

**Comment by camronh** [comment]
Had a provider attempt to deploy on windows and got an `Invalid Reference Format` error. It looked like a standard CMD but I can't be sure. Adding the quotes based on the top answer [Here](https://stackoverflow.com/questions/46940191/docker-exe-invalid-reference-format) seemed to fix it.

(Also, I don't think have permission to transfer the issue. We can close this and open a new one if you like)

**Comment by bbenligiray** [comment]
I see, it looks like this is only a problem if `%cd%` returns a path with whitespace
I created a replacement issue, closing this. Thanks a lot @camronh
