### ISSUE TITLE
Add metrics to the heartbeat

### ISSUE THREAD

**Issue by andreogle** [api3dao/airnode#465]
## Description

Currently, the heartbeat sends a simple POST with only the API key and deployment ID. We should enhance this to include a few metrics from the coordinator run.

Some metrics that should be readily available:

1. The time the coordinator took to run
2. The number of successful API calls that were made (count `AggregatedApiCall` with a `responseValue`
3. The number of errored API calls (count `AggregatedApiCall` with an error code). Double check what sets the aggregated API call error code too.
4. The number of API call fulfillments, grouped by chain type and chain ID (count `ApiCall` where status = 'Submitted')
5. The number of withdrawals, grouped by chain type and chain ID (count `Withdrawal` where status = 'Submitted')
6. The block number for each provider, chain type and chain ID. Might be useful for building a history and diagnosing problematic providers

There may be other metrics worth adding too

**Comment by bbenligiray** [comment]
Tracked by https://api3dao.atlassian.net/browse/AN-135
