### ISSUE TITLE
API test calls

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#468]
(I'm breaking https://github.com/api3dao/airnode/issues/97 down into components. This issue will also broken down further in the near future.)

We want the Airnode operator to be able to expose an HTTP endpoint that allows off-chain API calls. This can be used to
- Test integrations
- Test if the node is available
- Allow potential clients to test the API (for example, through a platform such as ChainAPI)
- Allow requesters to verify the response schema for a specific call and provide their reserved parameters on the on-chain call accordingly (again, through a platform such as ChainAPI)

Note that the last two features were already offered in Honeycomb. Here, this feature is largely being built for ChainAPI, yet it is built in a way to allow the node operator to use this themselves (e.g., with Postman) or allow integration with another platform.

In the initial implementation, we want the node operator to be able to define an API key for this endpoint in the `secrets.env` file. In the future, we may want to allow the node operator to set a call limit for example (as mentioned in https://github.com/api3dao/airnode/issues/343#issuecomment-889111907), especially if this is easy to implement.

This is actually more of a nice to have for v0.1.0, but it looks like it'll be done in time anyway.

**Comment by bbenligiray** [comment]
I always thought this would live in a separate `api` package because test calls are not a part of the node functionality (so it shouldn't be in the `node` package) but we want the containerized version to support this as well (so it shouldn't be in the `deployer` package). @andreogle what do you think?

**Comment by andreogle** [comment]
Sounds good. 

I'm not sure the testing part can live outside of the node package since (I think) the node doesn't directly expose the functionality to call the API. Needs more investigation though. The testing functionality on `main` currently lives in the node package.

**Comment by amarthadan** [comment]
Moving the functionality from the node package shouldn't be that difficult. To support this in a containerized version there would have to be an HTTP server accepting requests and calling the handler. For serverless this is done by the AWS API Gateway.

But both those things seem like a different issues. The issue described here is already done. I propose closing this and opening those two mentioned.

**Comment by bbenligiray** [comment]
Closing this because it's already implemented
