### ISSUE TITLE
Design a release plan

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#473]
Releasing a new node version has multiple steps such as
- Build and publish the Docker container
- Publish the individual monorepo packages as npm packages
- Publish a new documentation version
- Other things I forgot about...

**Comment by amarthadan** [comment]
By design you mean just formalizing a process, e.g. writing down the steps and following them each time we release or comming up with some automation for this?

**Comment by bbenligiray** [comment]
The former, at least for now

**Comment by bbenligiray** [comment]
Closing to be tracked by https://api3dao.atlassian.net/jira/software/projects/AN/boards/18/backlog?selectedIssue=AN-80
