### ISSUE TITLE
Create a bug bounty program

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#474]
The closest thing we have to a bug bounty is
https://github.com/api3dao/api3-dao#bug-bounty

We need to do this properly, add it to docs, link it from the repo READMEs.

**Comment by wkande** [comment]
I created an api3-docs issue to remind me to add this when the program is well defined. #149

**Comment by bbenligiray** [comment]
Closing this to be tracked by https://api3dao.atlassian.net/jira/software/projects/CT/boards/28?selectedIssue=CT-1
