### ISSUE TITLE
Move API test call functionality into its own package

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#479]
Airnode can expose an HTTP endpoint for API test calls. The related functionality is currently implemented in the `node` package https://github.com/api3dao/airnode/issues/468
Since this is not a part of the base node functionality (and as a result would need to implemented differently for the serverless and containerized versions), maybe it should be implemented in its own package (`api` or `airnode-api`). Note that this is only a suggestion, let me know if you don't agree.

**Comment by Siegrift** [comment]
I agree. This actually confused me initially as I thought the test calls are somehow going through airnode (but that doesn't make sense).

**Comment by bbenligiray** [comment]
Closed to be tracked by https://api3dao.atlassian.net/browse/AN-113
