### ISSUE TITLE
Containerized Airnode doesn't support API test calls

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#480]
Airnode can expose an HTTP endpoint for API test calls (https://github.com/api3dao/airnode/issues/468). Currently, this is only implemented for the serverless version through an API Gateway.
Here's a useful user path: The user integrates an API, then wants to test their integration through a local Airnode in an automated way using the `example` values of the parameters (https://docs.api3.org/pre-alpha/airnode/specifications/ois.html#_5-5-6-example). This would need API test calls to be implemented on the containerized version, which would be done by implementing an HTTP server (https://github.com/api3dao/airnode/issues/468#issuecomment-895014284).

Tracked by https://api3dao.atlassian.net/browse/AN-112

**Comment by Siegrift** [comment]
Is this worth adding to the v0.1.0 target? (I think no)

**Comment by amarthadan** [comment]
I agree with @Siegrift. But can be fun, I'm calling dibs :smile:

**Comment by bbenligiray** [comment]
Closing this issue in line with the changes in how we use Github issues internally. This is tracked by a Jira issue that will be migrated here.
