### ISSUE TITLE
Airnode examples broken

### ISSUE THREAD

**Issue by Ashar2shahid** [api3dao/airnode#636]
## Description

After #622  has been merged to master the Airnode example (coingecko) seem to be broken.  

## Version

Master Branch 
Node - v14.17.1
Yarn - v1.22.10

## Present Behaviour

When Running the example and deploying the airnode with command `yarn deploy-airnode` it returns 
```
Invalid Airnode configuration file: [{"message":"nodeSettings.nodeVersion: nodeVersion should be set to 1.0.0","level":"error"}]
```

On Setting the version to 0.1.0, we get the following error:
```
 nodeVersion under nodeSettings in config.json is 1.0.0 while the deployer node version is 0.1.0
```

## Expected Behaviour

It should deploy without any errors

## Steps to reproduce

Follow the steps in the example package

**Comment by bbenligiray** [comment]
Reportedly this is now fixed
