### ISSUE TITLE
Use JMESPath for Airnode _path reserved parameter

### ISSUE THREAD

**Issue by 37Rb** [api3dao/airnode#690]
## Description

It would be powerful if we could pass [JMESPath](https://jmespath.org/) queries (or something similar) in the _path parameter so that JSON responses can be transformed and filtered before the data is put on-chain.

See examples here: https://jmespath.org/examples.html

## Version

All

## Present Behaviour

Currently _path is processed by a (seemingly) basic query processor.

## Expected Behaviour

We should be able to use a more powerful off-the-shelf JSON query language to select data from responses. If the _path value is fed into JMESPath then users would have more control over API responses.

**Comment by Siegrift** [comment]
Relates to https://github.com/api3dao/airnode/issues/507

**Comment by bbenligiray** [comment]
Reminds me of https://docs.paralink.network/developer-guide/paralink-query-language.html
There are three issues with this approach:
- Requires requester to learn thing
- It's still limited, for example lacks date operations, which are needed for a lot of use cases
- The packages that will be used to implement the feature tends to be under-maintainted (for example https://github.com/jmespath/jmespath.js)
But this is still an issue that needs to be addressed as Emanuel linked above. I sent you an invite to the call that we will be talking about the feasibility of a solution that potentially doesn't have the issues above.

**Comment by 37Rb** [comment]
> Requires requester to learn thing

I don't see that as a problem if it's a commonly used thing intended for this purpose.

> The packages that will be used to implement the feature tends to be under-maintainted (for example https://github.com/jmespath/jmespath.js)

Good point but it does seem heavily used with 6M+ weekly downloads. https://www.npmjs.com/package/jmespath

> It's still limited, for example lacks date operations, which are needed for a lot of use cases.

Agreed.

Sure, happy to join the call. I'm not a fan of a particular solution. Just learning to be an Airnode user and it's pretty clear that I would like to be able to manipulate API responses as a requester. This seemed like an easy way to get there.

**Comment by 37Rb** [comment]
This is relevant. https://github.com/jmespath/jmespath.site/issues/65#issuecomment-592613602
