### ISSUE TITLE
Single level _path fails?

### ISSUE THREAD

**Issue by An-dz** [api3dao/airnode#752]
## Description

It seems that a `_path` with a single level doesn't work on v0.3.1.

## Version

Airnode v0.3.1

## Present Behaviour

I have created an Airnode where the API responds with a simple JSON with a single key and I configured the endpoint `reservedParameters` like this:

```json
"reservedParameters": [
  {
    "name": "_type",
    "fixed": "int256"
  },
  {
    "name": "_path",
    "fixed": "scores"
  }
]
```

But the following witchcraft happens:

```
ERROR Unable to find response value from 
{
    "scores": "57896044889312237195750096412266029227848665016659598748611696315871396439764"
}
. Path: scores
```

## Expected Behaviour

I expect a single level `_path` to work. I have not tested on this Airnode for multi-level but I assume they work considering the examples you guys created have multi-level `_path`.

## Steps to reproduce

I believe the only thing needed is to use the Coingecko example but change the path to something in the first level.

**Comment by dcroote** [comment]
@An-dz  - I wasn't able to reproduce your error with the `0.3.1` client docker image and a coingecko single level path (`coingecko_rank` for the API endpoint `/coins/{id}`). Could you share your full `config.json`?

**Comment by bbenligiray** [comment]
I replaced the number [here](https://github.com/api3dao/airnode/blob/v0.3.1/packages/airnode-adapter/e2e/index.ts#L40) with `'57896044889312237195750096412266029227848665016659598748611696315871396439764'` and ran `yarn test:adapter` and got
```
Error: value out-of-bounds (argument=null, value="57896044889312237195750096412266029227848665016659598748611696315871396439764", code=INVALID_ARGUMENT, version=abi/5.5.0)
```

Experimenting a bit more, when I enter `'57896044618658097711785492504343953926634992332820282019728792003956564819967'` (`2^255 - 1`) there, the tests pass. When I enter `'57896044618658097711785492504343953926634992332820282019728792003956564819968'` (`2^255`) there, the tests fail with the error message above.

So the value your API returns doesn't fit into an `int256`. Failure in this case is the preferred behavior, but the error message is indeed a bit cryptic. I'll leave the issue open for you to confirm.

**Comment by An-dz** [comment]
Thank @bbenligiray, that was it.

The endpoint was creating a ***u***int256 since it deals with bit manipulation, now it creates a negative decimal number.

This endpoint is deprecated by the way – it comes from pre-alpha – but we already have code depending on it that we won't have time to upgrade for the array return introduced on v0.3.1.

Now Airnode just needs a better error message when this happens.

**Comment by bbenligiray** [comment]
> Now Airnode just needs a better error message when this happens.

Thanks for the update. We were already tracking this issue internally at a somewhat low priority so it will be addressed in one of the upcoming releases.
