### ISSUE TITLE
Need to verify designatedWallet-requesterInd

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#80]
All requests pass `designatedWallet` and `requesterInd`.

When the node receives a request, it should verify that `designatedWallet` is the address of `m/0/${requesterInd}` and ignore the request if this is not the case.

**Comment by bbenligiray** [comment]
Example:
https://github.com/api3dao/airnode/blob/696ebad7207b02ffba9b85f2bb57430425c7cd32/packages/protocol/test/UserFlow.js#L240-L244

**Comment by andreogle** [comment]
This will need to be done after templates have been applied, right? Short requests don't have `requesterInd` and `designatedWallet` until that point

**Comment by bbenligiray** [comment]
Yes
