### ISSUE TITLE
Run an example

### ISSUE THREAD

**Issue by abbasyazdinejad** [api3dao/airnode#812]
Hello,
I am trying to run Airnode's examples, but I have faced some errors during applying api3/airnode-deployer
docker or myself airnode-deployer.
Could you please provide a short video for running one of Airnode's examples that use AWS, and
Rinkeby network
![3](https://user-images.githubusercontent.com/17172810/152901848-4197ea92-6565-402b-80ab-a02211c9425e.JPG)
![2](https://user-images.githubusercontent.com/17172810/152901882-791b4cb0-dade-4187-8f66-b085593c7565.JPG)

**Comment by amarthadan** [comment]
Hi Abbas, glad to see your interest in Airnode.

Unfortunately, we currently don't have any videos showcasing Airnode and its usage, but that is an interesting idea, we'll consider making something like that in the future.

But we provide other resources you can take a look at.
* Here's our [documentation](https://docs.api3.org/airnode/v0.3/grp-providers/guides/build-an-airnode/) where you can read everything you need about Airnode. And here's a [quick tutorial](https://docs.api3.org/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/) about deploying Airnode to AWS.
* We also provide a package called [airnode-examples](https://github.com/api3dao/airnode/tree/%40api3/airnode-examples%400.3.1/packages/airnode-examples) with a convenient CLI that allows you to choose an integration and deploy it as you like. Just follow the README file. This is just for showcasing purposes though.

As for your error, the airnode-deployer is trying to read `config/secrets.env` file but such a directory/file doesn't exist. You'll find more information about what should such a file look like in the [documentation](https://docs.api3.org/airnode/v0.3/grp-providers/guides/build-an-airnode/configuring-airnode.html).

If you get stuck on something feel free to reach out.

**Comment by abbasyazdinejad** [comment]
Thanks for your providing these materials, but before I had studied them that I could not solve my problem till running it.
Hope that you provide a short video until we learn how can set up an environment and run Airnode samples.

**Comment by amarthadan** [comment]
We're happy to help you with your setup if you provide us with a bit more information:
* Description of what you're trying to do
* Version or Airnode you're using
* Exact steps & commands you've tried so far
* Any error messages
* Your `config.json`
* Your `secrets.env` without the actual secrets (just to check the correct variables)

**Comment by abbasyazdinejad** [comment]
Thanks for this. 
I got an error when I want to use this step-->$yarn sponsor-requester
Although
![image_2022-02-09_105233](https://user-images.githubusercontent.com/17172810/153237914-6d862ec2-7bdf-48fc-9a0d-cdbe993240ce.png)
 I have all required arguments, let's see attached pic.

**Comment by dcroote** [comment]
Hi, given that command, can you confirm you're up to [step 16 of the examples README](https://github.com/api3dao/airnode/tree/master/packages/airnode-examples#16-allow-the-sponsor-to-pay-for-requests-made-by-the-requester)? Have the preceding steps worked smoothly? Also, it looks like you're on Windows, is this true?

**Comment by Siegrift** [comment]
Hi, I have reproduced this error and it's because windows is unable to run the script that is invoke by the `yarn sponsor-requester` (see: https://stackoverflow.com/a/67060506). I will update the code to be windows compatible and let you know to try again.

**Comment by abbasyazdinejad** [comment]
@dcroote , @Siegrift : I am using Windows 10, and I run all of the steps without any error until step 16 for Authenticate Coinmarktcap example. Thanks for your update, Keep me posted; I am waiting for it.

**Comment by Siegrift** [comment]
Hi, I've implemented a fix for you since it was relatively an easy change on our side in https://github.com/api3dao/airnode/tree/win-examples-actions.

Can you checkout that branch and try whether it works for you? (It does work on my windows machine).

**Comment by abbasyazdinejad** [comment]
@Siegrift, It works for me, I really appreciate your viable work.

**Comment by abbasyazdinejad** [comment]
Finally, when I am doing Make a request, I have faced with this error:
![sss](https://user-images.githubusercontent.com/17172810/153726323-4dac434e-46c2-4ab0-9f8d-6b845910be38.JPG)

While I had an active API key for whether sample, I have this error: Timeout exceeded!
Regarding other samples like coinmarkcap there is Timeout exceeded! error for me. Please guide me in this regard.
