### ISSUE TITLE
Requester workflow

### ISSUE THREAD

**Issue by abbasyazdinejad** [api3dao/airnode#838]
I was wondering if you explain to me these cases in requester: ( Address where I can find the code of these in Airnode repository)

1- When the requester wants to send its request to Airnode (e.g Airnode is in AWS), is it possible to read this request during calling RRP protocol? 
2- After receiving the request to Airnode, when Airnode tries to fill a request from API, can we access Airnode remotely or via a gateway to observe which parameters the requester wants and Airnode provide?
3- Can we access to RRP protocol while it deploys on the chain?

**Comment by Siegrift** [comment]
1. Yes, Airnode does read these requests from the blockchain (specifically the RRP protocol). When the requester makes a request, the contract will emit an event that can be read by offchain services (e.g. Airnode). See: https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/contracts/rrp/AirnodeRrp.sol#L117

2. What the API expects is described in config.json under [OIS api specification](https://docs.api3.org/airnode/v0.4/grp-providers/guides/build-an-airnode/api-integration.html#step-2-specifying-the-api). The parameters that the requester can supply are described in [OIS endpoint specification](https://docs.api3.org/airnode/v0.4/grp-providers/guides/build-an-airnode/api-integration.html#step-3-specifying-airnode-endpoints). What the requester wants is specified by [reserved parameters](https://docs.api3.org/ois/v1.0.0/reserved-parameters.html). There is no concept of gateway or remote access to Airnode (except AWS dashboard where you can find logs and other information). I am not sure if this answers your question. Can you maybe describe what is your use case?

3. Yeah, once the RRP contract is deployed (and you know the deployed address) you can access the contract. However, you should not need to interact with RRP contract directly. What is your use case?

**Comment by bbenligiray** [comment]
Closed due to inactivity
