### ISSUE TITLE
Authorization check should treat [] and [0x0] differently

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#86]
The authorization check shouldn't call the contract if `authorizers` is `[]` (return `false` automatically) or `[ethers.constants.AddressZero]` (return `true` automatically)

**Comment by andreogle** [comment]
Could you expand a bit on this one? What "contract" are you referring to that shouldn't be called? At what point does this happen?

**Comment by bbenligiray** [comment]
For some reason, I thought that we provided `authorizers` to `checkAuthorizationStatus` from the node as an argument. So if the `authorizers` is `[]` or `[0x0]`, we would already know what `checkAuthorizationStatus` will return so we don't have to make the call. 

But this is not the case so nevermind :grin:
