### ISSUE TITLE
Divide the types file

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#89]
What do you think about dividing this into multiple files?
https://github.com/api3dao/airnode/blob/fd1fdf209ea22aba8b2bf980d4980011e850c955/packages/node/src/types.ts

**Comment by andreogle** [comment]
I kinda like having everything in a single file, but yeah we can divide them up

**Comment by bbenligiray** [comment]
I wanted to nudge you towards it in case you were already considering it. It's not really at the size that it's a problem. I'm closing this now, can be re-opened later.
