### ISSUE TITLE
fromBlock for fetching logs can possibly be negative

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#90]
https://github.com/api3dao/airnode/blob/fd1fdf209ea22aba8b2bf980d4980011e850c955/packages/node/src/core/evm/requests/event-logs.ts#L21

The Ethereum node probably does this itself, but ideally should be `max(0, options.currentBlock - FROM_BLOCK_LIMIT)`.

**Comment by andreogle** [comment]
Addressed here: https://github.com/api3dao/airnode/commit/cb1b598aceb54c23c68096258b9f5b0467c635b9
