### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#91]
Says it uses lodash get, but doesn't use it.

https://github.com/api3dao/airnode/blob/fd1fdf209ea22aba8b2bf980d4980011e850c955/packages/adapter/README.md#processbyextracting

**Comment by andreogle** [comment]
The `adapter` README got some love today:

1. https://github.com/api3dao/airnode/commit/5d667a607bf775d58644174b6056062275a64e46
2. https://github.com/api3dao/airnode/commit/c5d080751794040a3c85f009afac6bf588815bcc
