### ISSUE TITLE
Adapter lacks logging

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#92]
Adapter doesn't log anything. Would it need to return the logs to the coordinator? Can we pass metadata to the adapter instead (and that would also facilitate the `_metadata` reserved parameter)?

**Comment by andreogle** [comment]
Yeah we can make the adapter work in whatever way we want. Do you mean passing the `logOptions` object to the adapter? In the new dynamic configuration PR, it looks like:

```js
{
  format: 'plain', // or 'json'
  meta: { coordinatorId: '1234', providerName: 'infura-mainnet', chainId: 1, chainType: 'evm' },
  additional: {} // optional object with extra key/value data
}
```

How would passing metadata to the adapter facilitate the `metadata` reserved parameter? Not sure I follow this

**Comment by bbenligiray** [comment]
By metadata I meant things related to the request that are not API call parameters, like `requestId`. Nevermind though, it's a silly feature.
This feels like a duplicate of https://github.com/api3dao/airnode/issues/116 so I'm closing it.
