### ISSUE TITLE
Adapter casting numbers to Number

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#93]
I remember discussing this but it bothered me again.

https://github.com/api3dao/airnode/blob/fd1fdf209ea22aba8b2bf980d4980011e850c955/packages/adapter/src/response-processor/caster.ts#L32

This would be a problem if the API returned a Wei value for example. Why not parse as a big number directly?

**Comment by andreogle** [comment]
Yeah I don't think the existing behaviour is correct
