### ISSUE TITLE
Ethereum call retries are not consistent

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#95]
Some Ethereum calls are retried
https://github.com/api3dao/airnode/blob/fd1fdf209ea22aba8b2bf980d4980011e850c955/packages/node/src/core/evm/requests/requester-data.ts#L36
and some are not
https://github.com/api3dao/airnode/blob/fd1fdf209ea22aba8b2bf980d4980011e850c955/packages/node/src/core/evm/requests/event-logs.ts#L30

We need to come up with a guideline for how to decide

**Comment by andreogle** [comment]
Yeah I *think* this is covered by the `RetryProvider` class (since it's a default provider method), but I'm not sure. I agree that it's better to keep it consistent with a single way of retrying

**Comment by bbenligiray** [comment]
>RetryProvider
Right, I forgot about this. Yeah, then only depending on this should be preferable imo.

**Comment by andreogle** [comment]
All request fulfillment calls are currently *not* retried at all. Just something to note. I imagine we want these to retry too
