### ISSUE TITLE
Validation across config.json and security.json

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#99]
There are two things to be validated between the `config.json` and `security.json` files:
- `id` fields of the two files must be the same
- All security schemes in `config.json` (`ois.*.security`) must exist in `security.json` (`apiCredentials.{oisTitle}`)

**Comment by andreogle** [comment]
Do we want this to throw an error or return an object like `{ valid: false, messages: ['...'] }`. Should it exit with status 1?

**Comment by bbenligiray** [comment]
For I imagine myself using it for deployment, I would prefer it to return an object.

Btw there is also the error vs. warning thing here. For example what if `security.json` includes security schemes that don't exist in `config.json`? So we keep have the `{ valid: false, messages: ['...'] }` structure (and even have this wrap `isOisValid` and bubble up messages from that)

**Comment by bbenligiray** [comment]
Another thing to check for:
- Either `nodeSettings.providerId` in `config.json` or `masterKeyMnemonic` in `security.json` must be present. If both are missing, the files are invalid.

**Comment by bbenligiray** [comment]
Note that I deleted an outdated post above. Here's a complete (?) list of things to check for

## `config.json`
- `ois` must be a non-empty list. We can also warn the user if there is an OIS in this list that is not used for any of the `triggers.request` items (it's redundant and should be removed).
- `triggers` can only have a key named `request`
- `triggers.request` must be a non-empty list (this would be more complex when we have other `triggers` keys but for now it's good enough)
- Each `triggers.request` must have the keys `endpointId`, `oisTitle`, `endpointName`. The `oisTitle`&`endpointName` pair must match one of the items in `ois.*.endpoints`.
- `endpointId` must satisfy the following
```
const endpointId = ethers.utils.keccak256(ethers.utils.defaultAbiCoder.encode(['string'], [`${oisTitle}/${endpointName}`]));
```
- `nodeSettings` must have `stage`, `nodeVersion`, `logFormat`, `chains`. `providerIdShort` is optional.
- `chains` must be a non-empty list.
- `chains.*` must have `providerAdminForRecordCreation` (this name will change), `id`, `type`, `providers` (a non-empty list). It may also have an optional `contracts` key.
- `chains.*.providers` must have `name` and `url`. `blockHistoryLimit` and `minConfirmations` are optional.
- If `chains.*.contracts` exists, it can only have the keys `Airnode`, `Convenience` and `GasPriceFeed`. `chains.*.contracts` should not exist if `chains.*.id` is `1`, but I think we don't have to enforce that yet at the validator because we don't know which other chain IDs we wan't to protect yet, etc.
- `id` must exist and match the one in `security.json`

## `security.json`
- Find the endpoints that are relevant to the `triggers.request` items and find their respective OISes. All of the security schemes of these OISes must be defined in `apiCredentials`.
- Warn the user if there are entries in `apiCredentials` that are not relevant to the `triggers.request` items (they are redundant and should be removed).
- `id` must exist and match the one in `config.json`

I will come back to these to make sure I didn't miss anything. @andreogle can you also take a look some time?

**Comment by andreogle** [comment]
> If chains.*.contracts exists, it can only have the keys Airnode, Convenience and GasPriceFeed. chains.*.contracts should not exist if chains.*.id is 1, but I think we don't have to enforce that yet at the validator because we don't know which other chain IDs we wan't to protect yet, etc

Just a small note here, any extra `contracts` keys are ignored and the user does not need to supply all 3 addresses - it can be one or more. There is already validation for all of this in the node when the coordinator starts, although it might be more useful to get this information upfront, before deploying the node and then finding out something is wrong.

Otherwise looks good to me. Can't think of anything else here

**Comment by bbenligiray** [comment]
@andreogle I think we now require all `chains.*` objects to have the `contracts` key and all `contracts` objects to have all three contracts (`Airnode`, `Convenience`, `GasPriceFeed`), right?

**Comment by andreogle** [comment]
I haven't made that change yet to the node, but yeah I think that's what we decided(?). There will be no default contract addresses in the node. Rather, they will all need to be set in `config.json`

I think we can probably drop `GasPriceFeed` if we're just going to rely on the provider's `getGasPrice`?

**Comment by bbenligiray** [comment]
Yes, I'll update `config.json`
